### PR TITLE
Update temperature-converter error handling and parsing

### PR DESCRIPTION
**Pull request by mking**
this fixes the following issues:
1. on invalid temperature conversion, "0.0 Err" should be printed (currently, a stack trace is shown)
2. the temperature unit should be matched case-insensitively (per the description given in the xhtml)

### CODE REVIEW

**Comment by LightGuard** [comment]
This looks good to merge

**Comment by sgilda** [comment]
Merged and closed.
@pmuir , @LightGuard : do you think I need to apply these changes to the eap 6.1 quickstart?

**Comment by pmuir** [comment]
@sgilda I think we could

**Comment by sgilda** [comment]
Done. Issued pull https://github.com/jboss-eap/quickstart/pull/90

**Pull request closed without merging**
