### PR TITLE
[JDF-152] helloworld-mdb demonstrates JMS topic

### PR DESCRIPTION
**Pull request by jmesnil**
- add a 2nd MDB which receives messages from a topic
- let the servlet sends messageis either to the queue or to the topic
  (by adding the topic HTTP request parameter)
- update the README and remove the section about configuring the
  messaging subsystem for OpenShift, .openshift/config/standalone.xml is
  already properly configured for both AS7 and EAP6

The files EOL were using Windows format. I assumed it was an error and saved them using UNIX format

### CODE REVIEW

**Comment by jmesnil** [comment]
I removed the EOL stuff

**Comment by sgilda** [comment]
Very nice! I tested the local deployment and it works great. I still need to test the OpenShift. 
Nice job on the README. I only had a few minor comments.

@pmuir :  Do you want to review the code?

**Comment by jmesnil** [comment]
@sgilda I have amended the code with your remarks

**Comment by sgilda** [comment]
@jmesnil :  One last minor comment. 'Under Build and Deploy the Quickstart', the new console log messages need to be indented 4 more spaces to render correctly in the HTML.

**Comment by jmesnil** [comment]
good catch, I've fixed it.

**Comment by pmuir** [comment]
Looks good to me.

**Comment by sgilda** [comment]
Thanks Pete. Merged!

**Pull request merged**
