### PR TITLE
JDF-207 fix: remove references to passing settings on the Maven command ...

### PR DESCRIPTION
**Pull request by sgilda**
...line

### CODE REVIEW

**Comment by LightGuard** [comment]
Is this the first of many passes to add in the needed info about running each quick start?

**Comment by sgilda** [comment]
@LightGuard : I'm not clear about what to expect in the future with this. I'm just responding to this one issue. 

@pmuir: Can you comment ^^?

**Comment by pmuir** [comment]
This looks good.

@LightGuard All this pull does is remove the suggestion of doing this with a file other than ~/.m2/settings.xml

**Comment by LightGuard** [comment]
Okay, that's fine.

On Tue, Feb 19, 2013 at 12:10 PM, Pete Muir notifications@github.comwrote:

> This looks good.
> 
> @LightGuard https://github.com/LightGuard All this pull does is remove
> the suggestion of doing this with a file other than ~/.m2/settings.xml
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jboss-jdf/jboss-as-quickstart/pull/450#issuecomment-13791707.

## 

Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by sgilda** [comment]
@pmuir : Should I apply this change to the EAP 6.1 repository even though none of them use MavenDependencyResolver?

**Pull request merged**
