### PR TITLE
JBIDE-12915 - Kitchensink quickstart is missing .cheatsheet.xml

### PR DESCRIPTION
**Pull request by snjeza**
https://issues.jboss.org/browse/JBIDE-12915
Kitchensink quickstart is missing .cheatsheet.xml

I have changed cheatsheet.xml according to the jdf kitchensink quickstart.

### CODE REVIEW

**Comment by sgilda** [comment]
@snjeza or @pmuir: I'm a little confused by this pull. 

The kitchensink cheatsheet is named cheatsheet.xml, is in the root directory, and is a hidden file.
The helloworld-mdb cheatsheet is named helloworld-mdb.xml, is in a cheatsheets/ directory, and is not hidden.

Are cheatsheets supposed to be consistent in their appearance and use?

Also, I'm not sure how to test them other than import them into JDBS and open them using the Help --> Cheat Sheets menu.

**Comment by pmuir** [comment]
Agreed with @sgilda we should add instructions or something to the contribution guide about cheatsheets, how to author them and how to use them...

**Comment by snjeza** [comment]
.cheatsheet.xml is the default cheatsheet name that is opened by the JBoss Central/Project Examples wizards if there is not any declaration in the project example file.
If you add .cheatsheet.xml to the root of a project example, you don't have to change the project xml file.

**Comment by sgilda** [comment]
@snjeza  or @pmuir : 
If the standard is to put the cheatsheet in the root directory and name it `cheatsheet.xml`, should the helloworld-mdb cheatsheet be moved to the root directory and renamed from `helloworld-mdb.xml` to `cheatsheet.xml` (the first commit)?

Also, is it supposed to be a hidden file?

**Comment by pmuir** [comment]
@sgilda yes, let's move it. Calling .cheatsheet.xml will make  it hidden.

**Comment by snjeza** [comment]
You can name a cheatsheet of your choice.
However, if you name it .cheatsheet.xml and add it to the root of a project example, you don't have to change the project xml file.

**Comment by sgilda** [comment]
My biggest concern is consistency for the contributors and for the developers that access the quickstarts. If files are not named consistently or in a known location, it's confusing for everyone.

@snjeza : Do you want to make that change as part of this pull since you modified the helloworld-mdb.xml file?

**Comment by snjeza** [comment]
@sgilda I haven't modified the helloworld-mdb.xml file. You can ignore the 5e3624 commit.

**Comment by sgilda** [comment]
@snjeza : The helloworld-mdb cheatsheet appears in the changed files: https://github.com/jboss-jdf/jboss-as-quickstart/pull/363/files. it appears you added or removed a newline at the end of the cheatsheet. :-)

@pmuir: To clarify your comment above "yes, let's move it. Calling .cheatsheet.xml will make it hidden." I assume you mean we should move the helloworld-mdb.xml file to the root and rename it to cheatsheet.xml, correct? If so, I'll do that in a separate pull and go ahead and merge this one.

**Comment by pmuir** [comment]
@maxandersen can you create us a gist which is for a CONTRIBUTING.md that explains how people should deal with cheatsheets. This needs to cover:
- how to create them (could like to an eclipse guide for example)
- how to test them
- where to place them in each project

**Comment by sgilda** [comment]
@snjeza  I would like the first commit removed from this before a merge. Not sure why it's there.

@maxandersen, @pmuir : Other than that, is this ready to be merged?

**Comment by sgilda** [comment]
2013-03-28: Waiting for review by @pmuir and additional instructions from @snjeza for the CONTRIBUTING guide.

**Comment by sgilda** [comment]
@maxandersen: Have you had a chance to look at the comment made by @pmuir above (https://github.com/jboss-jdf/jboss-as-quickstart/pull/363#issuecomment-11608926) to explain how to create and test cheatsheets?

@pmuir: Should I go ahead an merge this one?

**Comment by sgilda** [comment]
That's how I imported it. 
This is very strange! 
I am using JDBS: Version: 7.0.0.GA. Build id: GA-v20130720-0044-B364, Build date: 20130720-0044

If I import kitchensink from my ~/jdf-quickstarts/kitchensink/ directory, it appears in JDBS as 'jboss-as-kitchensink'.
If I copy the kitchensink quickstart directory to my ~/workspace/ folder and import it from there, it appears in JDBS as 'kitchensink'.
Apparently, JDBS does something different when there is a parent POM file than when there is not?

Does that sound right?

That means if I only download one quickstart, the cheat sheet path will not be correct?

**Comment by sgilda** [comment]
Well, it appears that if you copy the project folder to a new location, it changes the path and the cheat sheet is no longer valid.  Can you confirm that what I see is the expected behavior? I believe the plans are to allow download of one quickstart at a time so I am concerned about the impact on the cheat sheets.

I am not testing it in the jdf-quickstarts/kitchensink directory and it seems to be working much better. Ignore my previous comments about paths and line numbers for now.

**Comment by snjeza** [comment]
When you test a cheat sheet that will be defined as a Maven project example, you have to import it using New>Import>Maven>Existing Maven Projects. 
The Project Examples plugin will create a project based on the project's artifactId in the pom.xml.
You can also use the project name as a variable which is especially important when adding a cheat sheet to an archetype. See https://issues.jboss.org/browse/JBIDE-14333 and http://docs.jboss.org/tools/whatsnew/examples/examples-news-4.1.0.Beta1.html
You can create a test project example using a Project Example user site and test the cheat sheet with the Project Examples wizard. See https://community.jboss.org/wiki/ProjectExamplesSites

**Comment by sgilda** [comment]
Per Max Andersen: This pull request is broken/not updated to use the new features in JBDS 7 to resolve files relative to the project where the cheatsheet is inside - which is what we added to avoid these exact issues.

@snjeza : Will you be able to make these changes?

**Comment by snjeza** [comment]
I will make those changes, but they will require JBDS 7/JBT 4.1

**Comment by sgilda** [comment]
I think that is fine. Don't you? We will just note it in the README file. Which reminds me, I will need to update the instructions.

**Comment by snjeza** [comment]
I have updated the PR. See https://issues.jboss.org/browse/JBIDE-12915?focusedCommentId=12794158&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-12794158

**Comment by sgilda** [comment]
@snjeza : Very cool cheat sheet! It is extremely helpful in understanding the quickstart. I made a few comments about minor issues. Some may be due to my lack of the understanding of how cheat sheets should work.

**Comment by snjeza** [comment]
I have updated the PR.

According to your suggestions, I have changed some labels, but they were mainly copied from http://www.jboss.org/jdf/quickstarts/jboss-as-quickstart/guide/KitchensinkQuickstart/

> Also, I don't understand this statement: 'the named producer field has dependent scope'
> I don't see @Dependent anywhere. Can you explain this statement to me? :-)

The @Dependent is the default scope. See http://docs.jboss.org/weld/reference/latest/en-US/html/scopescontexts.html#d0e1997

> This opens to the Overview page rather than the source for the pom.xml file, so it is not clear what this is referring to. 
> I can manually select the 'pom.xml' tab and see the highlighted lines. Is there a way to tell Eclipse to open that tab?.

The openFileInEditor command calls the default editor for pom.xml (the Maven POM Editor by default). We can't change the way in which some editor is opened, but will probably be able to change the openFileInEditor command to set the pom.xml tab when opening the Maven POM editor.

**Comment by sgilda** [comment]
@snjeza : Thanks for the explanations. This looks good to me and all steps now work.

@pmuir : Do you want to review the content? Since it was taken from http://www.jboss.org/jdf/quickstarts/jboss-as-quickstart/guide/KitchensinkQuickstart/, I assume you're good with it, but will wait to here from you before merging.

**Comment by maxandersen** [comment]
With respect to openFileInEditor changes then @snjeza please remember any changes to the commands have to be 100% api compatible so we don't break cheatsheets. The good thing about commands is though that they just use named parameters so its much easier to extend them - but still have to be careful.

**Comment by snjeza** [comment]
Of course, we can be adding new commands or optional parameters to the old commands, but we mustn't change the old commands, actions and parameters.

**Comment by sgilda** [comment]
Merged.

**Pull request closed without merging**
