### PR TITLE
Updated with some fixes for standalone mode.

### PR DESCRIPTION
**Pull request by jsight**
Updated based upon feedback...

### CODE REVIEW

**Comment by jsight** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1020859

**Comment by sgilda** [comment]
Thanks @jsight : I have one remaining question. What is the port for the access URL when you run the standalone server?

**Comment by jsight** [comment]
8080 (and 8180)... I actually changed this in the README.md, but it
probably needs to be separated out for standalone vs domain.

**Comment by sgilda** [comment]
Ignore the previous comment. I see the URL in the updated README file.

**Comment by sgilda** [comment]
Hold off on this merge. I need to test undeploy from domain and work on separate scripts.

**Comment by sgilda** [comment]
@jsight : Does your server ever hang when you start it with: bin/standalone.sh -c standalone-full-ha.xml

Mine hangs with no output after :

$ bin/standalone.sh -c standalone-full-ha.xml
= = =

  JBoss Bootstrap Environment

  JBOSS_HOME: /home/sgilda/tools/jboss-eap-6.2-ER5

  JAVA: /home/sgilda/JDKs/jdk1.7.0_09/bin/java

  JAVA_OPTS:  -server -XX:+UseCompressedOops -Xms1303m -Xmx1303m -XX:MaxPermSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true

= = =

^X^Csgilda@sgilda-T510 ~/tools/jboss-eap-6.2-ER5 $

**Comment by jsight** [comment]
I assume you are seeing this on the cloned node? If so, this is because of
a node id conflict. I've added some instructions covering this to the
section on cloning.

**Comment by sgilda** [comment]
No, this is the first server. I haven't even started the second server. Btw, I removed those directoies from the second server.

**Comment by jsight** [comment]
I haven't seen that with only one server running. Is anything happening in
the server.log at the time?

**Comment by sgilda** [comment]
Jess: Nothing in the log at all. See my trace above. It just puts out the bootstrap info and stops. 

I'll try with a clean server. I was using ER5. I'll try the ER6 server here: http://download.devel.redhat.com/devel/candidates/JBEAP/JBEAP-6.2.0-ER6/

**Comment by sgilda** [comment]
I discovered the console is not enabled when running the standalone server with the full HA profile. 

I modified the scripts to enable the console, added scripts to undeploy (the domain version needs the server group), and to remove the configuration from the server in both modes. 

I modified the files in Jess's pull and issued a new one: https://github.com/jboss-developer/jboss-eap-quickstarts/pull/692

Closing this one.

**Pull request closed without merging**
