### PR TITLE
Back out the addition of jpp-quickstarts to the complex dependencies

### PR DESCRIPTION
**Pull request by sgilda**
Previous commit results in jenkins build failure: http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jdf-quickstarts-ci/27/changes

### CODE REVIEW

**Comment by rafabene** [comment]
Holding until more investigation on why hudson is failing.

**Comment by sgilda** [comment]
Marek Schmidt investigated and discovered it was a problem with jenkins trying to be too clever with Maven, and failing during parsing of the poms even before running the actual maven.  He converted the job to just run the maven command. Closing this since it's not necessary.

**Comment by rafabene** [comment]
Thanks for this investigation! :+1:

**Comment by sgilda** [comment]
Yes, thanks Marek!

**Pull request closed without merging**
