### PR TITLE
Modified the jboss-as-html5-mobile quickstart to use a template instead if mixing HTML into the JavaScript.

### PR DESCRIPTION
**Pull request by kborchers**
[Underscore.js](http://documentcloud.github.com/underscore/) is used for the templating because it is simple to use and small. This is mostly a best practices change as the current method works perfectly but this helps to ensure developers are encouraged to not mix HTML with their JavaScript as it can get very cumbersome to maintain and even read in more complex applications.

### CODE REVIEW

**Comment by sgilda** [comment]
Hi Kris,
I tested this using Firefox/Fedora on my laptop. Is the expected behavior that I need to refresh the page to see the newly added member?
Thanks,
Sande

**Comment by kborchers** [comment]
Sande,
Thanks for reviewing this. That is definitely not expected behavior. I do not see that behavior in Firefox, Chrome, Safari or Opera on Win7 and I did not see that behavior on Chrome on OSX last night. I do see an issue with IE9 where even refreshing the page does not show the new member but that is also the case with the unmodified version. Do you see any errors that I could try to look into?

**Comment by sgilda** [comment]
There aren't any errors. This is what appears in the server log:
    11:29:18,041 INFO  [org.jboss.resteasy.cdi.CdiInjectorFactory](http--0.0.0.0-8080-3) 
        Found BeanManager at java:comp/BeanManager
    11:29:18,046 INFO  [org.jboss.resteasy.spi.ResteasyDeployment](http--0.0.0.0-8080-3) 
        Deploying javax.ws.rs.core.Application: class 
        org.jboss.as.quickstarts.html5_mobile.rest.JaxRsActivator$Proxy$_$$_WeldClientProxy
    11:30:01,650 INFO  [org.jboss.as.quickstarts.html5_mobile.rest.MemberService](http--0.0.0.0-8080-2) 
        Registering Mike Jones
However, the Current Members doesn't reflect the new member until I click "Reload current page" or CTRL-R.

I am running fedora 14 and Firefox 3.6.17. Maybe it's a browser setting. It must be something in my configuration setup.

**Comment by balunasj** [comment]
I'll try to get a look at these updates myself a little later this afternoon, and see if I can reproduce the behavior

Thanks for the pull request btw!  We knew this was an area we wanted to clean up!

**Comment by kborchers** [comment]
OK, so I am able to reproduce the issue in FF 3.6. I was testing FF 8 before. I am not sure what the problem is at the moment but it is also an issue in the unmodified source as well from what I can tell.  Once I move up to FF 4 or higher, both versions work as expected. I'll see if I can track down the issue.

Jay - No problem! I figured the best way to prep a little for our chat was to dive into your world, so here I am. :)

**Comment by kborchers** [comment]
OK, I believe I have tracked it down. It looks like Firefox older than 4 dies on `console.log()` statements unless Firebug is open. If I run either version in FF 3.6.17 with Firebug open, everything behaves as expected. If I comment out the `console.log("Member registered");` statement in app.js, everything works as expected even with Firebug closed ... except for errors which still have the `console.log()` statements. Would you like me to remove the `console.log()` statements?

**Comment by sgilda** [comment]
Good find! I installed Firebug, opened it and it works great.

Jay or Pete, it's your decision.

**Comment by balunasj** [comment]
Sande - I'll let you know later today, but the updates look good so far - although I've not tried it live yet.

**Comment by sgilda** [comment]
OK. Sounds good.

One idea would be to add a comment to the README.md file saying if you 
are on Firefox 3.6 or older, the list will not automatically refresh 
unless you install Firebug and open it?

**Comment by balunasj** [comment]
I reviewed and tried the changes and I like the updates.  We'll need to get the same updates into the archetype as well.  I'll create a jira to cover this.

Pete, Sande - please merge the pull request when you can.

Kris - we'll talk tomorrow, and thanks for the updates!

**Comment by pmuir** [comment]
Merged.

**Comment by sgilda** [comment]
Hi Jay and Kris,

I am removing the '<repositories>' and '<pluginRepositories>' from the 
quickstarts.

I noticed the kitchensink-html5-mobile quickstart in 
https://github.com/jbossas/quickstart/ contains these sections, however, 
the version in https://github.com/aerogear/as-quickstarts/ does not.

I'm assuming that the merge to remove them in  
https://github.com/jbossas/quickstart/ just hasn't happened yet. Is that 
correct?

Thanks,
Sande

**Comment by sgilda** [comment]
Yup, we will be releasing 1.0.0.m3 on the 24th. It will have these changes and  others.

**Comment by sgilda** [comment]
That's what I figured. Thanks!

**Pull request closed without merging**
