### PR TITLE
Quickstart 59: XA datasource configuration and recovery

### PR DESCRIPTION
**Pull request by mmusgrov**
Shows how to perform XA transactions on an H2 database with recovery
This pull request replaces https://github.com/jbossas/quickstart/pull/49

### CODE REVIEW

**Comment by mmusgrov** [comment]
Sande, in the previous pull request (that the current one is replacing) you commented that "the POM file versions need to be updated to avoid runtime errors and to allow the scripts that move the quickstart to EAP to work". Do you recall which artifacts caused the problems, I only remember one of them being wrong).

**Comment by sgilda** [comment]
Mike, I don't recall. If I notice anything, I'll let you know. 
I'll check this one out next. Thanks!

**Comment by sgilda** [comment]
Quick question about the readme:
You say: Do the same for java:jboss/datasources/H2XADS2
        > cd /subsystem=datasources/xa-data-source="java:jboss/datasources/H2XADS2"
        :write-attribute(name="recovery-username",value="sa")
        :write-attribute(name="recovery-password",value="sa")
        :write-attribute(name="wrap-xa-resource",value="true")
The 3rd write-attribute for wrap-xa-resource wasn't specified in the instructions for H2XADS1. Should it have been? If not, maybe the instructions could note that it's an additional step for H2XADS2?

**Comment by sgilda** [comment]
Also, you can pass the --connect parameter on the jboss-admin.sh command and save a step. ;-)

bin $ ./jboss-admin.sh --connect
[standalone@localhost:9999 /]

**Comment by sgilda** [comment]
I think this may be a typo on the http://localhost:8080/jboss-as-xa page: black should be blank?
"Leave black to list all key/value pairs in each selected database"

**Comment by sgilda** [comment]
Mike, are you going to rename this one to "jta-crash-rec", per Tom's email?

**Comment by mmusgrov** [comment]
On 02/03/2012 03:41 PM, sgilda wrote:

> Quick question about the readme:
> You say: Do the same for java:jboss/datasources/H2XADS2
>          >  cd /subsystem=datasources/xa-data-source="java:jboss/datasources/H2XADS2"
>          :write-attribute(name="recovery-username",value="sa")
>          :write-attribute(name="recovery-password",value="sa")
>          :write-attribute(name="wrap-xa-resource",value="true")
> The 3rd write-attribute for wrap-xa-resource wasn't specified in the instructions for H2XADS1. Should it have been? If not, maybe the instructions could note that it's an additional step for H2XADS2?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jbossas/quickstart/pull/86#issuecomment-3798553
> I meant it to be added to both. BTW I mentioned it to Jesper and he said 
> the default value for wrap-xa-resource was already set to true. I need 
> to do a rebuild with the latest trunk to verify this. In the meantime I 
> will simply remove this step from the instructions (since it is a bug if 
> it is still set to false by default).

I have renamed the quickstart to jta-crash-rec and will commit my 
changes soon.

**Comment by mmusgrov** [comment]
I have cleaned up the commit so that you should have a clean patch to apply now

**Comment by sgilda** [comment]
Thanks Mike. I'll take a look at it.

**Comment by sgilda** [comment]
Very cool! I got it set up, crashed my server, and when I restarted it my database keys were still there!
I did have some moments of confusion though.
For example, the link says Now you should "enable Byteman by following the instructions below", but the headingfor that section says "Crashing the Application using Byteman". Do the steps in this section actually crash the server? When I completed that section my server wasn't running, but I don't know if that was a result of one of the steps in that section or if I had stopped my server at some point. So, I started the server, added the key/value. Then I crashed it myself and restarted it. The rows were still there, as advertised. :-)
I need to run through this again so I understand the process

**Comment by mmusgrov** [comment]
After you deploy the war you can add key value pairs to the database. However, if you install the byteman rule then the AS will halt _only after you try to add another key/value pair_.

The only explanation for the AS halting after installing the Byteman rule but before you try add a key/value pair is if their was already a pending transaction that the recovery system replayed the commit on.

**Comment by sgilda** [comment]
Mike. Ignore the previous question. I'm retesting now.

**Comment by sgilda** [comment]
Hi Mike, 
It took me too long to get back to this quickstart. Since you submitted it, they changed the name of the script that starts the jboss CLI from jboss-admin.sh to jboss-cli.sh, so the README file needs to be updated with this information.

I had a problem with step 8. The first time I started the server, I had the following errors in the console:
14:00:16,665 INFO  [org.hibernate.engine.transaction.internal.TransactionFactoryInitiator](MSC service thread 1-2) HHH000268: Transaction strategy: org.hibernate.engine.transaction.internal.jta.CMTTransactionFactory
14:00:16,670 INFO  [org.hibernate.hql.internal.ast.ASTQueryTranslatorFactory](MSC service thread 1-2) HHH000397: Using ASTQueryTranslatorFactory
14:00:16,707 INFO  [org.hibernate.validator.util.Version](MSC service thread 1-2) Hibernate Validator 4.2.0.Final
14:00:16,944 INFO  [org.hibernate.tool.hbm2ddl.SchemaUpdate](MSC service thread 1-2) HHH000228: Running hbm2ddl schema update
14:00:16,945 INFO  [org.hibernate.tool.hbm2ddl.SchemaUpdate](MSC service thread 1-2) HHH000102: Fetching database metadata
14:00:16,952 INFO  [org.hibernate.tool.hbm2ddl.SchemaUpdate](MSC service thread 1-2) HHH000396: Updating schema
14:00:16,966 INFO  [org.hibernate.tool.hbm2ddl.TableMetadata](MSC service thread 1-2) HHH000261: Table found: XAQS1.PUBLIC.XA_KVPAIR
14:00:16,966 INFO  [org.hibernate.tool.hbm2ddl.TableMetadata](MSC service thread 1-2) HHH000037: Columns: [name, value]
14:00:16,967 INFO  [org.hibernate.tool.hbm2ddl.TableMetadata](MSC service thread 1-2) HHH000108: Foreign keys: []
14:00:16,967 INFO  [org.hibernate.tool.hbm2ddl.TableMetadata](MSC service thread 1-2) HHH000126: Indexes: [primary_key_7, constraint_index_7]
14:00:16,968 INFO  [org.hibernate.tool.hbm2ddl.SchemaUpdate](MSC service thread 1-2) HHH000232: Schema update complete
14:00:18,622 WARN  [org.jboss.jca.core.connectionmanager.pool.strategy.OnePool](MSC service thread 1-6) IJ000604: Throwable while attempting to get a new connection: null: javax.resource.ResourceException: Could not create connection
    at org.jboss.jca.adapters.jdbc.xa.XAManagedConnectionFactory.getXAManagedConnection(XAManagedConnectionFactory.java:447)
    at org.jboss.jca.adapters.jdbc.xa.XAManagedConnectionFactory.createManagedConnection(XAManagedConnectionFactory.java:385)
    at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreArrayListManagedConnectionPool.createConnectionEventListener(SemaphoreArrayListManagedConnectionPool.java:758)
    at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreArrayListManagedConnectionPool.getConnection(SemaphoreArrayListManagedConnectionPool.java:343)
    at org.jboss.jca.core.connectionmanager.pool.AbstractPool.getSimpleConnection(AbstractPool.java:400)
    at org.jboss.jca.core.connectionmanager.pool.AbstractPool.getConnection(AbstractPool.java:365)
    at org.jboss.jca.core.connectionmanager.AbstractConnectionManager.getManagedConnection(AbstractConnectionManager.java:329)
    at org.jboss.jca.core.connectionmanager.tx.TxConnectionManagerImpl.getManagedConnection(TxConnectionManagerImpl.java:368)
    at org.jboss.jca.core.connectionmanager.AbstractConnectionManager.allocateConnection(AbstractConnectionManager.java:464)
    at org.jboss.jca.adapters.jdbc.WrapperDataSource.getConnection(WrapperDataSource.java:129)
    at org.hibernate.ejb.connection.InjectedDataSourceConnectionProvider.getConnection(InjectedDataSourceConnectionProvider.java:67) [hibernate-entitymanager-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.engine.jdbc.internal.JdbcServicesImpl$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcServicesImpl.java:253) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:119) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.service.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:75) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:159) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:131) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.cfg.SettingsFactory.buildSettings(SettingsFactory.java:71) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.cfg.Configuration.buildSettingsInternal(Configuration.java:2270) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.cfg.Configuration.buildSettings(Configuration.java:2266) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1735) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.ejb.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:84) [hibernate-entitymanager-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:904) [hibernate-entitymanager-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:889) [hibernate-entitymanager-4.0.1.Final.jar:4.0.1.Final]
    at org.hibernate.ejb.HibernatePersistence.createContainerEntityManagerFactory(HibernatePersistence.java:73) [hibernate-entitymanager-4.0.1.Final.jar:4.0.1.Final]
    at org.jboss.as.jpa.service.PersistenceUnitServiceImpl.createContainerEntityManagerFactory(PersistenceUnitServiceImpl.java:162) [jboss-as-jpa-7.1.0.Final.jar:7.1.0.Final]
    at org.jboss.as.jpa.service.PersistenceUnitServiceImpl.start(PersistenceUnitServiceImpl.java:85) [jboss-as-jpa-7.1.0.Final.jar:7.1.0.Final]
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811)
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) [rt.jar:1.6.0_25]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) [rt.jar:1.6.0_25]
    at java.lang.Thread.run(Thread.java:662) [rt.jar:1.6.0_25]
Caused by: org.h2.jdbc.JdbcSQLException: Database may be already in use: "Locked by another process". Possible solutions: close all other connection(s); use the server mode [90020-161]
    at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
    at org.h2.message.DbException.get(DbException.java:169)
    at org.h2.message.DbException.get(DbException.java:146)
    at org.h2.store.FileLock.getExceptionAlreadyInUse(FileLock.java:435)
    at org.h2.store.FileLock.lockFile(FileLock.java:332)
    at org.h2.store.FileLock.lock(FileLock.java:128)
    at org.h2.engine.Database.open(Database.java:539)
    at org.h2.engine.Database.openDatabase(Database.java:219)
    at org.h2.engine.Database.<init>(Database.java:214)
    at org.h2.engine.Engine.openSession(Engine.java:56)
    at org.h2.engine.Engine.openSession(Engine.java:159)
    at org.h2.engine.Engine.createSessionAndValidate(Engine.java:138)
    at org.h2.engine.Engine.createSession(Engine.java:121)
    at org.h2.engine.Engine.createSession(Engine.java:28)
    at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:285)
    at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:110)
    at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:94)
    at org.h2.Driver.connect(Driver.java:72)
    at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:181)
    at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:331)
    at org.jboss.jca.adapters.jdbc.xa.XAManagedConnectionFactory.getXAManagedConnection(XAManagedConnectionFactory.java:430)
    ... 30 more

14:00:18,645 WARN  [org.hibernate.engine.jdbc.internal.JdbcServicesImpl](MSC service thread 1-6) HHH000342: Could not obtain connection to query metadata : javax.resource.ResourceException: IJ000453: Unable to get managed connection for java:jboss/datasources/H2XADS2
14:00:18,647 ERROR [org.jboss.msc.service.fail](MSC service thread 1-6) MSC00001: Failed to start service jboss.persistenceunit."jboss-as-jta-crash-rec.war#pctx2": org.jboss.msc.service.StartException in service jboss.persistenceunit."jboss-as-jta-crash-rec.war#pctx2": Failed to start service
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1767) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) [rt.jar:1.6.0_25]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) [rt.jar:1.6.0_25]
    at java.lang.Thread.run(Thread.java:662) [rt.jar:1.6.0_25]
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: pctx2] Unable to build EntityManagerFactory
    at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:914)
    at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:889)
    at org.hibernate.ejb.HibernatePersistence.createContainerEntityManagerFactory(HibernatePersistence.java:73)
    at org.jboss.as.jpa.service.PersistenceUnitServiceImpl.createContainerEntityManagerFactory(PersistenceUnitServiceImpl.java:162)
    at org.jboss.as.jpa.service.PersistenceUnitServiceImpl.start(PersistenceUnitServiceImpl.java:85)
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
    ... 3 more
Caused by: org.hibernate.HibernateException: Connection cannot be null when 'hibernate.dialect' not set
    at org.hibernate.service.jdbc.dialect.internal.DialectFactoryImpl.determineDialect(DialectFactoryImpl.java:97)
    at org.hibernate.service.jdbc.dialect.internal.DialectFactoryImpl.buildDialect(DialectFactoryImpl.java:67)
    at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:172)
    at org.hibernate.service.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:75)
    at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:159)
    at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:131)
    at org.hibernate.cfg.SettingsFactory.buildSettings(SettingsFactory.java:71)
    at org.hibernate.cfg.Configuration.buildSettingsInternal(Configuration.java:2270)
    at org.hibernate.cfg.Configuration.buildSettings(Configuration.java:2266)
    at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1735)
    at org.hibernate.ejb.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:84)
    at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:904)
    ... 9 more

14:00:18,875 INFO  [org.jboss.as.server](Controller Boot Thread) JBAS018559: Deployed "jboss-as-jta-crash-rec.war"
14:00:18,878 INFO  [org.jboss.as.controller](Controller Boot Thread) JBAS014774: Service status report
JBAS014777:   Services which failed to start:      service jboss.persistenceunit."jboss-as-jta-crash-rec.war#pctx2": org.jboss.msc.service.StartException in service jboss.persistenceunit."jboss-as-jta-crash-rec.war#pctx2": Failed to start service

I shut down AS7 and restarted it, to close and open the database as you said, and when I access the results, I see this:

Database 1: key1=value1,key2=value2,key3=value3,crashkey1=crashvalue1,
Database 2: key1=value1,key2=value2,key3=value3,

Is that correct?
Thanks,
Sande

**Comment by sgilda** [comment]
Mike, to be clear, it should update both tables with the crash key/value after restart, correct?

**Comment by mmusgrov** [comment]
The stacktrace is reporting that there is already a connection to the H2 database. H2 is primitive and will only allow a single connection. Can you check whether you have the H2 console open else where.

Step 8 says that recovery should have occurred but it also states the following: 
_However XA support in the hypersonic product isn't great and after recovery the new SQL row will
    not be immediately visible - [the database needs to be closed and re-opened for it to make the
    changes visible](http://www.h2database.com/html/advanced.html#two_phase_commit).
    The easiest way to do this is to shutdown the AS thus releasing its connection to the recovered
    database. And now if you use use the H2 console to inspect the table
    (`SELECT * FROM XA_KVPAIR;`) you should see the missing row and there should no longer be an in
    doubt transaction. Similarly, if you restart the AS, you can use the example application to list
    the database contents._

ie you need to restart the AS another time to see the missing key/value pair show up in the second database.

**Comment by mmusgrov** [comment]
Sande, in view of the poor XA support provided by the H2 database I think it might be better to change the example to either use 2 JMX queues or a postgresql database and a JMS queue. I say this because postgresql and JMS both provide good XA support.

The downside is that postgresql can be tricky to set up (so 2 JMS queues could be preferable) and JMS requires standalone-full

What do you think?

**Comment by mmusgrov** [comment]
Actually 2 JMS queues wont work because Hornetq will just use a single XA connection to send both messages. Using 2 postgresql databases won't work either since they would need to be installed on different ports (or different hosts) which from a configuration point of view is difficult to set up. So the only options left are:
- 1 postgresql database and 1 JMS queue (in this case we will get clean recovery since each provides good XA support);
- stay with the existing example of using two H2 databases (and accept the proviso of having to restart the AS after recovery)

**Comment by mmusgrov** [comment]
I am implementing the following scenario:

The example first inserts a database row and sends a JMS message (containing the change) both within an XA transaction. Outside of the transaction the message consumer then modifies the row with some text that indicates that it received the message.

I will demonstrate recovery by allowing the first Db update to succeed and fail the JMS send (during commit). The user will see the new row in the database but not the JMS updated value. On restart after recovery happens the user will be able to see the JMS updated value.

This is an improvement on using 2 H2 databases since JMS does not suffer from the caveats we use when demonstrating H2 XA support since it is JMS that is recovering and not H2.

**Comment by mmusgrov** [comment]
The latest commit address comments from Burr and Sande.
It also changes the example by replacing the second database with a JMS producer.

**Comment by sgilda** [comment]
Hi Mike,
I tried this again. I'm a little confused by the README instructions at step 4. I deployed the application and added a bunch of key/value pairs. Step 4 says "Now you should enable Byteman by following the instructions below."
I add the JAVA_OPTS using my own path information. It says "These changes will only take effect during AS startup."
Step 5 says "If you have completed step 4 then you are ready to create a recovery record. Go to the application URL and insert another row into the database."
I added another row and nothing happened which is kind of what I expected. Since the JAVA_OPTS are not in effect until the server is restarted, I assumed I need to restart the server after step 4 and before step 5?
So I tried restarting the server. Then I got a status 404 for a while, but then the server seems to have halted.

**Comment by mmusgrov** [comment]
You are correct, after updating JAVA_OPTS you need to restart the AS (it was so much better when I told the user to use bminstall and bmsubmit thus avoiding the need for a restart).

So you changed JAVA_OPTS, restarted the AS which then halted before you had a chance to add another key/value pair? If that is correct then there must already have been a pending transaction from some other application (or from a previous run of this quickstart or Toms quickstart - yet another reason why using bminstall and bmsubmit is far superior). 

Do you have any transaction logs in the data directory (tree ../standalone/data/tx-object-store, if you do have any logs in there then during restart they are recovered and if my Byteman script is enabled that would cause the halt. You could clear out the logs before beginning the quickstart (rm -rf ../standalone/data/tx-object-store/).

**Comment by sgilda** [comment]
Pete, I'm good with this one. Has the code review been done?

I would like to wait for the EAP6 build to be completed on March 6 before processing this one though.

**Comment by mmusgrov** [comment]
Sande, the quickstart currently relies on the presence of testQueue in standalone-full.xml. Since this will be removed for EAP I am adding a JMS destination to the war file instead. I will issue another commit in the next hour or so.

**Comment by sgilda** [comment]
Yes. Tom did a similar fix to the jts quickstart. Will yours be similar?

**Comment by mmusgrov** [comment]
Yes it will, I am deploying a JMS queue inside the quickstart war archive. But I don't seem to be getting automatic recovery for it. I am investigating.

**Comment by mmusgrov** [comment]
If I paste the jms-destination directly into the standalone config file it works. I will need to put it into a debugger and pass the results over to Jesper

**Comment by mmusgrov** [comment]
I suspect that ironjacamar does not support the definition of JMS queues via war archives.
I have updated the README to show how EAP users can define a JMS queue via the standalone configuration file.

**Comment by sgilda** [comment]
Mike, have you looked at the jts quickstart that is currently in jbossas/quickstart/jts? That application defines the JMS queues in the WAR archives. At least I think it does. There's a hornetq-jms.xml file in each component's webapp/WEB-INF/ directory that defines the JTSQueue.

This is beyond me, so maybe this quickstart is different than that one?

**Comment by mmusgrov** [comment]
EAP does not support deployment of queues via war archives so it safer to tell the user to simply add the testQueue back into standalone-full.xml. [FYI, the queue works when deploying via a war, it is just that it isn't enabled for recovery]

**Comment by sgilda** [comment]
Now I understand and see the difference. Thanks!

**Comment by sgilda** [comment]
Hi Mike,
I'm afraid some users may be confused by the instructions in the README file under "Deploying the application". You start the application server in step 1. Step 2 starts with building and deploying the quickstart, but then talks about modifying the configuration file. Should that instruction be moved up before starting the server? Also, since there is no longer a jms-destinations element in the configuration file, I'm not sure they will be able to figure out where it should go in the file. Maybe it should say to look for and existing element under "<subsystem xmlns="urn:jboss:domain:messaging:1.1">" and if you can't find one, place the XML within the &lt;hornetq-server&gt; tags after the &lt;jms-connection-factories&gt;?  Should the snippet also contain the jms-destinations tag like this?

`<jms-destinations>
    <jms-queue name="testQueue">
        <entry name="queue/test"/>
        <entry name="java:jboss/exported/jms/queue/test"/>
    </jms-queue>
</jms-destinations>`

**Comment by sgilda** [comment]
Mike, 
In step 4, you say: "You should also ensure that there are no transaction logs left over from running other quickstarts". Should this also be done before you start the server the first time?

**Comment by sgilda** [comment]
I continued testing and ran into a problem. I'm sure it's something I'm doing wrong. This is what I did:
Started the server
Added key1/value1.
Stopped the server.
Added the byteman JAVA_OPTS to my standalone.conf
Added key2/value2
That killed the server.
Commented out the byteman JAVA_OPTS
Restarted the server
Hit the URL: http://localhost:8080/jboss-as-jta-crash-rec/
I only see key1/value1 displayed. I don't see key2/value2 that I added before the crash.
I try to add key3/value3, but get an error: org.hibernate.exception.GenericJDBCException: The database is read only; SQL statement: insert into XA_KVPair (value, name) values (?, ?) [90097-161] 

I see this in the server log:
14:50:15,815 WARN  [com.arjuna.ats.jta](Periodic Recovery) ARJUNA016037: Could not find new XAResource to use for recovering non-serializable XAResource XAResourceRecord < resource:null, txid:< formatId=131077, gtrid_length=29, bqual_length=36, tx_uid=0:ffff7f000001:-6d8c1375:4f5e4421:10, node_name=1, branch_uid=0:ffff7f000001:-6d8c1375:4f5e4421:15, subordinatenodename=null, eis_name=java:jboss/datasources/H2XADS1 >, heuristic: TwoPhaseOutcome.FINISH_OK, product: H2/1.3.161 (2011-10-28), jndiName: java:jboss/datasources/H2XADS1 com.arjuna.ats.internal.jta.resources.arjunacore.XAResourceRecord@aa1830 >
14:50:15,821 WARN  [com.arjuna.ats.jta](Periodic Recovery) ARJUNA016038: No XAResource to recover < formatId=131077, gtrid_length=29, bqual_length=36, tx_uid=0:ffff7f000001:-6d8c1375:4f5e4421:10, node_name=1, branch_uid=0:ffff7f000001:-6d8c1375:4f5e4421:15, subordinatenodename=null, eis_name=java:jboss/datasources/H2XADS1 >
14:50:15,848 INFO  [org.jboss.as.quickstarts.xa.DbUpdaterMDB](Thread-0 %28HornetQ-client-global-threads-13090704%29) Received Message: HornetQMessage[ID:101eb768-6c74-11e1-8c44-0024d78f9f14]:PERSISTENT
14:50:15,937 INFO  [stdout](Thread-0 %28HornetQ-client-global-threads-13090704%29) Hibernate: select kvpair0_.name as name1_0_, kvpair0_.value as value1_0_ from XA_KVPair kvpair0_ where kvpair0_.name=?
14:50:16,002 INFO  [org.jboss.as.quickstarts.xa.DbUpdaterMDB](Thread-0 %28HornetQ-client-global-threads-13090704%29) JTA Crash Record Quickstart: key value pair updated via JMS
14:50:16,016 INFO  [stdout](Thread-0 %28HornetQ-client-global-threads-13090704%29) Hibernate: insert into XA_KVPair (value, name) values (?, ?)
14:50:16,021 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper](Thread-0 %28HornetQ-client-global-threads-13090704%29) SQL Error: 90097, SQLState: 90097
14:50:16,022 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper](Thread-0 %28HornetQ-client-global-threads-13090704%29) The database is read only; SQL statement:
insert into XA_KVPair (value, name) values (?, ?) [90097-161]
14:50:16,042 WARN  [com.arjuna.ats.arjuna](Thread-0 %28HornetQ-client-global-threads-13090704%29) ARJUNA012125: TwoPhaseCoordinator.beforeCompletion - failed for SynchronizationImple< 0:ffff7f000001:74c74feb:4f5e455d:18, org.hibernate.engine.transaction.synchronization.internal.RegisteredSynchronization@186793e >: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: The database is read only; SQL statement:
insert into XA_KVPair (value, name) values (?, ?) [90097-161]

I will try again with a clean server.

**Comment by sgilda** [comment]
Mike, it worked when I started with a new clean app server. I think the key is to make sure there are no leftover transaction logs before testing this quickstart. An updated README should help. :-)

**Comment by mmusgrov** [comment]
You are right, well spotted. I have committed a change that includes a step on how to configure the testQueue just before step 1 where we ask the user to start the server.

**Comment by mmusgrov** [comment]
The README already includes an instruction to tell the user to clear out the logs in step 4 where is states:

"You should also ensure that there are no transaction logs left over from running other quickstarts"

It then goes on to describe how to do that.

I have included the instruction in step 4 because by this time the quickstart user should already be quite familiar with transaction logs and so the instruction should be more meaningful than if I put the instruction right up front before starting the server.  The steps leading up to it gradually familiarise the user with transaction concepts. Logically step 4 is the correct place to ask the user to make sure the transaction logs are empty.

If it helps then as you suggest I could put something up front that refers the user to step 4 for how to do it.

**Comment by mmusgrov** [comment]
You reported the error "GenericJDBCException: The database is read only" That happens when the H2 has an unfinished transaction and you are correct, that happened because the logs weren't cleaned out first. H2 support for recovery is very poor and that is why I moved to using JMS as the resource to use to demonstrate recovery. As long as the quickstart user follows step 4 before enabling Byteman it should be OK.

**Comment by sgilda** [comment]
Hi Mike, it appears my internal anchors are broken. I have things like `<a id="start-server">` and it should be `<a id="start-server"/>` or `<a name="start-server">`. Other than that, this one looks good to me.

Pete, does this need any more code review?
Thanks, Sande

**Comment by sgilda** [comment]
It appears the new scripts to generate html from markdown are buggy. The anchors work in my version. Also, your version is no longer generating lists correctly. I'll email you the markdown and generated html so you can see what I mean.
Pete, is there an alternative to Red Carpet? It's really difficult to get around the syntax bugs.

**Comment by sgilda** [comment]
I think this one is ready to go. Pete, did you need to review it?

**Comment by pmuir** [comment]
Merged :-D

Mike, Sande please review my merged version as I made a few updates to naming etc. I hope I caught all locations to change stuff.

**Comment by mmusgrov** [comment]
Thanks Pete for the  changes. Just three small points:

1) The queue name is jta-crash-rec-quickstart but the README refers to it as test. Since we now deploy the queue via the war we can just delete item 2 (in the first section "Build and Deploy the application")

2) Section 6 refers to an in memory H2 db. It should correspond to what's deployed in the war, ie a file based url:

jdbc:h2:file:~/jta-crash-rec-quickstart;DB_CLOSE_DELAY=-

3) You removed src/main/webap/readme.html - Sande had asked me to refer to the readme instructions from the web servlet XAServlet.java - the servlet pointed at that file so we should either reinstate readme.html or remove the link from the servlet output (my preference).

**Comment by sgilda** [comment]
I asked you to refer to the readme instructions from the XAServlet.java? 
I don't recall asking you to do that, but my memory isn't as good as it 
used to be. ;-)

**Comment by mmusgrov** [comment]
Mine isn't the best either, but on this occasion my memory isn't failing me :-) Your quote was (https://github.com/jbossas/quickstart/pull/49#issuecomment-3634685):

"When you run the application, it would be nice if the page had the same instructions that are in the README file so you don't have to switch back and forth to see how it works."

I resolved this comment by adding some explanatory text about the application followed by a link to an html version of the README (otherwise if I had duplicated the text it would have quickly got out of sync). Maybe it would be better to just say refer to the README for more information.

**Comment by sgilda** [comment]
Sorry. When you said "refer to", I read that as "link to".

I also wasn't very clear when I told you that. What I meant was, it 
would be nice to have general instructions on the running application 
page so you know what to do. :-)

Sorry for the confusion.

**Pull request closed without merging**
