### PR TITLE
Upgrade to Wicket 6.9

### PR DESCRIPTION
**Pull request by OndraZizka**
Tested.

### CODE REVIEW

**Comment by sgilda** [comment]
@OndraZizka : We generally try to keep all the quickstarts at the same version. Should all of them be updated to 7.4.Final of the JBoss Maven plugin? If so, we need to update them all, including the parent POM.

**Comment by OndraZizka** [comment]
Oh, ok, I didn't know.
JBoss AS plugin 7.4:  https://issues.jboss.org/browse/JBASMP#selectedTab=com.atlassian.jira.plugin.system.project%3Achangelog-panel
Seems like it won't harm to move all QS to 7.4.
I suggest to leave this at 7.4 in the meantime.

**Comment by sgilda** [comment]
@OndraZizka : Would you mind squashing the commits?

**Comment by sgilda** [comment]
@OndraZizka : Should all instances of  `<version.compiler.plugin>` be updated from 2.3.1 to 3.1 also?

**Comment by OndraZizka** [comment]
Squashed.

**Comment by sgilda** [comment]
Merged.

**Pull request closed without merging**
