### PR TITLE
Update pom.xml

### PR DESCRIPTION
**Pull request by bkhadige**
http://maven.repository.redhat.com/earlyaccess/all/org/jboss/bom/eap/jboss-javaee-6.0-with-resteasy/6.2.0.Beta1/jboss-javaee-6.0-with-resteasy-6.2.0.Beta1.pom (version 6.2.0.Beta1)

### CODE REVIEW

**Comment by sgilda** [comment]
I'm not clear why you are updating this version. Is there a new EAP 6 BOM? Can you please explain the need for this change?

**Comment by bkhadige** [comment]
The only version available in http://maven.repository.redhat.com/earlyaccess/ is the 6.2.0.Beta1 so i had to change it to be able to build the sample.

**Comment by sgilda** [comment]
@bkhadige :Only the released versions of the quickstarts, for example `jdf-2.1.8`.Final, are guaranteed to work against the public repositories specified in the settings.xml file. If you are working with the latest master branch, you need to use the contributor-settings.xml file located in the root of the quickstart directory. It includes an additional `jboss-developer-repository` containing artifacts currently under developement. You can find more information in the Contributing Guide here: https://github.com/jboss-developer/jboss-eap-quickstarts/blob/master/CONTRIBUTING.md

I will close this pull request, but please let me know if you have any questions.

**Comment by sgilda** [comment]
@bkhadige : I will also update the Maven instructions to be more clear. See this pull: https://github.com/jboss-developer/jboss-eap-quickstarts/pull/825 :-)

**Pull request closed without merging**
