### PR TITLE
Kitchensink-Cordova for iOS - remove useSplashScreen deprecated setting

### PR DESCRIPTION
**Pull request by tolis-e**
Removed the useSplashScreen deprecated setting

### CODE REVIEW

**Comment by tolis-e** [comment]
@sgilda I think that an explanation would be useful. This line produces a warning in XCode while building the project and is not needed in Cordova versions >= 2.5.0. The only action needed in these newer versions of Cordova is to add or remove the SplashScreen plugin in config.xml. I thought that it would be better to comment this line and not to remove it for backward compatibility reasons.

**Comment by sgilda** [comment]
@tolis-e : Sounds good. Let me know when you've added the comment and you need me to review again.

**Comment by tolis-e** [comment]
@sgilda Comment added

**Comment by VineetReynolds** [comment]
Squashed and merged: https://github.com/jboss-jdf/jboss-as-quickstart/commit/5f50a73aad92e929e5f9133ae9f8c4fb65111e00

**Pull request closed without merging**
