### PR TITLE
use separate databases for cmt and jts

### PR DESCRIPTION
**Pull request by tomjenkinson**

### CODE REVIEW

**Comment by pmuir** [comment]
We've used the convention of angle brackets around something like <QUICKSTART NAME> to indicate the user should replace it. I think we need to do the same here.

**Comment by pmuir** [comment]
Hoisted on our own petard! Yes, angles on!

**Comment by sgilda** [comment]
Pete, I wasn't aware of this convention. 

I removed all of the angle brackets because they are used for links, as in http://localhost:8080/jboss-as-cmt/ and I found it to be confusing. 

In the product documentation, we just use terms like 'JBOSS_HOME' with no brackets and no leading dollar sign for replaceable values.

Are you saying I should go back and add angle brackets to all of the replaceable values like 'JBOSS_HOME' and 'QUICKSTART_HOME'?

**Comment by sgilda** [comment]
I just realized I'm notified of the original pulls, but not getting notified wihen these comments come in. I only found this when I started going through all the pull requests. How can I be sure to see these comments?

**Comment by sgilda** [comment]
I really don't like the angle brackets. If we need to do something, could we make it italicized or bold instead?

**Comment by sgilda** [comment]
I did get notified this time. Strange.
I think that's a good plan. It's best for them to all be consistent for now. If we decide to change them, I'll have to edit all of them again anyway.

**Comment by sgilda** [comment]
Great. I will test it out now. Thanks for all the info too!

**Comment by sgilda** [comment]
Hi Tom,
I think maybe my instructions aren't correct for setting up the PostgreSQL database in the root readme. Do each of these quickstarts require their own database? In the root readme, it looks like I give instructions for creating a jts_quickstart: ./createdb jts-quickstart
It's interesting, because when I list my databases using 'psql -l', I don't even see that database. I only see postgres, test1, test2, template0, and template1. I can't remember what your original instructions were now.

Anyway, I think the missing database is what is causing the error I'm seeing when I deploy 'cmt'. 
-- I started the PostgreSQL database (I did the install and configuration a long time ago).
-- I extracted a new clean copy of jboss-as-7.1.1.Final and copied the module.xml and postgresql-9.1-901.jdbc4.jar to the modules/org/postgres/main directory from a previous server.
-- I started the server using 'bin/standalone.sh -c standalone-full.xml'
-- When I run 'mvn clean package jboss-as:deploy', I get a build failure and see this in the server console:

09:11:18,648 INFO  [org.jboss.as.server](management-handler-thread - 2) JBAS015870: Deploy of deployment "jboss-as-cmt.war" was rolled back with failure message {"JBAS014771: Services with missing/unavailable dependencies" => ["jboss.data-source.jboss/datasources/CMTQuickstartDSjboss.jdbc-driver.postgresqlMissing[jboss.data-source.jboss/datasources/CMTQuickstartDSjboss.jdbc-driver.postgresql]"]}
09:11:18,651 INFO  [org.jboss.as.controller](management-handler-thread - 2) JBAS014774: Service status report
JBAS014775:    New missing/unsatisfied dependencies:
      service jboss.jdbc-driver.postgresql (missing) dependents: [service jboss.data-source.jboss/datasources/CMTQuickstartDS] 

Please let me know what I need to create for 'cmt' and 'jts' and I'll modify the instructions.

**Comment by sgilda** [comment]
Right. I will need to modify the instructions for that. I'm still seeing the same problem. 
I created the cmt-quickstart-database: ./createdb cmt-quickstart-database;
I granted privileges to 'sa': grant all privileges on database "cmt-quickstart-database" to sa;
When I list the databases, it looks OK to me:

bin $ psql -l
                                        List of databases
          Name           |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges  
-------------------------+----------+----------+------------+------------+-----------------------
 cmt-quickstart-database | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =Tc/postgres         +
                         |          |          |            |            | postgres=CTc/postgres+
                         |          |          |            |            | sa=CTc/postgres
 postgres                | postgres | UTF8     | en_US.utf8 | en_US.utf8 | 

But the deploy still fails with: 
9:58:37,895 INFO  [org.jboss.as.server](management-handler-thread - 2) JBAS015870: Deploy of deployment "jboss-as-cmt.war" was rolled back with failure message {"JBAS014771: Services with missing/unavailable dependencies" => ["jboss.data-source.jboss/datasources/CMTQuickstartDSjboss.jdbc-driver.postgresqlMissing[jboss.data-source.jboss/datasources/CMTQuickstartDSjboss.jdbc-driver.postgresql]"]}

Am I forgetting something else?

**Comment by sgilda** [comment]
You hit on it! I missed step 1 above. Sorry about it!

**Comment by sgilda** [comment]
Works great. Squashed commits, merged, and closed.

**Comment by pmuir** [comment]
Re angle brackets - I didn't realise Sande had removed them all, so I'm out of date! Ignore my comments on this!

**Pull request closed without merging**
