### PR TITLE
Updates for EAP 6.3.0

### PR DESCRIPTION
**Pull request by dosoudil**
Fundamental pom updates for building quickstarts for EAP 6.3.0 (DR0).

### CODE REVIEW

**Comment by rafabene** [comment]
Note: We need to rename master to 6.3.x-develop before apply this PR

**Comment by sgilda** [comment]
@rafabene : do we want to rename master or create a new 6.3.x. These changes are for the product builds, so we still need a branch for development.

**Comment by rafabene** [comment]
It's better that we rename master. I'll do that. Hang on

**Comment by rafabene** [comment]
Branch 6.3.x created from master

**Comment by pgier** [comment]
This has been merged to the 6.3.x branch.

**Pull request closed without merging**
