### PR TITLE
add example of TransactionAttributeType.REQUIRES_NEW (attempt 2)

### PR DESCRIPTION
**Pull request by gkephorus**
An example to show how a method marked with TransactionAttributeType.REQUIRES_NEW does commit a record while the former transaction can still fail.
One can see this by running the application and adding a 'customer' whose name contains non letters (e.g. John1). This will result in a LogMessage-record in the database but not a customer-record neither will a JMS-message be delivered.

Signed-off-by: Gerke - Ephorus gerke.ephorus@gmail.com

### CODE REVIEW

**Comment by sgilda** [comment]
@gkephorus : Would you mind squashing the commits? It makes it easier to review the changes. Thanks!

**Comment by gkephorus** [comment]
I think I've made it ;-). Squashing the commits and even the 'force push' of the commits.
Thanks for reviewing already. (and thanks for leading me into the advanced features of git. I get to love it even more. Though I can image that other developers get discouraged by the administration needed to get a contribution accepted... ;-) though I also understand the need for this administration. I keep telling my developer off for not sticking to formatting-conversions and commit-conventions.)

**Comment by sgilda** [comment]
@gkephorus : Thanks! Sorry it's so painful, but we need the quickstarts to be consistent and easy for developers to follow. We also want to make sure they follow development guidelines and recommded practices.

I have a few more comments, although I am more than happy to make the changes before we merge.
1. There are no instructions to run your new Arquillian tests. Examples can be found in the `Run the Arquillian Tests` of the `bean-validation/README.md` file.
2. When you run the Arquillian tests, you get this warning: `[WARNING] The requested profile "arq-jbossas-remote" could not be activated because it does not exist.`. This is because the pom.xml file is missing the Arquillian profiles. The `<profiles>` can be copied from the `bean-validation/pom.xml` file.

I have also asked for a separate code review from the quickstart owner.

**Comment by gkephorus** [comment]
@sgilda: I'm not aware of adding tests that need Arquillian and the test I did add were there for my own good. They were the first tests on the cmt-module. I'll have a look at what I should do with respect to Arquillian. Maybe I can turn Arquillian off for this module to avoid the warning?
I did forget to allow spaces in the name but adding that to the commit should be peanuts now I know the dril for rewriting (git-)hisory ;-) and should be available soon.

sgilda notifications@github.com wrote:

> @gkephorus : Thanks! Sorry it's so painful, but we need the quickstarts
> to be consistent and easy for developers to follow. We also want to
> make sure they follow development guidelines and recommded practices.
> 
> I have a few more comments, although I am more than happy to make the
> changes before we merge.
> 1. There are no instructions to run your new Arquillian tests. Examples
>    can be found in the `Run the Arquillian Tests` of the
>    `bean-validation/README.md` file.
> 2. When you run the Arquillian tests, you get this warning: `[WARNING]
>    The requested profile "arq-jbossas-remote" could not be activated
>    because it does not exist.`. This is because the pom.xml file is
>    missing the Arquillian profiles. The `<profiles>` can be copied from
>    the `bean-validation/pom.xml` file.
> 
> I have also asked for a separate code review from the quickstart owner.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jboss-developer/jboss-eap-quickstarts/pull/831#issuecomment-31841178

## 

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by sgilda** [comment]
I ran the QS tools checker against this quickstart and it reports numerous Java formatting violations. 

You can find instructions for the code formatter in the Contributing guide here: https://github.com/jboss-developer/jboss-eap-quickstarts/blob/master/CONTRIBUTING.md#general-guidelines

You can find information on how to run the QS Tools plugin to verify your changes here: http://www.jboss.org/jdf/quickstarts/qstools/. 

This tool has recently been enhanced to fix violations. The latest instructions can be found here: https://github.com/jboss-developer/maven-qstools-plugin

**Comment by sgilda** [comment]
@gkephorus : The tests are a nice addition and I am happy to update the instructions and pom.xml file. :-)

**Comment by gkephorus** [comment]
@sgilda: I'd be happy to update the instructions and pm myself if it's just boilerplate/copy-past in the location you already specified. Or is it easy to get your changes in this same commit?

sgilda notifications@github.com wrote:

> @gkephorus : The tests are a nice addition and I am happy to update the
> instructions and pom.xml file. :-)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jboss-developer/jboss-eap-quickstarts/pull/831#issuecomment-31844754

## 

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by gkephorus** [comment]
@sgilda: I'll run the QS tools as soon as I have some time again. It should be simple, I presume. As long as it only hits my new code. Thanks.

sgilda notifications@github.com wrote:

> I ran the QS tools checker against this quickstart and it reports
> numerous Java formatting violations. 
> 
> You can find instructions for the code formatter in the Contributing
> guide here:
> https://github.com/jboss-developer/jboss-eap-quickstarts/blob/master/CONTRIBUTING.md#general-guidelines
> 
> You can find information on how to run the QS Tools plugin to verify
> your changes here: http://www.jboss.org/jdf/quickstarts/qstools/. 
> 
> This tool has recently been enhanced to fix violations. The latest
> instructions can be found here:
> https://github.com/jboss-developer/maven-qstools-plugin
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jboss-developer/jboss-eap-quickstarts/pull/831#issuecomment-31844444

## 

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by sgilda** [comment]
@gkephorus : 

It's easy for me to update the README and POM files before I do the merge.

IMPORTANT: Be sure to navigate to your `cmt` quickstart directory before you run the QS Tools plug-in. That way you will be sure to only update only that code!

**Comment by gkephorus** [comment]
@tomjenkinson : thanks for the review.

Indeed, the name-checking is only for explaining the fact that REQUIRES_NEW will start a new transaction and commit, so cause a LogMessage-record to be stored eventhough all the other things in the main-transaction are rolled-back. And, yes, in real life this should be done before trying to store everything. I'm open to suggestions on what else to use as demonstration of this REQUIRES_NEW.

On the general EjbException: maybe I should have created a new Exception, but this would involve more code and would not help the demonstration.

**Comment by sgilda** [comment]
@gkephorus : When you fix the issues reported by the QS Tool, would you mind adding some comments to the code?

**Comment by sgilda** [comment]
@tomjenkinson : Thanks for the code review!

**Comment by gkephorus** [comment]
@sgilda : I updated the commit after running the QSTools fixer. I split it into two commits to show that the second commit is only fixes to existing code: year-2014 & tiny formatting-issues and some order of elements in pom.

Hope it's ready for acceptance now ;-)

PS. I should still add comments. Hope to do so soon.

**Comment by sgilda** [comment]
@gkephorus : As soon as you add the comments, I'll merge this pull.

**Comment by sgilda** [comment]
Merged.

**Comment by gkephorus** [comment]
Thanks for the merge.

**Pull request closed without merging**
