### PR TITLE
Updated quickstart to work with new JNDI implementation and security in ...

### PR DESCRIPTION
**Pull request by jbertram**
...AS 7.1.0.Final

### CODE REVIEW

**Comment by sgilda** [comment]
Hi Justin,
Apparently there is some additional setup required for this quickstart? I'm getting this error:

SEVERE: Unable to validate user: myUser
javax.jms.JMSSecurityException: Unable to validate user: myUser

I found this in the pom.xml file:



```
              <systemProperty>
                 <key>username</key>
                 <value>myUser</value>
              </systemProperty>
              <systemProperty>
                 <key>password</key>
                 <value>myPass</value>
```

I added a myUser/myPass User with a guest role to the application realm, but now I am seeing this error:

SEVERE: User: myUser doesn't have permission='CONSUME' on address jms.queue.testQueue
javax.jms.JMSSecurityException: User: myUser doesn't have permission='CONSUME' on address jms.queue.testQueue

The README instructions need to be updated. I'll email you a copy so you can verify that I set it up correctly.

Any idea what I did wrong?

Do we have to use the bin/add-user.sh script to add a user? To which 
Can you modify the README file

**Comment by jbertram** [comment]
I did update the README.md.  It's part of the commit.  Did you see those changes?

**Comment by jbertram** [comment]
Make sure your user is in the "guest" role as stated in the README.md and in the pom.xml.

**Comment by sgilda** [comment]
I was looking at the wrong version of the README. Sorry! My bad. :-)

**Comment by sgilda** [comment]
I'm pretty sure I did.

**Comment by sgilda** [comment]
In fact, I copied and pasted from the command line for the readme. Maybe there was an extra space somewhere.

Is there a way to remove a user so I can add them back?

**Comment by jbertram** [comment]
Are you using AS 7.1.0.Final or the latest snapshot of 7.1.1?  AS 7.1.0.Final has a bug that may prevent add-user.sh from working properly.  I mentioned this in my email to you earlier today in a reply to the thread you forwarded to me.  I recommend you use 7.1.1 because of this.

**Comment by sgilda** [comment]
I'm using AS 7.1.0.Final. That must be it. Thanks!

**Comment by jbertram** [comment]
Once you try with 7.1.1 let me know if you have any issues.  Thanks!

Also, I think the walk-through you added for using add-user.sh is worth keeping.

**Comment by pmuir** [comment]
I wonder if it's worth removing the whole netty/jndi option thing as part of this? I assume JNDI is recommended, and as this is a quickstart, it should show recommended approaches not all. I think this could simplify the code considerably.

Sande, we should add the stuff about adding users to the root readme as a number of quickstarts will need this.

**Comment by sgilda** [comment]
It does make sense. It also would be nice if all the quickstarts were 
modified to use the same user. Maybe quickstartUser/quickstartPassword 
or something like that.

**Comment by pmuir** [comment]
Good idea.

**Comment by sgilda** [comment]
I can't download it at the moment because the web site is down for 
maintenance. I assume it's available here: 
http://www.jboss.org/jbossas/downloads/

I'll try again in an hour.

**Comment by sgilda** [comment]
Hi Justin,

It does work great with JBoss 7.1.1. Thanks!

I am going through the README as a new user and I think the instructions need to be more specific. For example, it states:

```
    * `username`

        This username is used for both the JMS connection and the JNDI look-up (if necessary).  Use the bin/add-user.sh script on the server to add this user to the "guest" role and the "ApplicationRealm".

         Default: `defaultUser`
```

When I read that as a new user, I assume I create a user "defaultUser/defaultPassword" or "username/password". Nowhere does it indicate that the username you need to create is "myUser/myPass".

It's not until you compile that you know the username you need to create:

```
   SEVERE: Unable to validate user: myUser
   javax.jms.JMSSecurityException: Unable to validate user: myUser
```

Also, why does it show BUILD SUCCESS?

```
    Caused by: HornetQException[errorCode=105 message=Unable to validate user: myUser]
        ... 13 more
     [INFO] ------------------------------------------------------------------------ 
     [INFO] BUILD SUCCESS
     [INFO] ------------------------------------------------------------------------
```

Would you mind making the following changes?

--  Change the username/password from myUser/myPass to quickstartUser/quickstartPassword in anticipation of trying to have one user for all the quickstart.
--  Modify the README as follows:
---- Move the instructions to start the server before the maven compile instructions. I'm afraid some users may follow the steps and not realize until the end that the server must be started
---- Add specific details about the user to create. You might want to point out the properities in the pom.xml file and how they impact this. Eventually I'll pull the add-user instructions to the root readme, but the pom.xml information needs to be here.
---- Add information about what you should expect to see when you  successfully run the quickstart. For example:
Mar 14, 2012 8:21:47 AM org.jboss.as.quickstarts.jms.JMSClientUtil getConnectionFactory
INFO: Attempting to acquire ConnectionFactory "RemoteConnectionFactory" with a connection type of: netty
Mar 14, 2012 8:21:47 AM org.jboss.as.quickstarts.jms.JMSClientUtil getConnectionFactory
INFO: Creating Netty Based ConnectionFactory.
Mar 14, 2012 8:21:47 AM org.jboss.as.quickstarts.jms.JMSClientUtil getDestination
INFO: Attempting to acquire Destination with a connection type of: netty
Mar 14, 2012 8:21:47 AM org.jboss.as.quickstarts.jms.JMSClientUtil getDestination
INFO: HornetQ Destination testQueue
Mar 14, 2012 8:21:48 AM org.jboss.as.quickstarts.jms.HelloWorldJMSClient main
INFO: Sending 1 messages with content: Hello, World!
Mar 14, 2012 8:21:48 AM org.jboss.as.quickstarts.jms.HelloWorldJMSClient main
INFO: Received message with content Hello, World!

Thanks for getting this quickstart working again!
Sande

**Comment by jbertram** [comment]
Yes, I can do that.  Do you want me to make this a JNDI only quick-start?  If we want to show the HornetQ "core" API (i.e. Netty) use-case, we could have a different quick-start for that.

**Comment by pmuir** [comment]
+1

**Pull request closed without merging**
