### PR TITLE
JavaScript changes to fix issues with IE and older versions of Firefox

### PR DESCRIPTION
**Pull request by kborchers**
Comment out console.log() statements to prevent JavaScript errors in IE and older versions of Firefox. Update updateMemberTable() to use $.ajax instead of $.get in order to pass the 'cache: false' option to fix update issues in IE. Removed the unnecessary errStatus var.

### CODE REVIEW

**Comment by pmuir** [comment]
Emailed Jay to ask him to review this.

**Comment by balunasj** [comment]
The changes look good at first glance - I'll verify today!

**Comment by kborchers** [comment]
Thanks Jay. I decided to just comment out the console.log() statements. Even though it would be "cleaner" to actually remove them, I thought it would be helpful, especially for those newer to JS development, to still show how and where debugging statements like that could be placed.

**Comment by balunasj** [comment]
The funny thing is I was debating the same thing, and came to the same conclusion :-)

**Comment by sgilda** [comment]
Jay, did you get a chance to review this one? is it good to go?

**Comment by balunasj** [comment]
Unfortunately not yet - I plan on getting to this later today.  Is that timing ok, or do you need it sooner?

**Comment by sgilda** [comment]
No. I was just curious. ;-)

One thing I noticed is that this example is still using the table 
"Member". It probably needs to be changed to a unique name to avoid 
conficts with other examples.

**Comment by balunasj** [comment]
Yup - I'm going to be updating the table names for the quickstart and the archetype this afternoon too

**Comment by sgilda** [comment]
Thanks!

**Comment by balunasj** [comment]
Sorry for the delay - I've been fighting git - this commit looks good!!

**Comment by pmuir** [comment]
Merged

**Pull request closed without merging**
