### PR TITLE
Add automated datasource deployments for mysql and postgresql

### PR DESCRIPTION
**Pull request by stuartwdouglas**
I have added a feature to the jboss-as maven plugin that allows it to automatically deploy datasources. I think it would be a good idea to have a sample of this functionality in the quickstarts, to enable people to get started with a custom datasource quickly on AS7.

This pull request has an example pom that can automatically add mysql and postgresql datasources (and xa-datasources).

### CODE REVIEW

**Comment by pmuir** [comment]
Rather than add this as a new quickstart, I think it would make more sense to add this to an existing quickstart, probably the login quickstart, as profiles, and optional features.

We would need more docs for this too.

WDYT?

**Comment by stuartwdouglas** [comment]
I don't know about it being part of another example, as there is not really any way to just run it without also installing the project (I don't think there is anyway, unless there is some  maven feature I don't know about).

I envisaged people using this in the real world as a sub project that just installs the datasource, rather than having it integrated into their main build pom. With that said though if you think it is better in the login example I am happy to go with that. 

I agree it needs more docs, I will try and get onto that this week. It would also be good to get oracle and mssql datasources, but I don't have them availible to test.

**Comment by pmuir** [comment]
How about adding it as a sub module of the login quickstart then?

**Comment by stuartwdouglas** [comment]
Ok, I will do that.

**Comment by pmuir** [comment]
Stuart, did you do this?

**Comment by stuartwdouglas** [comment]
No, and it will need a bit of work due to AS7 management API changes. I will revisit after 7.1 is out

**Comment by pmuir** [comment]
I'm going to close this pull for now :-)

**Pull request closed without merging**
