### PR TITLE
Add jboss-cli commands in addition to the manual edits of the server config file

### PR DESCRIPTION
**Pull request by sgilda**

### CODE REVIEW

**Comment by sgilda** [comment]
I added commands for everything but configuration of OpenShift deployments.

**Comment by pmuir** [comment]
@sgilda do you want us to get someone from the AS team to review this one?

**Comment by sgilda** [comment]
Sure. I tested that the commands created the correct XML (matched the XML snippets in the README instructions), but it wouldn't hurt to review them.

**Comment by aloubyansky** [comment]
CLI parts look good.Thanks.

**Comment by sgilda** [comment]
Merged.

**Pull request closed without merging**
