### PR TITLE
Updated README.md to remove default description.

### PR DESCRIPTION
**Pull request by StevenBoscarine**
I updated the default text on README.md.  Is this along the lines of what you had in mind?

### CODE REVIEW

**Comment by sgilda** [comment]
I entered the comment in the wrong location. :-)
This looks fine. Who requested this?

**Comment by StevenBoscarine** [comment]
No one requested it.  I am a volunteer just getting started with the project and  happened to notice it when Pete asked for a code review this afternoon.

**Comment by StevenBoscarine** [comment]
I apologize for closing and reopening.  It was accidental.  I am still learning my way around github.

**Comment by pmuir** [comment]
I'm going to hold this open, as we would need to update the archetype as well. Steven, do you want to look at this?

**Comment by sgilda** [comment]
There are 2 other kitchensink pulls. Should they be merged in the following order?

https://github.com/jbossas/quickstart/pull/125 (kitchensink: efactored the database manipulation into a service layer to facilitate testing)
https://github.com/jbossas/quickstart/pull/126 (Kitchensink upgrade)
https://github.com/jbossas/quickstart/pull/127 (kitchensink README)

**Comment by pmuir** [comment]
They can be merged as they are ready. I think only 125 is ready.

**Comment by StevenBoscarine** [comment]
I assumed it was the result of the archetype but don't understand why we'd need to update the archetype as well. 
Are you generating the archetype directly from this project?  If so, I'll cancel my pull request.

I was operating under the assumption you created it from the archetype and wanted to update the README.md to reflect the kitchensink project itself, but haven't gotten around to it yet.

I think the text is great for an archetype, but for the kitchensink example in quickstarts, I assumed you didn't want to say: "This is your project!"

**Comment by sgilda** [comment]
Pete. I'm not sure where this one stands. There's an outstanding pull for the archetype and quickstart README files at the moment.

**Comment by pmuir** [comment]
I'm going to close, as I do really want to keep the archetype and kitchensink in sync as much as possible!

**Pull request closed without merging**
