### PR TITLE
Convert to a single-page app

### PR DESCRIPTION
**Pull request by kborchers**
Use media queries instead of UA detection, conditionally load remote libraries for improved caching and performance, and upgrade to latest jQuery Mobile.

### CODE REVIEW

**Comment by balunasj** [comment]
This looks good, and was a needed change, but there are a couple of things:
- We had the non-minified version of jquery in there because Eclipse displays an error for the minified version.  We wanted to make sure the user experience out of the box had no errors.  Perhaps pull the minified version of CDN, and fall back to local full version?
- There are areas of descriptive text that we had in the desktop version, but not the mobile version.  This text is now there, and throws off the mobile layout.  I think it could be removed with a simple class.
- Some comments in index.html about the moderizer calls would make it clearer for new users.

**Comment by kborchers** [comment]
Thanks for the feedback @balunasj. I will try to get to these this weekend.

**Comment by kborchers** [comment]
I have made all of the changes but have run into an issue. I tried including the full, un-minified version of Modernizr to avoid Eclipse errors. Unfortunately, the development version of Modernizr does not include the yepnope.js library. My question is would you prefer I include the full versions of Modernizr and yepnope separately and adjust the code accordingly, or leave the minified version of Modernizr which can be built to include yepnope and explain the Eclipse error with comments? I see advantages and disadvantages to both methods so really just looking for the preference of the team.

**Comment by balunasj** [comment]
It sucks that eclipse has these errors - I'll ask Max ( tools lead ) to get any ETA, but I suspect these errors will be around a while.  Iirc they have been there a long time already.

So it comes down to having our examples show recommended practices ( minified JS, etc.. ), and having the examples perform well, or having no errors in the eclipse project navigator.

Personally I think we should go with the recommended practices, but I'll have to check with Max, and PM first.  I'll get back to you today if possible.

**Comment by balunasj** [comment]
Just finished discussing this, and here is where we stand.  The eclipse issues are in eclipse core - not part of JBoss Tools.  This means we can't predict when this would be fixed - its been a problem for a long time.  We also really don't want to show errors in the tooling.

So this means we need to include the non-minimized versions, and we'll need to package the yepnope.js library as well.

However the good news is that the tooling team is working on integrating [wro4j](http://code.google.com/p/wro4j/) not only into JBoss tools, but also as a standard maven plugin here - https://github.com/fbricon/m2e-wro4j#readme

So, we'll have to look into using that approach, but that will be a separate task.  I'll create a jira for that, and for now please just update with the non-minimized versions.

**Comment by kborchers** [comment]
I believe I have addressed all of your points above. Please let me know if you find any other changes you would like made.

**Comment by balunasj** [comment]
Thanks Kris I should be able to review and merge this afternoon!

**Comment by kborchers** [comment]
@balunasj Working on a different project, I have determined that the media queries I am using to detect mobile are not comprehensive enough. I will be updating that later if you want to hold off on merging until then. Otherwise, I can just send another PR with the change.

**Comment by balunasj** [comment]
I can hold off, it is a related change.

**Comment by kborchers** [comment]
OK, this should do it. The only possible remaining issue is that I don't have an iPhone to test with which may still give us problems. There is another media query I could add to detect iPhone 4 if it is not working properly.

**Comment by balunasj** [comment]
I'll test that out when I review this.  Thanks again for the updates!

**Comment by balunasj** [comment]
Couple of minor things, but otherwise looks good:
- index.html 
  - second meta tag not closed
  - We're using spaces instead of tabs
    - Index.html was the only one using tabs
    - We're looking to better document that soon
- The motorola zoom shows desktop, while the iPad shows mobile 
  - xoom resolution: 1280x800
  - ipad 1024x768
  - note it looks fine as desktop version on xoom.
  - you might want to try it on ipad to see how it looks in desktop.
    - I'm fine with it showing the desktop version

**Comment by kborchers** [comment]
I am slapping my hand with a ruler for not closing a tag.

I will convert the tabs to spaces.

In my opinion and from people I have asked, it is usually preferred to be shown the desktop site on a tablet. Since you are fine with it, I will only show the mobile site to smaller devices. Can anyone confirm that an iPhone 4 shows you the mobile site? If only I had an arsenal of mobile devices to test with since I really don't trust emulators.

I should get to all of this tonight.

**Comment by balunasj** [comment]
I only have an iPhone 3g - gasp - I'll have Wesley take a look at this when you update.

**Comment by kborchers** [comment]
I have made those updates. Before merging I would like to know if the iPhone 4 gets the mobile version. I have a feeling it may need an extra check but I didn't want to add it unless it's necessary.

**Comment by balunasj** [comment]
Hi Kris,

Wesley tested out your changes today, and it appears that on his Android 2.3.3 phone your updates did not show the mobile versions.  One his iPhone 4 it did show the mobile site.

I'll try to check this out myself tomorrow on my Android 2.3.6, and hopefully we can get this PR merged :-)

**Comment by kborchers** [comment]
My Android 2.3.4 device works so that makes it even more fun. I'll try bumping the dimensions in that media query a little and then maybe Wesley can check it again. Oh the joys of mobile browsers. That is why jQuery Mobile's test area looks like this and there are still devices/OS versions they don't have covered:

**Comment by kborchers** [comment]
OK, I pinged Wesley on Skype to get some info about the device he is using. I am unable to get that media-query to fail here. I don't have a 2.3.3 device to test with but I think it has to be something else because it works properly on my 2.3.4 phone and my wife's 2.2 phone.

**Comment by balunasj** [comment]
Ok then, lets not spend anymore time on this for now then.  I'd like to get your changes integrated, so we can work on syncing your updates into the [companion maven archetype](https://github.com/jbossas/archetypes/tree/master/jboss-html5-mobile-archetype).

If I can't get to this today, I'll see someone else can.

**Comment by wesleyhales** [comment]
Hey Kris, Here's the test I did yesterday...
Android 2.3.3

**Comment by kborchers** [comment]
Thanks @wesleyhales! What device is that? It looks just like my T-Mobile HTC Sensation. Also, is it possible that you have some zoom level set that would mess up the min and max device-width's the phone would report?

**Comment by wesleyhales** [comment]
it's the EVO 4G. Since this is a test-only phone through JBoss, all the settings are default. I know, this is weird to me as well. I may try to see what is going on and test further next week.

**Comment by kborchers** [comment]
I was afraid you would say that. Thanks for the testing. I'll try to ask around and see if anyone I know has a similar device so that I can see it fail. If you do get a chance to test, can you try creating a simple page that just writes out window.screen.width with JavaScript? That might lead us in the right direction on this media query. Thanks again!

**Comment by balunasj** [comment]
Thanks guys - Wesley can you create a jira with this info so we don't lose it.

I want to get this merged asap - today/weekend so we can sync the archetype source.

**Comment by wesleyhales** [comment]
@kborchers "4.3” 480 x 800 WVGA OLED Touch screen" http://shopamerica.htc.com/cell-phones/productdetail.htm?prId=37149

**Comment by kborchers** [comment]
Ooohhhh, ok 480 x 800! I think that should work and still show full site on the iPad. I will try to change that shortly. Thanks @wesleyhales!

**Comment by kborchers** [comment]
I would appreciate testing on as many devices as possible. This works on my Android 2.3.4 device and my iPad on iOS 5.

**Comment by balunasj** [comment]
I have merged this pull requests, and it should be all set.

**Comment by sgilda** [comment]
Hi Jay, 
In addition to renaming the readme.md and readme.html files to README.md and README.html, could you update a few versions in the pom.xml file? 
- The versions for the artifactIds with the pattern 'jboss-as-arquillian*' need to be updated to 7.1.0.CR1b.
- The versions for groupIds with the pattern 'org.jboss.arquillian.\* ﻿' need to be updated to 1.0.0.CR7. 
- The jboss-as-maven-plugin version needs to be updated to 7.1.0.CR1.
  All the version numbers can be found here: https://docs.jboss.org/author/display/AS71/Maven+POM+Versions+Checklist
  Once these are updated, this is ready to go if Pete has no changes. It looks great!

**Comment by balunasj** [comment]
Sure thing - we can get these updated.  Thanks for the link to the version checklist!

**Comment by sgilda** [comment]
Is this pull request still valid? It looks like Pete processed a pull yesterday that renamed this quickstart to kitchensink-html5-mobile and that superseded this one. Please let me know if this one should be closed.
Thanks!

**Comment by balunasj** [comment]
I believe I already closed this one back on January 21st.

**Pull request closed without merging**
