### PR TITLE
Added remove-configuration.cli to revert install-domain.cli changes back to default

### PR DESCRIPTION
**Pull request by Dantheman720**
Will make changes to README as well, but wanted to get comments on this.

### CODE REVIEW

**Comment by sgilda** [comment]
@Dantheman720 : Thanks! I'll look at this later today.

**Comment by sgilda** [comment]
After running the script and comparing the configuration files to the backed up versions, I see one minor difference in the host.xml file: 

 The "ApplicationtRealm" security-realm is missing this line: 

```
    `<local default-user="$local" allowed-users="*" />`
```

**Comment by sgilda** [comment]
I see quite a  few differences in the domain.xml file (first line is after removal script, second line is original file):

For example, in the Default profile and ha profile, under the  <subsystem xmlns="urn:jboss:domain:ejb3:1.4"> subsystem, 
                <default-missing-method-permissions-deny-access value="false"/>
previously it was 
                <default-missing-method-permissions-deny-access value="true"/>

There are  entries like this in the restored file that aren't in the original:

```
    <distributed-cache name="dist" l1-lifespan="0" mode="ASYNC" batching="true">
                    <eviction strategy="LRU" max-entries="10000"/>
                    <file-store/>
                </distributed-cache>
```

Have you done a diff on the domain.xml with the backed up version?

I need to look at this closer to see if the differences are important or not.

**Comment by sgilda** [comment]
Great job. I think with a few minor changes, this is very close!

**Comment by sgilda** [comment]
Thanks @Dantheman720 ! Excellent job.
Merged!

**Comment by Dantheman720** [comment]
Thanks!

**Pull request closed without merging**
