### PR TITLE
Simplify installation of HATimerService using a ServiceActivator.

### PR DESCRIPTION
**Pull request by pferraro**

### CODE REVIEW

**Comment by pmuir** [comment]
@pferraro what release did you test this on? With your changes it breaks on EAP 6.0.0

**Comment by pferraro** [comment]
The changes were tested against both AS7 master and the HEAD of the 7.1 branch.

**Comment by pmuir** [comment]
Could you retest against the latest released EAP and AS 7 as those are our targets. Otherwise let's revisit when there are releases for which this change will work.

**Comment by sgilda** [comment]
This brings up the question: do the EAP 6.1 quickstarts need to be backward compatible with the EAP 6.0 release?

**Comment by pmuir** [comment]
@sgilda  you mean with the EAP 6.0 release?

**Comment by sgilda** [comment]
Ah yes! Typo. I modified my comment. :-)

**Comment by pferraro** [comment]
@pmuir I just tested this successfully against both the latest public AS7 release (7.1.2.Final), as well as EAP6 - I don't see any breakage.  Can you post specifics?

**Comment by sgilda** [comment]
@pferraro : I will try this out too.

**Comment by pferraro** [comment]
@sgilda Thanks.  Theoretically, I don't see any reason why the above changes would break anything.  All I'm changing is the mechanism by which the singleton service is installed.  ServiceActivator has been around since well before EAP6.

**Comment by sgilda** [comment]
@pferraro : I don't recall, do I need to make a copy of the server directory before I start the second server? I'm not seeing anything in the server 2 log when I run: mvn jboss-as:deploy -Ddeploy.hostname=localhost -Ddeploy.port=10099

**Comment by sgilda** [comment]
@pferraro: I started with a fresh JBoss AS 7.1.1 Final, and made a copy of the directory for the 2nd server. I started the servers using the commands in the README file (I copied and pasted them).
-  I run `mvn clean install jboss-as:deploy` and see messages like the following in the server1 console:  (EJB default - 1) HASingletonTimer: Info=HASingleton timer @nodeOne Tue Dec 18 
- I run `mvn jboss-as:deploy -Ddeploy.hostname=localhost -Ddeploy.port=10099`. I get "BUILD SUCCESS", but I see nothing in the server 2 log.  These are the last lines I see in the server 2 log:

14:23:43,729 INFO  [org.jboss.as.remoting](MSC service thread 1-7) JBAS017100: Listening on /127.0.0.1:10099
14:23:43,879 INFO  [org.jboss.as.remoting](MSC service thread 1-5) JBAS017100: Listening on /127.0.0.1:4547
14:23:44,136 INFO  [org.jboss.as](Controller Boot Thread) JBAS015951: Admin console listening on http://127.0.0.1:10090
14:23:44,137 INFO  [org.jboss.as](Controller Boot Thread) JBAS015874: JBoss AS 7.1.1.Final "Brontes" started in 8444ms - Started 135 of 260 services (124 services are passive or on-demand)

Any idea what I'm doing wrong?

**Comment by pferraro** [comment]
If the jboss-as maven plugin isn't deploying the artifact correctly now, then it wasn't before either.  Nothing I did changed how the artifact is deployed.
When I tested this, I deployed the jar by dropping it in the deployments directory on each server.

**Comment by sgilda** [comment]
I know I tested this and it worked at one time. Let me see if I can figure out what is different.

**Comment by sgilda** [comment]
I can see comments here: https://github.com/jboss-jdf/jboss-as-quickstart/pull/283. At some point it did work based on this comment: https://github.com/jboss-jdf/jboss-as-quickstart/pull/283#issuecomment-6466858

I'll look into this a little more.

**Comment by pmuir** [comment]
I've merged this, as I did get it to work. However there is definitely a problem here. The only way it reliably works, before, or after, the changes @pferraro made, is to restart both servers having done a redeploy. I'll file an issue and see if @wfink or @pferraro can take a look.

**Pull request closed without merging**
