### PR TITLE
Add info to run add-user script plus replaced tables

### PR DESCRIPTION
**Pull request by sgilda**
Replaced all tables but the one describing the quickstarts with lists.

### CODE REVIEW

**Comment by sgilda** [comment]
Pete, 
Do you want to review this, or should I just push this one upstream?
Thanks, Sande

**Comment by sgilda** [comment]
Squashed to 1 commit.

**Comment by sgilda** [comment]
Discovered the  replaceable value <custom-options> wasn't rendering. Changed it to CUSTOM_OPTIONS. Squashed the commits.

I believe this is ready to go now. :-)

**Comment by pmuir** [comment]
Merged with a reformat of the source to consistently use spaces and new lines.

**Pull request closed without merging**
