### PR TITLE
see comments

### PR DESCRIPTION
**Pull request by anilsaldhana**
https://issues.jboss.org/browse/JDF-355
https://issues.jboss.org/browse/JDF-353
https://issues.jboss.org/browse/JDF-352

### CODE REVIEW

**Comment by pmuir** [comment]
@anilsaldhana could you create a branch for each issue, and send a pull request for each branch? This is much easier for reviewers to work through. Also, could you squash your commits so you only have one per issue?

**Comment by anilsaldhana** [comment]
Agreed.

**Comment by sgilda** [comment]
@anilsaldhana : I have a couple of quick comments.
- Under _What is it?_, would it be possible to give a few more details about each quickstart and maybe talk a little about the most interesting classes? Check out the servlet-security, picketlink-deltaspike-authorization, picketlink-authentication-idm-multi-tenancy, or other picketlink quickstarts to see what I mean.
- Would you mind addiing  some comments to the classes?
- We need to come up with the jboss-cli commands to configure the server and also create scripts. See the `servlet-scurity` quickstart for an example of what I mean. We have a standard note to tell them to back things up before they begin, then give them instructions on how to configure the server using the script, jboss-cli commands, and manually. We give them info to remove the configuration. In these, they will also need instructions to edit the configuration script to plug in the values they obtain. I can help with the instructions and cli commands.

**Comment by rafabene** [comment]
@pedroigor Are these changes part of PicketLink quickstarts?

If so, can I close those JIRAS ?

Thanks

**Comment by sgilda** [comment]
This pull was closed June 24, 2013. Are there open JIRAs related to this?

**Pull request closed without merging**
