### PR TITLE
Update Maven README instructions and cheat sheet CONTRIBUTING guide.

### PR DESCRIPTION
**Pull request by sgilda**

### CODE REVIEW

**Comment by sgilda** [comment]
Hold off on this. I forgot to add the settings.xml file!

**Comment by sgilda** [comment]
I believe this is ready to go. I tested the settings file and it builds successfully.

**Comment by rafabene** [comment]
It looks good for me. I believe that we don't need instructions to setup ER maven repository, right ?

**Comment by sgilda** [comment]
@rafabene : Sorry. I'm not sure what you mean by 'setup ER maven repository'???

**Comment by rafabene** [comment]
I mean those "Engineering Releases" that will use jboss-developer.github.io as repository. Only for developers

**Comment by sgilda** [comment]
@rbenevides: I'm not sure. I thought @pmuir said to use the early access and tech preview repositories listed in the settings.xml file. It builds fine using:
- http://maven.repository.redhat.com/techpreview/all
- http://maven.repository.redhat.com/earlyaccess/all/

**Comment by sgilda** [comment]
@pmuir: Can you verify that the settings.xml file is pointing to the correct repositories? Or should it point to jboss-developer.github.io instead? I may be confused here! :-)

**Comment by rafabene** [comment]
developer.github.io is just to be used by the Engineering only. I thought about having the instructions about developer.github.io but that should cause some confusion to the users.

**Comment by sgilda** [comment]
I think this is ready for review again.

**Comment by rafabene** [comment]
Ready to go! Do you want me to merge and start the split ?

**Pull request merged**
