### PR TITLE
Jbeap 3456

### PR DESCRIPTION
**Pull request by pgier**
Upgrade EAP BOMs to sync with recent builds of EAP
Use BOM managed version of jbossws-cxf-client

### CODE REVIEW

**Comment by pgier** [comment]
Note: only the jbossws-cxf-client commit should be cherry-picked to the 7.0.x branch

**Comment by sgilda** [comment]
When I try to build all the quickstarts using "mvn clean install '-Pdefault,!complex-dependencies'
", It fails with this error:

[ERROR] Failed to execute goal on project jboss-jaxws-retail-service: Could not resolve dependencies for project org.jboss.quickstarts.eap:jboss-jaxws-retail-service:war:7.0.0-SNAPSHOT: The following artifacts could not be resolved: org.glassfish.jaxb:jaxb-runtime:jar:2.2.11.jbossorg-1, org.glassfish.jaxb:jaxb-xjc:jar:2.2.11.jbossorg-1, org.glassfish.jaxb:jaxb-core:jar:2.2.11.jbossorg-1: Could not find artifact org.glassfish.jaxb:jaxb-runtime:jar:2.2.11.jbossorg-1 in jboss-developer-repository (http://jboss-developer.github.io/temp-maven-repo/) -> [Help 1]

**Comment by sgilda** [comment]
@pgier : What should I do with this pull request? I can't merge these commits because the build fails.

**Comment by pgier** [comment]
Does the failure still happen if you add the jboss.org repo to your build settings?
I probably need to release a new BOM which excludes those dependencies, or we can exclude them from the quickstarts.

**Comment by sgilda** [comment]
@pgier : No, I didn't try that. Don't we need this to build with just the included JBoss EAP repositories?

**Comment by pgier** [comment]
@sgilda I updated the commits.  Can you try testing again?

**Comment by sgilda** [comment]
@pgier: Yes, this one seems to work. Merging to 7.0.x-develop.

**Comment by sgilda** [comment]
@pgier: Should I only cherry-pick the following commit to the 7.0.x branch?

https://github.com/jboss-developer/jboss-eap-quickstarts/commit/488a8fa2922abca45d3fbbd6b2dabdc430b8002d

**Comment by psakar** [comment]
@sgilda I think it should not be cherry picked to 7.0.x because of https://issues.jboss.org/browse/JBEAP-3953 and https://github.com/jboss-developer/jboss-eap-quickstarts/commit/93030ff586abf0fc380395d181f7b6ca481ee1c9

**Comment by sgilda** [comment]
@psakar and @pgier: So neither of these commits need to be cherry-picked to 7.0.x?

**Comment by pgier** [comment]
@sgilda I'll create a separate PR for the 7.0.x branch after this one is merged.

**Comment by sgilda** [comment]
@pgier: This one was merged a few hours ago.

**Pull request merged**
