### PR TITLE
Remove alternate EAP versions for version.jboss.bom.eap, version.jboss.as, and version.jboss.spec.javaee.6.0

### PR DESCRIPTION
**Pull request by sgilda**

### CODE REVIEW

**Comment by rafabene** [comment]
It looks good to me :)

**Comment by sgilda** [comment]
It doesn't build, so I won't merge until we resolve the problems.

**Comment by sgilda** [comment]
Do not merge until we resolve the BOM issues! I can no longer do a build.

**Comment by sgilda** [comment]
@rafabene : I think this is ready to go. It builds successfully.

**Pull request merged**
