### PR TITLE
Fix broken link to http://www.jboss.org/jbossas in default.xhtml files

### PR DESCRIPTION
**Pull request by sgilda**
Do we need to change the kitchensink and kitchensink-ear archetypes also?

### CODE REVIEW

**Comment by pmuir** [comment]
Yes, can you fix or file an issue?

**Comment by sgilda** [comment]
I would be happy to do that but I've never done anything with them. 
Where are they located?

**Comment by sgilda** [comment]
I tried to squash my commits, but things got messed up. Please make sure these commits are OK>

**Comment by pmuir** [comment]
Squashed and merged

**Pull request closed without merging**
