### PR TITLE
Use deployable datasources

### PR DESCRIPTION
**Pull request by pmuir**
- Use a different datasource for test and app

### CODE REVIEW

**Comment by pmuir** [comment]
Don't merge this yet, I need to update other quickstarts with this. Getting review of naming conventions from Jesper first though.

**Comment by sgilda** [comment]
OK. I'll wait.

**Comment by pmuir** [comment]
Sande, do you want to give this a review now. Make sure you understand what I've done!

**Comment by sgilda** [comment]
I noticed that too as I was going through it. They no longer use ExampleDS. :-)

**Comment by sgilda** [comment]
I like the new naming convention. I have a couple of questions:

The bean-validation quickstart defines a test/resources/META-INF/test-persistence.xml defining <jta-data-source>java:jboss/datasources/BeanValidationQuickstartTestDS</jta-data-source>
Unlike the others, it does NOT define a main/resources/META-INF/persistence.xml defining <jta-data-source>java:jboss/datasources/BeanValidationQuickstartDS</jta-data-source>
I assume this quickstart is different in some way from the others that have arquillian tests?

Should the jta datasource be changed for the kitchensink-html5-mobile quickstart? I know that comes from Aerogear, but I noticed it still uses ExampleDS: <jta-data-source>java:jboss/datasources/ExampleDS</jta-data-source>

**Comment by pmuir** [comment]
> The bean-validation quickstart defines a test/resources/META-INF/test-persistence.xml defining ? 
> java:jboss/datasources/BeanValidationQuickstartTestDS
> Unlike the others, it does NOT define a main/resources/META-INF/persistence.xml defining ?>java:jboss/datasources/BeanValidationQuickstartDS
> I assume this quickstart is different in some way from the others that have arquillian tests?

This quickstart only has tests...

> Should the jta datasource be changed for the kitchensink-html5-mobile quickstart? I know that comes from Aerogear, but I > noticed it still uses ExampleDS: java:jboss/datasources/ExampleDS

Yes, I've asked Jay to do this :-)

**Comment by pmuir** [comment]
Do you want to merge if you are happy?

**Comment by sgilda** [comment]
I should have looked in that directory. :-)
Pushed and closed.

**Pull request closed without merging**
