### PR TITLE
JDF-605: update the link to the seamframework.org site documentation

### PR DESCRIPTION
**Pull request by sgilda**

### CODE REVIEW

**Comment by rafabene** [comment]
It looks fine!

**Comment by sgilda** [comment]
I'll wait for a response from @pmuir before I merge.

**Comment by LightGuard** [comment]
Actually, the correct URL should be http://www.cdi-spec.org/faq. It's in an accordion panel, and there isn't a direct link to display it (thanks bootstrap).

**Comment by sgilda** [comment]
Thanks @LightGuard . I'll change it to that one.

**Comment by rafabene** [comment]
@sgilda wait until https://github.com/cdi-spec/cdi-spec.org/issues/9 is solved so you can link directly to the Answer. Thanks

**Comment by sgilda** [comment]
@rafabene: Yes. I saw the JIRA. Thanks!

**Comment by LightGuard** [comment]
I've fixed this and pushed the fix to the production cdi-spec site.

**Comment by sgilda** [comment]
@LightGuard : is this the new correct link?

```
   http://www.cdi-spec.org/faq/#accordion6
```

**Comment by rafabene** [comment]
Looks good! Ready to merge!

**Pull request merged**
