### PR TITLE
Jaxp

### PR DESCRIPTION
**Pull request by pmuir**

### CODE REVIEW

**Comment by sgilda** [comment]
This looks good to me. The README is clear. I tested loading an XML file that doesn't match the schema and it gives a nice error message: 
Severity: Validation Error  
Exception: org.xml.sax.SAXParseException: cvc-elt.1: Cannot find the declaration of element 'project'.

Pete: Do you want me to push it?

**Comment by pmuir** [comment]
Please do.

On 19 March 2012 23:40, sgilda
reply@reply.github.com
wrote:

**Comment by sgilda** [comment]
Done!

**Comment by sgilda** [comment]
Pushed.

**Pull request merged**
