### PR TITLE
Changed to support authentication using the Database JAAS LoginModule.

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Comment by pedroigor** [comment]
Instead of using the the RealUsersRoles JAAS LoginModule, these changes show how to setup and use the Database LoginModule to authenticate users.

**Comment by sgilda** [comment]
Very nice!

We are trying to add jboss-cli commands where possible in addition to the XML snippets. The new format can be found in this pull: https://github.com/jboss-jdf/jboss-as-quickstart/pull/333. You can use the README.md file for this commit https://github.com/sgilda/quickstart/commit/4e0024130281740a6040e71cae80dd3d2c60d4d2

I figured out the commands:

/subsystem=security/security-domain=servlet-security-quickstart/:add(cache-type=default)

/subsystem=security/security-domain=servlet-security-quickstart/authentication=classic:add(login-modules=[{"code"=>"Database", "flag"=>"required", "module-options"=>[("dsJndiName"=>"java:jboss/datasources/ServletSecurityDS"),("principalsQuery"=>"SELECT PASSWORD FROM USERS WHERE USERNAME = ?"), ("rolesQuery"=>"SELECT R.NAME, 'Roles' FROM USERS_ROLES UR INNER JOIN ROLES R ON R.ID = UR.ROLE_ID INNER JOIN USERS U ON U.ID = UR.USER_ID WHERE U.USERNAME = ?")]}])

/:reload

Let me know if you want me to modify the README for you. Send me an email and I'll attach the modified file.

Just a note to myself. This is to address issue 342: https://github.com/jboss-jdf/jboss-as-quickstart/issues/342

**Comment by sgilda** [comment]
I ran into a few problems with the instructions in the README file.

Under "What is it?", it says "When you deploy this example, one user is automatically created for you: guest. This data is located in the src/main/resources/import.sql file. The guest user password is guest." When I access the app, guest/guest works as expected.

Later, under "Access the application", it says "After a successful login using quickstarUser/quickstartPassword" (with a typo in quicstartUser), not guest/guest. All the other quickstarts use quickstartUser/quickstartPassword, would you mind changing this one from guest/guest to quickstartUser/quickstartPassword to be consistent with the other quickstarts?

Later, it says "You can now change the role in the quickstart /src/main/webapp/WEB-INF/classes/roles.properties files to notauthorized." There is no roles.properties file. What do they need to modify to get the "HTTP Status 403 - Access to the requested resource has been denied" message?

Thanks,
Sande

**Comment by pedroigor** [comment]
Hi Sande,

   I have fixed the instructions on the README.md file. Sorry for the inconvenience. 

   Now it reflects the right instructions to change roles and get the 403 error when configuring a invalid role.

Thanks.
Pedro Igor

**Comment by sgilda** [comment]
Hi Pedro Igor,

I made some modifications to your README.md file to add the jboss-cli commands and fix a few typos. If you contact me offline and give me your email address, I will send the edited README.md file  to you.

I am also running into a few issues with this quickstart: 
- I modified the import.sql as suggested, and did not close my browser. The page, (http://localhost:8080/jboss-as-servlet-security/SecuredServlet, still displayed as logged in successfully, even when I hit refresh.It didn't prompt me to login or give an error. This doesn't seem right. 
- I then killed the server and restarted it. Then when I access http://localhost:8080/jboss-as-servlet-security, right away I get "HTTP Status 403 - Access to the requested resource has been denied". I don't even get a chance to log in as anyone. Is it supposed to work this way?

This quickstart might benefit from having a couple of users seeded at the beginning where one has access and one doesn't. 
- guest/guest in a guest role that has no access
- quickstartUser/quickstartPassword in the quickstart role that is allowed access

Either that, or maybe it needs a logout button? What do you think?

Thanks, Sande

**Comment by sgilda** [comment]
Pedro Igor, this looks good to me (except for my wishlist item of a logout button!).

Pete, do you want to review this, or should I merge?

**Comment by sgilda** [comment]
Squashed and merged.

@pmuir: let me know if you have any comments or suggestions.

**Comment by pmuir** [comment]
@sgilda, I'll review this one please

**Pull request closed without merging**
