### PR TITLE
Fixing broken urls at the main page

### PR DESCRIPTION
**Pull request by abstractj**
All the URLs to the projects at the main page are broken. This is gonna fix the github issue (https://github.com/github/markup/issues/84)

### CODE REVIEW

**Comment by pmuir** [comment]
This will break all the links locally :-(

**Comment by abstractj** [comment]
Are we running README.md locally?

**Comment by pmuir** [comment]
Yes, every release :-)

On 7 May 2012 23:32, Bruno Oliveira
reply@reply.github.com
wrote:

**Comment by abstractj** [comment]
Got it :)

**Pull request closed without merging**
