### PR TITLE
bean-validation-custom-constraint: Bean Validation using custom constraints via Arquillian Example.

### PR DESCRIPTION
**Pull request by girirajsharma**
This Quickstart demonstrates how to use CDI 1.0, JPA 2.0 and Bean Validation 1.0. to show how to test bean validation using custom constraints with Arquillian tests.

### CODE REVIEW

**Comment by sgilda** [comment]
Other than the blank line in the README file, this looks good! 

In the "What is it?" section of the README, it might be nice to talk a little about the custom constraints the quickstart and point them to the constraint in the `Person` class and the code in AddressValidator class, but it is not totally necessary. 

I need to find someone to do a final code review and it will be good to go. Thanks for submitting this one. :-)

**Comment by girirajsharma** [comment]
@sgilda Thanks. Readme.md file has been pushed again with required changes :)

**Comment by sgilda** [comment]
Much better. Thanks!
Now I just need someone to review the code and it will be ready to merge!

**Comment by rafabene** [comment]
It looks fine for me!

**Comment by sgilda** [comment]
Merged!

**Pull request closed without merging**
