### PR TITLE
JBEAP-948: test updated to RestEasy 3

### PR DESCRIPTION
**Pull request by treblereel**
-- remove deprecated code
-- README.md

### CODE REVIEW

**Comment by sgilda** [comment]
@treblereel : I just tested this pull and I still see "Tests are skipped."

**Comment by sgilda** [comment]
This didn't work. In the meantime, I fixed it with this commit: https://github.com/jboss-developer/jboss-eap-quickstarts/commit/54487e9dd0f257f87de894f28fa6a3ecdf26f646

**Comment by sgilda** [comment]
@treblereel : Thanks anyway!!

**Comment by treblereel** [comment]
hmm:

> mvn install
> [INFO] JBoss EAP Quickstart: ejb-remote - client .......... SUCCESS [  0.046 s]
> [INFO] JBoss EAP Quickstart: resteasy-jaxrs-client ........ FAILURE [  1.031 s]
> [INFO] JBoss EAP Quickstart: jta-crash-rec ................ SKIPPED
> [INFO] JBoss EAP Quickstart: wsat-simple .................. SKIPPED
> [INFO] JBoss EAP Quickstart: wsba-coordinator-completion-simple SKIPPED
> [INFO] JBoss EAP Quickstart: wsba-participant-completion-simple SKIPPED
> [INFO] JBoss EAP Quickstart: Parent ....................... SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE

As we can see from README.md:
IMPORTANT: This quickstart depends on the deployment of the 'helloworld-rs' quickstart for its test.

That's why test disabled by default, and i also want to add :+1: 

[WARNING] /Users/chani/workspace/jboss-eap-quickstarts/resteasy-jaxrs-client/src/test/java/org/jboss/as/quickstarts/jaxrsclient/JaxRsClientTest.java: /Users/chani/workspace/jboss-eap-quickstarts/resteasy-jaxrs-client/src/test/java/org/jboss/as/quickstarts/jaxrsclient/JaxRsClientTest.java uses or overrides a deprecated API.
[WARNING] /Users/chani/workspace/jboss-eap-quickstarts/resteasy-jaxrs-client/src/test/java/org/jboss/as/quickstarts/jaxrsclient/JaxRsClientTest.java: Recompile with -Xlint:deprecation for details.

**Pull request closed without merging**
