### PR TITLE
Master

### PR DESCRIPTION
**Pull request by pelekekona**
A little error on delete.

### CODE REVIEW

**Comment by sgilda** [comment]
@Pelekekona : I'm not clear about the intent of this pull. It adds a lot of commits and new quickstarts. Can you explain?

**Comment by sgilda** [comment]
I am closing this pull because I don't believe it is valid.

**Comment by pelekekona** [comment]
Sorry for the inconvenience.

Just tried to become familiar with the tool...

2015-12-01 15:55 GMT+01:00 sgilda notifications@github.com:

**Comment by sgilda** [comment]
@Pelekekona : Good to know! Thanks for the explanation.

**Pull request closed without merging**
