### PR TITLE
helloworld-mdb-propertysubstitution: Enhanced the helloworld-mdb quickstart

### PR DESCRIPTION
**Pull request by sgilda**
to demonstrate property substitution

### CODE REVIEW

**Comment by sgilda** [comment]
This needs a code review.

**Comment by sgilda** [comment]
This was created based on this bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1090012
This quickstart was reviewed by Miroslav Novak and commented on here: https://bugzilla.redhat.com/show_bug.cgi?id=1090012#c11

**Comment by rafabene** [comment]
It looks fine!

**Comment by sgilda** [comment]
Thanks Rafael. Merged.

**Pull request closed without merging**
