### PR TITLE
JBEAP-17131: Remove xsi-schemalocation

### PR DESCRIPTION
**Pull request by parsharma**
Removed xsi-schemalocation. This issue is resolved in [JBIDE-18319](https://issues.redhat.com/browse/JBIDE-18319).

### CODE REVIEW

**Comment by emmartins** [comment]
@parsharma all Quickstarts development happens at https://github.com/wildfly/quickstart repo, you should first clone the JBEAP JIRA to WFLY JIRA, and then submit PR to wildfly repo, and in PR description you should include a line "Issue: WFLY_JIRA_URL", please check PRs over there to see how these are done and worked out

**Comment by parsharma** [comment]
@emmartins do you mean first i have to create issue in JIRA for WFLY? and then commit the changes?

**Comment by emmartins** [comment]
Yes, this is accomplished by first “clone” the JBEAP jira and then “move”
that clone to the WFLY jira project. Then your PR at wildfly/QuickStart
should reference the WFLY issue as shown in other PRs.

**Comment by parsharma** [comment]
@emmartins As you mentioned, I have created the pull request in WFLY: https://github.com/wildfly/quickstart/pull/369

**Comment by parsharma** [comment]
@emmartins Should we close this PR?

**Comment by emmartins** [comment]
yes @parsharma , thanks for reminding me

**Pull request closed without merging**
