### PR TITLE
Fix all POM file errors reported by qstools EXCEPT for 

### PR DESCRIPTION
**Pull request by sgilda**
new BOM suggestions and non JBoss/JDF BOM reports

### CODE REVIEW

**Comment by LightGuard** [comment]
Big change. Does everything still work? Looking quickly through it, I don't see any problems with it as long as it still builds and works correctly.

**Comment by sgilda** [comment]
@LightGuard : I ran `mvn clean install '-Pdefault,!complex-dependencies'` and everything compiles fine. I also compiled the quickstarts excluded due to complex dependencies. I did not deploy or test runtime though, but if they build, I feel comfortable with the changes. 

If you append ?w=1 to the URL for the changes, it's not as scary as it looks. There were a lot of tab character and whitespace changes. :-)

**Comment by LightGuard** [comment]
Sounds like you're pretty safe then.

**Comment by sgilda** [comment]
Agreed. Thanks!

**Comment by sgilda** [comment]
Merged.

**Pull request closed without merging**
