### PR TITLE
Fix issue 178: hibernate3 validations fail;

### PR DESCRIPTION
**Pull request by sgilda**
Also,  exception for duplicate key was not returned to the form

### CODE REVIEW

**Comment by sgilda** [comment]
Pete, I'm not a UI programmer, so please be sure to review the code changes. :-)

**Comment by pmuir** [comment]
Code looks good, assuming it works!

**Comment by sgilda** [comment]
Well, I tested it as best I could. Seems to work. :-)

**Comment by sgilda** [comment]
Merged.

**Pull request closed without merging**
