### PR TITLE
Add command line arguments and fix wrong/missing comments

### PR DESCRIPTION
**Pull request by wfink**

### CODE REVIEW

**Comment by sgilda** [comment]
Thanks Wolf. I'll try to review this soon.

**Comment by sgilda** [comment]
This looks good! Is there a way I can test the remote server without an extra machine?

**Comment by wfink** [comment]
You should have tested this before, right ;) ?
Anyway if you start the server with "-b <your IP address>" the default "localhost" will not work and you can use the approach with the properties file.

**Comment by sgilda** [comment]
Yes, at the time, I probably should have, but it was crazy busy and I wanted to get it merge. If you have tested it and it works, I'm good. :-)

**Comment by wfink** [comment]
I've had tested both :)

**Comment by sgilda** [comment]
Merged.

**Pull request closed without merging**
