### PR TITLE
Issue 373 - Add instructions for root mvn install command

### PR DESCRIPTION
**Pull request by sgilda**

### CODE REVIEW

**Comment by pmuir** [comment]
@sgilda might be nice to list all the possible profiles, and what they are for/require?

**Comment by sgilda** [comment]
Good idea! I may need some help with a few of them though. I'll ping you if I need you. :-)

**Comment by sgilda** [comment]
Added information about the Maven profiles defined in the root POM file.

**Comment by pmuir** [comment]
Merged

**Pull request closed without merging**
