### PR TITLE
Fixes issue with helloworld-jms build status message in case of build failure

### PR DESCRIPTION
**Pull request by wprice**
Simple fix to throw Exception to indicate build failure when test client experiences exception.

### CODE REVIEW

**Comment by sgilda** [comment]
Is this something you can do? If not, I can try, but I'm not proficient at git. ;-)
Pete, do you need to review this change?

**Comment by wprice** [comment]
I don't have the access rights, Pete should. 

Regards,

Weston

**Comment by pmuir** [comment]
Weston, you can change this, just amend the commit locally to remove the file, and force push it to github, and this pull will then be updated.

Technically looks fine.

**Comment by wprice** [comment]
Should be done now.

Weston

**Comment by sgilda** [comment]
Did you push it to your repo? I still see the file. Maybe I'm doing something wrong here...

**Comment by wprice** [comment]
I pushed it. Let me check, that file should be gone.

W

**Comment by pmuir** [comment]
Sometimes the pull doesn't update right. Try pulling down Weston's branch.

**Comment by wprice** [comment]
Give me one sec.

W

**Comment by wprice** [comment]
Try now...stupid remote-refs may have gotten in the way of the push.

**Comment by sgilda** [comment]
I did. I fetched his latest and reset --hard. :-)

**Comment by sgilda** [comment]
That's better! :-)

**Comment by wprice** [comment]
I just pushed again about 5 minutes ago.

**Comment by sgilda** [comment]
Squashed commits, pushed upstream, and closed.

**Pull request closed without merging**
