### PR TITLE
Hibernate4 quickstart modified to be in sync with kitchensink changes

### PR DESCRIPTION
**Pull request by madhumita12**
Pete/Sande

```
       These are changes in response to your email to make hibernate 4 in sync with kitchensink changes.
```

### CODE REVIEW

**Comment by sgilda** [comment]
Madhumita, 
I just tested this and it works, but the dual branding is not there. Deploy the kitchensink and access the application. You'll see it has the nice branding logos for the product and the project. It's also not using the same layout, stylesheet, or other resources.

I also noticed the MemberRepository.findByEmail() method is commented out. If it's not supported, it would probably be better to remove it.

Pete, was the intention of this to also to duplicate the dual branding aspect of the kitchensink, or am I looking for too much here? :-)

**Comment by madhumita12** [comment]
Sande/Pete,

```
      I had just implemented the architecture changes.I did not ponder over cosmetic changes but if they are required I can take a look again and add them.Let me know.
```

**Comment by sgilda** [comment]
I thought we were going to dual-brand all of them, but I could be wrong. :-)
We'll see what Pete has to say.

**Comment by pmuir** [comment]
Yes, we need to apply the cosmetic changes too :-)

**Comment by sgilda** [comment]
Madhumita,
Just checking in to see how the UI changes are going. Do you think this will be competed soon?
Thanks,
Sande

**Comment by madhumita12** [comment]
Sande,

```
      Really sorry I have not had time to take a look at this.I will try over the weekend.
```

**Comment by madhumita12** [comment]
Sande/Pete,

```
            modified hibernate4 to reflect UI changes as in kitchensink
```

**Comment by sgilda** [comment]
Thanks Madhumita. I will try to look at this in the next few days.

**Comment by sgilda** [comment]
Madhumita, 

This looks much better! I have a couple of minor comments:
1. In the form, "Member Id(Enter Unique number):" could use a space between "Id" and "(Enter)" and a lower case "u" for "unique"
2. If possible, could the labels be a little wider? If not, this is not a big deal.
3. If I enter an existing member Id, it throws an exception to the page and it displays an HTTP Status 500 with a stack trace:
   javax.servlet.ServletException: javax.ejb.EJBException: org.hibernate.exception.ConstraintViolationException: Unique index or primary key violation: "PRIMARY_KEY_E ON PUBLIC.MEMBERHIBERNATE4DEMO(ID)"; SQL statement:
   insert into MemberHibernate4Demo (address, email, name, phone_number, id) values (?, ?, ?, ?, ?) [23505-161]
   javax.faces.webapp.FacesServlet.service(FacesServlet.java:606)
   org.jboss.weld.servlet.ConversationPropagationFilter.doFilter(ConversationPropagationFilter.java:62)

Is it possible to catch the exception and just out a formatted error message?
This was done for a few other quickstarts. I will see if I can find the ones that do that.

Thanks,
Sande

**Comment by sgilda** [comment]
Madhumita, I think the base kitchensink quickstart has the same issue with throwing the exception. We'll need to address it there first.

**Comment by madhumita12** [comment]
Sande,

```
       I have added a fix to handle the exception thrown when duplicate member id is entered for hibernate4 quickstart.I think the same fix should work for base kitchensink quickstart as well.
```

**Comment by sgilda** [comment]
Hi Madhumita, This looks good!
Pete, do you need to review anything?

**Comment by pmuir** [comment]
Merged.

**Pull request closed without merging**
