### PR TITLE
[JBEAP-6228] Replace WildFly artifacts with EAP ones

### PR DESCRIPTION
**Pull request by psakar**
replaced snapshot bom with version released for 7.0.0.GA
removed temp-repo which is not needed any more
 replace groupId org.wildfly with org.jboss.eap

### CODE REVIEW

**Comment by sgilda** [comment]
@psakar : Why are you removing the staging repository elements?

**Comment by sgilda** [comment]
@psakar : This breaks the quickstarts and I am closing it.

Please talk to @pgier about how he updated the product quickstarts. I believe you do the following:
1. Check out the 7.1.x product branch of the quickstarts.
2. Replace the `org.wildfly` groupID with `org.jboss.eap`.
3. Set the BOM version to the valid version.
4. Issue the pull request back to the 7.1.x product branch.

**Comment by sgilda** [comment]
@psakar: I will try to update the 7.1.x-develop branch and you can update the 7.1.x branch.

**Comment by psakar** [comment]
@sgilda this can not go this way. I'm going to escalate it next pm meeting

**Comment by sgilda** [comment]
@psakar : Please ignore my comment above. After I wrote that comment, I realized that you had basically already done the steps I described back in January with this commit: 

[JBEAP-2584] Rename Maven group and version to org.jboss.eap:*:7.0.0.ERx
https://github.com/jboss-developer/jboss-eap-quickstarts/commit/24df1d89c9a7d8a9b01dcf2f304e367425a637be

So this issue is resolved. There is nothing further to do.

I also updated the etherpad with the solution proposed by Paul Gier. I think it's how he handled this in the past.

**Pull request closed without merging**
