### PR TITLE
Update all Quickstarts to use 1.0.7.CR8 bom (aligned to WFK 2.3)

### PR DESCRIPTION
**Pull request by rafabene**

### CODE REVIEW

**Comment by sgilda** [comment]
This looks good. Would you like me to merge it?

**Comment by sgilda** [comment]
Both the root pom.xml and the helloworld-singleton/pom.xml files still have <version.jboss.bom>1.0.6.Final</version.jboss.bom>

@rafabene : Should they be updated?

**Comment by rafabene** [comment]
Hummm, That's  because helloworld-singleton declared the property and doesn't use a JDF bom.
I've update them manually and I'll open a Jira to fix this

**Comment by sgilda** [comment]
Modified root pom.xml file and merged.

**Pull request closed without merging**
