### PR TITLE
Master ejb throws exception

### PR DESCRIPTION
**Pull request by bmaxwell**
ejb-throws-exception quick start requested by Sande

### CODE REVIEW

**Comment by sgilda** [comment]
Hi Brad,
I finally got a chance to look at this. Sorry for the delay. The POM versions have changed since you issued this pull and I was not able to deploy it. 

In the top level POM:
- I don't believe you need the`<parent>` element.
- The version number has changed from 7.1.1.CR2 to 7.1.1.Final. This applies to the ejb and web dependencies and the child POMs.
- The `<javaee6.web.spec.version>` is now 3.0.0.Final
- The jboss-as-maven-plugin version is now 7.1.1.Final.
- It is not good practice to define repository information in the POMs. We were asked to remove the `<repository>` and `<pluginRepository>` elements from the POM files.

I'm not good a Maven, so I need to defer to Pete.
- Pete, can he add the `<jboss.bom.version>1.0.0.Final</jboss.bom.version>` property and boss-javaee-6.0-with-tools dependency to the parent and eliminate versions from arquillian-junit-container, arquillian-protocol-servlet, etc?
  I'm also not sure about the dependencies in the child POMs.I'll play around a bit with it.

**Comment by sgilda** [comment]
I played around with the POM files and was able to deploy and run this quickstart. Very nice!

The running application says "Clicking Say Hello with an empty name will catch a custom exception (GreeterException) coming back from the EJB". You might want to put single quotes around 'Say Hello' for the button text.

It might be nice to add something like this to the README in the "Access the Application" section. For example:

Enter a name in the input field and click the 'Say Hello'  button to see the response. Click 'Say Hello' with an empty name to catch a custom exception (GreeterException) coming back from the EJB"

The README also says to click the 'Greet' button. You should probably change that to 'Say Hello'. ;-)

**Comment by pmuir** [comment]
I've started to align to quickstart standards at https://github.com/pmuir/quickstart/tree/ejb-throws-exception but I need input from Brad on a few issues:
- Why the "client" module was introduced? And isn't really a "shared" module?
- We need copyright headers on all files
- Code looks like it is copied from ejb-in-ear, but all attribution and comments have been changed
- Use FacesMessages in the web module

**Comment by sgilda** [comment]
Hi Brad,

Where do we stand with this quickstart? Have you had a chance to look at Pete's comments?

Thanks,
Sande

**Comment by bmaxwell** [comment]
Sorry, we got really busy, when I get caught up I'm going to circle back and see try to fix this one up and we have some other folks talking about trying to start making quickstarts.
Thanks,
Brad

**Comment by sgilda** [comment]
Hi Brad,
No problem. Glad to hear you're still around and interested in contributing. I look forward to hearing more  about them!

**Comment by sgilda** [comment]
20121217: Sent email reminder.

**Comment by bmaxwell** [comment]
moved to a new pull request - since I redid my repo

**Pull request closed without merging**
