### PR TITLE
Quickstart 59: XA datasource configuration and recovery

### PR DESCRIPTION
**Pull request by mmusgrov**
Shows how to perform XA transactions on an H2 database with recovery

### CODE REVIEW

**Comment by pmuir** [comment]
We need to check if we can use byteman in eap.

**Comment by mmusgrov** [comment]
OK. If it turns out to be an issue I can remove byteman from the 
quickstart (and tell the user to use a debugger instead).

**Comment by pmuir** [comment]
If you can, that would be best. Alternatively, we can try to get byteman into Maven central, which bypasses the issue ;-)

**Comment by mmusgrov** [comment]
I asked Andrew last week to do this. I will chase him for a status update.

**Comment by mmusgrov** [comment]
What's the deadline for uploading it to central?

**Comment by mmusgrov** [comment]
I have removed references to byteman (and the jboss repository) from the pom. The updated README.md tells the user where he can download byteman if he wants to perform the recovery step of the quickstart.

**Comment by sgilda** [comment]
Mike, I am starting to look at this now. Thanks!

**Comment by sgilda** [comment]
Hi Mike,
This is a great example! It is one that is needed by most customers and will be extremely useful. 

I just did an initial usability test and had no problem with it. It works great! However, I think a few things could be be made a little clearer or informative.

I do have a few comments or suggestions for the README file:
- It might be nice to give a little more information about XA Recovery and what it means. For example, you might want to open with something like this (I found this in the EAP 5 documentation): "XA recovery deals with system or application failures to ensure that resources of a transaction are applied consistently to all resources affected by the transaction, even if any of the application processes or the machine hosting them crash or lose network connectivity. " 
- Under "Deploying the Application",  step 2. "Create 2 XA datasources...", you end up jumping around a bit. You click on the link "see ref 2 below for instructions" and when you get there, you click on "ref1" to go back to create the "admin user", which is called the "web console" user in the reference. Maybe instead of a "Notes" section, you could just reference a section named "Configure the XA datasources" that would have step 1, "Create the admin user" (keep the name consistent), step 2. "Create the XA datasources for this example", step 3: "Enable the XA datasources for recovery". 
- Again, instead of ref[4] "Enabling byteman scripting" under "Notes", maybe make it its own section "Enable byteman scripting" and under "Deploying the Application",  step 5, change the link "see notes in ref 4" to "see Enable byteman scripting" for details. 

When you run the application, it would be nice if the page had the same instructions that are in the README file so you don't have to switch back and forth to see how it works. It would also be nice if the page had a title indicating it's the XA Recovery example. :-)

The POM file versions need to be updated to avoid runtime errors and to allow the scripts that move the quickstart to EAP to work. You can find the versions to use here: 
https://docs.jboss.org/author/display/AS71/Maven+POM+Versions+Checklist

I haven't had a chance to try the failover yet, but wanted to get this information to you quickly. Please let me know if you have any questions or concerns about my comments.

Thanks, Sande

**Comment by sgilda** [comment]
One more thing. In the README you say:
With byteman you also have the option of dynamically loading and unloading scripts using the bmsubmit.sh tool. Instead of configuring the agent using a byteman script configure a listener instead:
 JAVA_OPTS="${JAVA_OPTS} -javaagent:$BYTEMAN_HOME/lib/byteman.jar=listener:true"

I found that confusing and am not clear what you mean by "Instead of...". 
Should we not do something in the previous step? 
Do we add that line to the standalone.conf file or is this something we do in a shell command?

The you say "When you are ready to dynamically install the script, type". 
What determines when I'm ready? Is this when I'm ready to test recovery?

Thanks, Sande

**Comment by sgilda** [comment]
Since I am testing quickstarts from contributors, this situation is probably unique to the way I work, but I ran into this problem starting the server when I checked out another branch to test a quickstart:
org.jboss.byteman.agent.Main: unable to read rule script file : /home/sgilda/Quickstarts/quickstart/xa-transactions/src/main/scripts/xa.btm
Exception in thread "main" java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:323)
    at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:338)
Caused by: java.io.FileNotFoundException: /home/sgilda/Quickstarts/quickstart/xa-transactions/src/main/scripts/xa.btm (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:120)
    at java.io.FileInputStream.<init>(FileInputStream.java:79)
    at org.jboss.byteman.agent.Main.premain(Main.java:166)
    ... 6 more
You might still want to add a step to back up the server configuration file before they add the byteman changes, because if they do remove this quickstart, the server won't start until you restore the configuration to the previous state. :-)

**Comment by mmusgrov** [comment]
Hi Sande, You have provide me with some great suggestions, I'll update the quickstart README accordingly.

Your previous but one comment regarding confusion about the Byteman section is because I have indicated that there are two ways of injecting Byteman rules - I will resolve this by only documenting one of them in the README.

I will update the README to use "dynamic rule injection" and that should clear up the last issue you came across (regarding the java.io.FileNotFoundException).

Thanks

**Comment by sgilda** [comment]
Hi Mike,
Well, I didn't really have a problem. I always back up config files when asked to change them. Then I can do a simple rename of each to switch back and forth. But it is nice to warn people in advance.
I assume with "dynamic rule injection" server startup will be smart enough to continue even if the quickstart isn't there? That would be great technique to show too!
Thanks, Sande

**Comment by sgilda** [comment]
Mike, is this one ready to go? I believe we left it that you were going to modify the README to use "dynamic rule injection". I would modify the README for you, but I have no clue how to go about it. ;-)

**Comment by mmusgrov** [comment]
Hi Sande, Sorry I have been busy on other issues. I will sanity check my 
changes tomorrow and then add a new commit to my pull request.

Thanks,

**Pull request closed without merging**
