### PR TITLE
Minor updates

### PR DESCRIPTION
**Pull request by snowolfe**
Changed EJB to return 3 decimal places, and modified the HTML output slightly

### CODE REVIEW

**Comment by sgilda** [comment]
Hi Bruce,
These commits look strange to me. It looks like you made the changes to your own repository rather than upstream. If that's the case, you risk losing updates made by others to this quickstart. Is that the case?
Thanks,
Sande

**Comment by snowolfe** [comment]
I guess that is what comes with not really knowing git :-). What should I have done? Or what did I miss doing?

**Comment by sgilda** [comment]
I am by no means a git expert, but I've made a lot of mistakes, so I've had to fix a lot of things. This is what I would do if it were me:

Make a copy of your temperature-converter folder so you don't lose your changes
$ git fetch upstream (or whatever you named the jbossas/quickstart remote repository, you can verify with $git remote -v)
$ git checkout tempconvert-updates upstream/master (I named the branch tempconver-updates)
make your changes and test
Then do your normal git add and commit
$git push snowolfe HEAD (this will great a branch in your repository named tempconvert-updates. It won't overwrite your master)
When you issue the pull, first click on the branches tab of your github and issue the pull from that.
Are you on IRC?

**Comment by snowolfe** [comment]
Thanks Sande,
I will take a look at the steps (they seem to make sense reading them) and try again. 
I am in Sydney so I had gone to bed by the time your reply came through. If I have problems, I will try and ensure we are online at the sametime and chat via IRC then.
I am a little busy over the next day or two, so will try again as soon as I get some time.

**Comment by sgilda** [comment]
Sure. I can arrange to be online in the evening (your morning) if you need me. :-)

**Comment by pmuir** [comment]
I extracted the new commit and applied.

**Comment by snowolfe** [comment]
OK - Thanks Pete. I will do it correctly next time :-). I have actually changed it again - so will push that into Git in the near future.

**Pull request closed without merging**
