### PR TITLE
JDF-455 remove maven compiler to remove JBDS issues

### PR DESCRIPTION
**Pull request by pmuir**

### CODE REVIEW

**Comment by LightGuard** [comment]
Wasn't sure if this was the final conclusion or not. I guess this PR answers the question. 
—

**Comment by rafabene** [comment]
I'm curious why this JBDS issues affects only Deltaspike Quickstarts...

**Comment by pmuir** [comment]
Yes, I got impatient ;-)

We don't use this elsewhere in the quickstarts, and so avoid this problem. I'm also unsure why the _quickstart_ is enforcing java 6.

**Comment by pmuir** [comment]
Other quickstarts don't specify the compiler plugin.

**Comment by LightGuard** [comment]
Probably some maven xml stanza I C&P'd originally from Seam 3 stuff.

On Tue, Aug 13, 2013 at 10:33 AM, Pete Muir notifications@github.comwrote:

> Other quickstarts don't specify the compiler plugin.
> 
> On 13 Aug 2013, at 17:31, Rafael Benevides notifications@github.com
> wrote:
> 
> > I'm curious why this JBDS issues affects only Deltaspike Quickstarts...
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jboss-jdf/jboss-as-quickstart/pull/586#issuecomment-22578247
> .

## 

Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by sgilda** [comment]
Merged.

**Comment by rafabene** [comment]
I know that this PR is closed but we have this snipped of code on almost 
every quickstart: 
https://github.com/jboss-jdf/jboss-as-quickstart/blob/master/bean-validation/pom.xml#L192-L200



<plugin>
<artifactId>maven-compiler-plugin</artifactId>
<version>${version.compiler.plugin}</version>
<configuration>
<source>${maven.compiler.source}</source>
<target>${maven.compiler.target}</target>
</configuration>
</plugin>

Without this, I have issues with JBDS with wrong target and source when 
importing maven project.

Em 13/08/13 13:33, Pete Muir escreveu:

**Comment by sgilda** [comment]
I saw that and thought that was the point. I tested `mvn clean install` from the root and it built successfully. I didn't test the JDBS import though. I'll try that now.

**Comment by rafabene** [comment]
@sgilda The origin was here: https://issues.jboss.org/browse/WFK2-140

**Pull request closed without merging**
