### PR TITLE
Bz1018959: Remove dual branding from the kitchensink-generated quickstarts

### PR DESCRIPTION
**Pull request by sgilda**
Also removed obsolete images and message bundles that referred to AS 7.

### CODE REVIEW

**Comment by sgilda** [comment]
Do not merge! I need to try a smaller image.

**Comment by sgilda** [comment]
I think this is ready for review.

**Comment by rafabene** [comment]
Another good job! Thanks! It looks fine!

**Comment by sgilda** [comment]
Merged.

**Pull request closed without merging**
