### PR TITLE
Spring quickstarts added

### PR DESCRIPTION
**Pull request by TejasM**
The added quickstarts are as follows:
Greeter-Spring: Simple Greeter Application using Spring 3.1
Petclinic-Spring: Advanced level Spring quickstart using Spring 3.1
Travel-Spring: Advanced level Spring quickstart using Spring 3.1
Kitchensink-Spring 5 Variants:
   -- Basic kitchensink using spring 3.1 with rest and spring mvc
   -- 4 other variants using spring 3.2 each showcase an additional feature introduced in spring 3.2

### CODE REVIEW

**Comment by sgilda** [comment]
@TejasM : I noticed the README files don't follow the template formatting and are missing some meta-data tage, so I tried to run the `qstools` utility against the quickstarts and got the following error:

[ERROR] Failed to execute goal on project petclinic: Could not resolve dependencies for project org.jboss.as.quickstarts:petclinic:war:7.1.2-SNAPSHOT: Could not find artifact org.jboss.snowdrop:snowdrop-weaving:jar:2.0.3.Final in central (http://repo.maven.apache.org/maven2) -> [Help 1]

It appears to be having a problem with petstoore-spring.

Also, I am able to successfully build greeter-spring,  but when I try to deploy, it hangs on that old remote hang:

Mar 28, 2013 3:12:54 PM org.xnio.Xnio <clinit>
INFO: XNIO Version 3.0.3.GA
Mar 28, 2013 3:12:54 PM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.0.3.GA
Mar 28, 2013 3:12:54 PM org.jboss.remoting3.EndpointImpl <clinit>
INFO: JBoss Remoting version 3.2.3.GA

It could be a problem with my server. It's been around a while and could be corrupt. I'm running this against AS 7.2, so I will clear out and try with 7.1.

**Comment by TejasM** [comment]
Sorry about the Readme files, I will fix them up. I am not sure what the `qstools` utility is so I am not sure what the error is getting at.

I haven't tested against AS 7.2 so it could definitely be the reason but I will try and see what the problem is.

**Comment by sgilda** [comment]
I just retried against a clean AS 7.2 and ran into the same issue. I know we had some remoting issues a while back. I will try it with AS 7.1 next.

@rafabene created the qstools maven plugin to automate consistency across the quickstarts. It catches things like bad formatting, missing licenses, and also Maven dependency and version issues. You can find out how to use it here: https://github.com/jboss-jdf/jboss-as-quickstart/blob/master/CONTRIBUTING.md

I may wait for you to run the qstool plugin and fix errors before I continue, however, it fails on petclinic-spring and I'm not sure why.

**Comment by sgilda** [comment]
BTW, it it should have been `qstools`, not 1qstools1. My eyes were dilated today, so my vision is off ;-)

**Comment by TejasM** [comment]
Ya I guess that is why google didn't turn up anything :)

**Comment by sgilda** [comment]
@TejasM : Did you have any luck running the QS Tools plugin?

**Comment by TejasM** [comment]
@sgilda: I wasn't working today, but yes the plugin is running and I have fixed up half of the quickstarts. I will fix the rest tomorrow and update the PR.

**Comment by sgilda** [comment]
Good! I'm glad it's working for you.

**Comment by TejasM** [comment]
@sgilda: I removed petclinic from the commit for now, because I am in the middle of rebasing it to a newer version and it doesn't make sense for you have to review it twice

**Comment by sgilda** [comment]
@TejasM : I am still getting an error when I run the QS Tools plugin:

[ERROR]   The project org.jboss.as.quickstarts:jboss-as-quickstarts-parent:7.1.2-SNAPSHOT (/home/sgilda/GitRepos/quickstart-jdf/pom.xml) has 1 error
[ERROR]     Child module /home/sgilda/GitRepos/quickstart-jdf/petclinic-spring/pom.xml of /home/sgilda/GitRepos/quickstart-jdf/pom.xml does not exist

I believe you need to remove line 178 from the root pom.xml file:

```
    <module>petclinic-spring</module>
```

After I removed that line, I ran into issues with the other existing quickstarts. You will need to fetch the latest upstream and rebase. Then it runs successfully. :-)

**Comment by sgilda** [comment]
@TejasM : It appears these need README files. You can find one to modify in the templates/ directory. Or, if you prefer to use one from another quickstart with similar functionality as the starting point, feel free to copy/paste/edit. 

Once you get the basics there, I'll be glad to help you out.

**Comment by TejasM** [comment]
@sgilda: The readmes (README.MD) were already there, but they didn't exactly match the template one. I have updated them so that they are more like the template one.

**Comment by pmuir** [comment]
@joshuawilson could you do a technical review on this?

**Comment by joshuawilson** [comment]
@pmuir I can do the tech review.

**Comment by sgilda** [comment]
@TejasM : You do plan to submit a new separate pull for each of these quickstarts, correct? 
We have pulls for kitchensink-spring and travel-spring, so you need a pull for greeter-spring and petclinic-spring. 

Can we close this one?

**Comment by TejasM** [comment]
@sgilda: I think greeter-spring has been added already, as for petclinic-spring, I still have some work to do before I send a pr for that. So this should be closed.

**Comment by sgilda** [comment]
@TejasM : I forgot that we merged greeter-spring. Thanks for the update!

**Comment by sgilda** [comment]
@joshuawilson : Thanks for offering to review!

**Pull request closed without merging**
