### PR TITLE
JDF-409: Replace richafaces quickstarts by a git submodule

### PR DESCRIPTION
**Pull request by bleathem**
Removed the kitchensink-rf and helloworld-rf quickstarts, and added the richfaces quickstarts repository as a submodule.

This PR is first done without a richfaces tag in the submodule, pending a review by the JDF team.  Once we have agreed that everything is ready to merge, I will update the PR pointing the RichFaces git submodule to a tag.

### CODE REVIEW

**Comment by sgilda** [comment]
@rafabene : How will this impact the build process in the root POM.xml file? Currently the richfaces quickstarts are listed as modules at the same level as the others. Do those have to be changed to include the submodule directory? For example: <module>richfaces-quickstart/kitchensink-fr</module> ?

**Comment by bleathem** [comment]
Good point @sgilda, I've updated the PR with an updated root pom.xml.

**Comment by sgilda** [comment]
I'm still not able to build.

$ mvn clean install '-Pdefault,!complex-dependencies'
[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]  
[ERROR]   The project org.jboss.as.quickstarts:jboss-as-quickstarts-parent:7.1.2-SNAPSHOT (/home/sgilda/GitRepos/quickstart-jdf/pom.xml) has 2 errors
[ERROR]     Child module /home/sgilda/GitRepos/quickstart-jdf/richfaces-quickstarts/helloworld-rf of /home/sgilda/GitRepos/quickstart-jdf/pom.xml does not exist
[ERROR]     Child module /home/sgilda/GitRepos/quickstart-jdf/richfaces-quickstarts/kitchensink-rf of /home/sgilda/GitRepos/quickstart-jdf/pom.xml does not exist

Still investigating.

**Comment by sgilda** [comment]
Do wee need to add instructions to the README on how to access the new submodule?

```
    git submodule update --init
```

Then to grab subsequent updates:

```
   git submodule update
```

**Comment by sgilda** [comment]
Merged.

**Pull request closed without merging**
