### PR TITLE
Fix about JAVA_OPTS with Byteman

### PR DESCRIPTION
**Pull request by gautric**
acording this link https://access.redhat.com/solutions/715343

### CODE REVIEW

**Comment by sgilda** [comment]
@gautric :  I don't see the exception mentioned in the solution when I run this quickstart. Are you seeing the issue?

**Comment by gautric** [comment]
If we use : 
export JAVA_OPTS="....."                              (1)
before standalone.sh 
JAVA_OPTS is full replaced by the new one (1) and 
the -Djboss.modules.system.pkgs=org.jboss.byteman option is removed too.
we need to reinject it.

**Comment by sgilda** [comment]
The quickstart instructions tell you to back up the standalone.conf file and append the following to the end of that file:

```
        JAVA_OPTS="-javaagent:/BYTEMAN_HOME/lib/byteman.jar=script:/QUICKSTART_HOME/jta-crash-rec/src/main/scripts/xa.btm ${JAVA_OPTS}" 
```

When you are done testing, you are instructed to remove that line from the file.

I added the line and echoed the JAVA_OPTS and I see this:

```
        -javaagent:/home/sgilda/tools/byteman-download-2.2.0.1/lib/byteman.jar=script:/home/sgilda/GitRepos/jboss-eap-quickstarts/jta-crash-rec/src/main/scripts/xa.btm -Xms1303m -Xmx1303m -XX:MaxPermSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true -Djboss.modules.policy-permissions=true
```

I remove the line and  echo the JAVA_OPTS and I see this:

```
        -Xms1303m -Xmx1303m -XX:MaxPermSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true -Djboss.modules.policy-permissions=true
```

I am still not clear what you are doing that causes it to remove the `-Djboss.modules.system.pkgs=org.jboss.byteman` option.  Are you following the instructions here? 

https://github.com/jboss-developer/jboss-developer-shared-resources/blob/master/guides/CONFIGURE_BYTEMAN.md#configure-byteman-for-use-with-the-quickstarts

**Comment by sgilda** [comment]
The quickstart experts asked the following questions:
- What version of JBoss EAP are you using?
- What JDK version are you using?
- Did you make any other changes to the quickstart?

**Comment by gautric** [comment]
Ok I just check the doc.
but I prefer user "export JAVA_OPTS" stuff rather than modify standalone.conf
you can delete the pull request.

**Comment by sgilda** [comment]
@gautric : The quickstart instructions try to prevent modification of the environment outside of the quickstart. That way, when you are done testing, you don't have to worry about cleaning up.

I will close this pull. Thanks for participating though!

**Pull request closed without merging**
