### PR TITLE
payment-cdi-event module

### PR DESCRIPTION
**Pull request by nelvadas**
Hi Sgilda, the first draft for CDI event sample.

### CODE REVIEW

**Comment by sgilda** [comment]
Hi Elvadas. I'm taking a look at this one now.

**Comment by sgilda** [comment]
Nice quickstart! 

I have limited knowledge of the cdi event model, so I can't do a technical review. Here are my comments and suggestions for clarity:

-- In the README file, could you modify the "What is it?" section to  something like the following (I may not be understanding this, so if I'm not saying the correct thing, feel free to change it):

This quickstart demonstrates how to use _CDI 1.0 Events_ in JBoss AS 7 or EAP 6. The JSF front-end client allows you to create both credit and debit operation events. 

To test this quickstart, enter an amount, choose either a Credit or Debit operation, and then click on *Pay" to create the event. A Session scoped (@SessionScoped) payment event handler catches the operation and produces (@Produces) a named list of all operations performed during this session. The event is logged in the JBoss console and the event list is displayed in a table at the bottom of the form. 

-- Actually, I would love to see more details in the above text on the basic processing flow in the README, including class names and maybe methods. It is possible for you to do something like that in the above section? I'll poke around at it and see if I can figure it out and come up with something. :-)

--- Could you also change the the log messages in PaymentBean.java from "hihi I catch a credit" and "I catch a debit" to say something like "Handling the debit event" and "Handling the credit event" (or Processing the ...)

**Comment by sgilda** [comment]
I didn't even notice the other log messages in the JBoss console. I think they all need to be clearer where they are logging from and what they are logging. I'll take a better look and add more specific comments.

**Comment by pmuir** [comment]
This branch is crazy!

I'll try to fix it and build a new branch.

**Comment by pmuir** [comment]
Here is a sanitized version of the branch - https://github.com/pmuir/quickstart/tree/payment-cdi-event. Elvadas, please make any changes on top of this, not on top of your current master!

**Comment by pmuir** [comment]
I'm closing this pull request, as we will need a new one anyway...

**Comment by nelvadas** [comment]
2012/1/6 sgilda <
reply@reply.github.com

> Nice quickstart!
> 
> I have limited knowledge of the cdi event model, so I can't do a technical
> review. Here are my comments and suggestions for clarity:
> 
> -- In the README file, could you modify the "What is it?" section to
>  something like the following (I may not be understanding this, so if I'm
> not saying the correct thing, feel free to change it):
> 
> This quickstart demonstrates how to use _CDI 1.0 Events_ in JBoss AS 7 or
> EAP 6. The JSF front-end client allows you to create both credit and debit
> operation events.
> 
> To test this quickstart, enter an amount, choose either a Credit or Debit
> operation, and then click on *Pay" to create the event. A Session scoped
> (@SessionScoped) payment event handler catches the operation and produces
> (@Produces) a named list of all operations performed during this session.
> The event is logged in the JBoss console and the event list is displayed in
> a table at the bottom of the form.
> 
> -- Actually, I would love to see more details in the above text on the
> basic processing flow in the README, including class names and maybe
> methods. It is possible for you to do something like that in the above
> section? I'll poke around at it and see if I can figure it out and come up
> with something. :-)
> 
> --- Could you also change the the log messages in PaymentBean.java from
> "hihi I catch a credit" and "I catch a debit" to say something like
> "Handling the debit event" and "Handling the credit event" (or Processing
> the ...)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jbossas/quickstart/pull/42#issuecomment-3387893

Envoy de mon tlphone Nokia

## 

*
*

_Cldt_
_Elvadas NONO_
_06 61 21 20 38_

**Pull request closed without merging**
