### PR TITLE
this is a merge from the richfaces quickstart project: kitchensink-rf

### PR DESCRIPTION
**Pull request by bleathem**

### CODE REVIEW

**Comment by sgilda** [comment]
Brian,
The README template has been modified for our quickstarts. Changes include removing line feeds (they don't render well), putting JBoss Enterprised Application Platform 6 ahead of JBoss 7, standardized sections, fix typos, and a few other changes. I don't suppose your READMEs could be modified to follow that pattern? I will email you a revised copy by email and let you decide.

Also, I just tried to build this and got the following error:
kitchensink-rf (kitchensink-rf-merge) $ mvn clean package
[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]  
[ERROR]   The project org.jboss.as.quickstarts:jboss-as-kitchensink-rf:7.1.1-SNAPSHOT (/home/sgilda/Quickstarts/quickstart/kitchensink-rf/pom.xml) has 7 errors
[ERROR]     Non-resolvable import POM: Could not find artifact org.richfaces:richfaces-bom:pom:4.2.1-SNAPSHOT @ line 42, column 22 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for com.sun.faces:jsf-impl:jar is missing. @ line 115, column 20
[ERROR]     'dependencies.dependency.version' for org.richfaces.core:richfaces-core-impl:jar is missing. @ line 129, column 19
[ERROR]     'dependencies.dependency.version' for org.richfaces.ui:richfaces-components-ui:jar is missing. @ line 144, column 19
[ERROR]     'dependencies.dependency.version' for org.atmosphere:atmosphere-runtime:jar is missing. @ line 150, column 19
[ERROR]     'dependencies.dependency.version' for org.ocpsoft.rewrite:rewrite-servlet:jar is missing. @ line 172, column 19
[ERROR]     'dependencies.dependency.version' for org.ocpsoft.rewrite:rewrite-integration-cdi:jar is missing. @ line 178, column 19
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

Any idea what I'm doing wrong?

Thanks,
Sande

**Comment by bleathem** [comment]
Oopps - forgot to git rid of the SNAPSHOT dependencies.  I'll fix that and update the pull request.

**Comment by sgilda** [comment]
Brian,
This quickstart is not listed in the table here, is it?
https://docs.jboss.org/author/display/AS71/Contributing+a+Quickstart

Thanks,
Sande

**Comment by pmuir** [comment]
I'm still seeing the SNAPSHOT dependencies.

Also, please follow the process in https://github.com/jbossas/quickstart/blob/master/CONTRIBUTING.md which describes how to make this submission. We've lost the merge commit in your pull req.

**Comment by bleathem** [comment]
@pmuir 
1) I have not yet updated the SNAPSHOT dpendencies
2) those are the instructions I followed, I must have done something wrong.  I'll try again with a subsequent pull request.

I am closing this pull request for now, there are some recently discovered bugs re need to first address.

**Pull request closed without merging**
