### PR TITLE
JDF-178 Add exception handling to kitchensink-deltaspike

### PR DESCRIPTION
**Pull request by rafabene**

### CODE REVIEW

**Comment by sgilda** [comment]
I tested this and it looks good to me.

@pmuir : Do you need to review these changes?

**Comment by pmuir** [comment]
Looks good.

**Comment by rafabene** [comment]
I will review the PR

**Comment by sgilda** [comment]
Looks good. Still works. I'm fine with this. 
@pmuir: do you need to review the code changes?

**Comment by pmuir** [comment]
Looks good to me :-)

**Comment by sgilda** [comment]
Merged upstream.

**Pull request closed without merging**
