### PR TITLE
Quickstart 27

### PR DESCRIPTION
**Pull request by kpiwko**
Hello, 

here is a modified (again) Bean Validation quickstart. I added usage of User BOMs defined at https://github.com/kpiwko/jboss-javaee-6.0-with-tools into the example and added author acknowledgement as well. 

Should you have any questions or comments, please let me know. 

Thanks,

Karel

### CODE REVIEW

**Comment by pmuir** [comment]
I've merged your BOM sources into the quickstarts and added them to the build. Can you update the quickstart to use this version of the BOM?

**Comment by pmuir** [comment]
Looks good, but I think we should point people in the README to the kitchensink demo to see BV used with a view layer (JSF).

**Comment by kpiwko** [comment]
Rebased to reflect new location of jboss-ee-6.0-with-tools BOM file

**Comment by kpiwko** [comment]
Readme updated to point to kitchesink. I'll update kitchensink to contain Arquillian Drone somewhen in the future.

**Comment by sgilda** [comment]
I haven't looked closely yet, but I do see a minor change needed in the POM. The jboss-as-maven-plugin should be 7.1.0.CR1.
Also, would you mind modifying the README based on the email I sent out today? Basically, upper case README, title "bean-validation:  Example that Demonstrates Bean Validation".

I did try a quick test against jboss-as-7.1.0.Final-SNAPSHOT.
I ran: mvn clean test -Parq-jbossas-remote and got the following output:
bean-validation (bean-validation) $ mvn clean test -Parq-jbossas-remote
[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]  
[ERROR]   The project org.jboss.as.quickstarts:bean-validation:7.0.2-SNAPSHOT (/home/sgilda/Quickstarts/quickstart/bean-validation/pom.xml) has 6 errors
[ERROR]     Non-resolvable import POM: Could not find artifact org.jboss.as.quickstarts:jboss-javaee-6.0-with-tools:pom:7.0.2-SNAPSHOT @ line 41, column 16 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for javax.enterprise:cdi-api:jar is missing. @ line 58, column 21
[ERROR]     'dependencies.dependency.version' for org.hibernate.javax.persistence:hibernate-jpa-2.0-api:jar is missing. @ line 66, column 21
[ERROR]     'dependencies.dependency.version' for junit:junit:jar is missing. @ line 100, column 21
[ERROR]     'dependencies.dependency.version' for org.jboss.arquillian.junit:arquillian-junit-container:jar is missing. @ line 108, column 21
[ERROR]     'dependencies.dependency.version' for org.jboss.as:jboss-as-arquillian-container-remote:jar is missing. @ line 214, column 29

I probably missed a step in the setup. I will try again tomorrow.

**Comment by kpiwko** [comment]
Updated README files to align with the rest of the quickstarts.

Yes, there's a step required, you need to install quickstart/bom into your local repository. This step would not be necessary once we have these user BOMs on Maven Central.

**Comment by sgilda** [comment]
OK. I thought the local Maven repository was only required for EAP 6. So you're saying these BOMs required for this quickstart are not yet on Maven Central for the community?

**Comment by pmuir** [comment]
Correct. If you do

```
cd ../bom && mvn install && cd -
```

Then you will find the build works. 
Although, I think we may need to move them on reflection...

**Comment by sgilda** [comment]
Thanks Pete. That worked. Do we need to update either the README in the root of the quickstarts (or this README) with the instructions to install the POM?

I am familiar with junit testing, but know nothing about Arquillian, so I have a few other comments/questions:

-- The README mentions there is no user interface, but in addition to seeing success where you run the command, it would be nice if it told you to watch the server console when you run the 'mvn clean test -Parq-jbossas-remote' command and what to look for. It doesn't have to be line by line details, but just that you can see it l deploy the "test.war" and then undeploy it. 

-- The result of this test is 0 failures, so I decided to try to get some failures. As I said, I'm have used junit, but am not familiar with Arquillian, so I modified the MemberValidationTest.createValidMember() method to set the phone number to "12", expecting to get "Phone number was invalid". When I run the test, instead I get:
   Failed tests:   testRegisterValidMember(org.jboss.as.quickstarts.kitchensink.test.MemberValidationTest): 
      No violations were found expected:<0> but was:<1>
   testNameViolation(org.jboss.as.quickstarts.kitchensink.test.MemberValidationTest): 
      One violation was found expected:<1> but was:<2>
    testEmailViolation(org.jboss.as.quickstarts.kitchensink.test.MemberValidationTest): 
      One violation was found expected:<1> but was:<2>
That was obviously wrong, so how do I test the case of an invalid value? :-)

**Comment by kpiwko** [comment]
Sande, if you modified createValidMember() method, you simply modified data for all tests. Now where the test expected only one failure, e.g. 

`testNameViolation()` expects the name is wrong, thus one validation error. However, you made them to be 2, so the test failed.

`testPhoneViolation()` does exactly what you wanted, it creates a valid member and then it sets invalid phone number and checks for failure.

I'll update the README soonish

**Comment by sgilda** [comment]
I guess my real question is, how do you know that the bean validation is 
catching things like an empty name, short phone number, incorrectly 
formatted email address. With the user interface, I can type in 
incorrect values and see immediate feedback. With arquillian, I'm 
unclear. :-)

**Comment by kpiwko** [comment]
Arquillian does not differ from JUnit. So it will show you only the results of the tests executed.

If you insist to have something shown on the console, you do have to add something like in your test methods:

```
for (ConstraintViolation<Member> v : violations) {
    System.out.println("Violated: " + v.getMessage();
}
```

However, this is not considered a good practice.

**Comment by kpiwko** [comment]
For some reason, the commit I did on Friday was rejected by post-recieve hook. I did a small change in README.md markup (h3 -> strong).

**Comment by sgilda** [comment]
I really like the changes to the README. Thanks!
I am able to successfully test the remote server version. However, I am having a problem with the managed server instructions.
First, I think there's a word missing in this sentence (after extracted?): "Arquillian will start the container for you. All you have to do is setup a path to your extracted . To do this, run"

I am running on Linux. I did the following:
    $ export JBOSS_HOME=/home/sgilda/tools/jboss-as-7.1.0.Final-SNAPSHOT

To make sure I defined it correctly, I list the directory:
    $ ls $JBOSS_HOME
       appclient  bin  bundles  copyright.txt  docs  domain  jboss-modules.jar  LICENSE.txt  modules  README.txt  
       standalone  welcome-content

When I run: 'mvn clean test -Parq-jbossas-managed', I get this error:
Tests in error: 
  org.jboss.as.quickstarts.kitchensink.test.MemberValidationTest: jbossHome '${jboss.home}' must exist

I haven't ever run a managed server, so it is probably something I didn't set up correctly. Do you know what I am doing wrong?

Pete, we removed all references to JBOSS_HOME from the other quickstarts. I'm assuming it's OK for Arquillian?
Thanks,
Sande

**Comment by sgilda** [comment]
Do we need to update the README with the instructions to install the POM? I hadn't looked at this one in a while and ran into the same problem I reported in the comment on January 26. Karel, you said "Yes, there's a step required, you need to install quickstart/bom into your local repository. This step would not be necessary once we have these user BOMs on Maven Central." Pete, you gave me the command "cd ../bom && mvn install && cd -". After I ran that command, I got "Testing on a Remote Server" to work. 

In "Testing on a Managed Server" , I think there's a word missing after 'extracted' here:
Arquillian will start the container for you. All you have to do is setup a path to your extracted . To do this, run

This test was not successful. My understanding is that I do not start the server and this command will start it. Is that correct? I get the same results regardless.

This is the trace :
 $ export JBOSS_HOME=~/tools/jboss-as-7.1.0.Final-SNAPSHOT
 $ mvn clean test -Parq-jbossas-managed
[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]  
[ERROR]   The project org.jboss.as.quickstarts:bean-validation:7.0.2-SNAPSHOT (/home/sgilda/Quickstarts/quickstart/bean-validation/pom.xml) has 6 errors
[ERROR]     Non-resolvable parent POM for org.jboss.as.quickstarts:jboss-as-quickstarts-bom-parent:7.0.2-SNAPSHOT: Could not find artifact org.jboss.as.quickstarts:jboss-as-quickstarts-parent:pom:7.0.2-SNAPSHOT @ org.jboss.as.quickstarts:jboss-as-quickstarts-bom-parent:7.0.2-SNAPSHOT -> [Help 2]
[ERROR]     'dependencies.dependency.version' for javax.enterprise:cdi-api:jar is missing. @ line 58, column 21
[ERROR]     'dependencies.dependency.version' for org.hibernate.javax.persistence:hibernate-jpa-2.0-api:jar is missing. @ line 66, column 21
[ERROR]     'dependencies.dependency.version' for junit:junit:jar is missing. @ line 100, column 21
[ERROR]     'dependencies.dependency.version' for org.jboss.arquillian.junit:arquillian-junit-container:jar is missing. @ line 108, column 21
[ERROR]     'dependencies.dependency.version' for org.jboss.as:jboss-as-arquillian-container-managed:jar is missing. @ line 200, column 29
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
bean-validation (bean-validation) $ mvn clean test -Parq-jbossas-managed

Did I miss something?

**Comment by pmuir** [comment]
I need to fix up the BOMs really. Let me do that tomorrow or today and then we can check.

**Comment by sgilda** [comment]
That isn't what is causing my problem, is it?

**Comment by pmuir** [comment]
Possibly, the whole thing is messed up right now.

**Comment by sgilda** [comment]
Pete, let me know when the BOM issue is resolved and I will retest.

**Comment by kpiwko** [comment]
Hello Sande,

Pete moved BOM upstream and published it in Maven Central, so I updated the coordinates. Now you should be able to run it flawlessly. 

Note I also enabled Servlet 3.0 protocol by default, as it is the one we recommend our users.

**Comment by sgilda** [comment]
Hi Karel,
Yes, this works great now! I am able to run both tests successfully.

The only thing I'm unclear about this statement: 

You can activate this test by selecting one of the container configuration provided for JBoss AS 7 / JBoss Enterprise Application Platform 6 (remote).

What does that mean? Sorry to be so dense!
Sande

**Comment by kpiwko** [comment]
Hi Sande,

that's a proper comment because it basically meant nothing at all ;). I reworded the section, please let me know if it is clearer now.

Karel

**Comment by sgilda** [comment]
Yes. I understand the reword. ;-)
Pete, are you OK with this one?

**Comment by pmuir** [comment]
Yes, please do merge :-)

**Comment by sgilda** [comment]
Done!

**Pull request closed without merging**
