### PR TITLE
Adjusts to solve JAX-WS 2.2 issue.

### PR DESCRIPTION
**Pull request by h3nrique**
Included method to solve WSFException. "Caused by: org.jboss.wsf.spi.WSFException: JBWS024104: Service class org.jboss.as.quickstarts.wsat.simple.jaxws.RestaurantServiceATService is missing required JAX-WS 2.2 additional constructors" and "Caused by: java.lang.NoSuchMethodException: org.jboss.as.quickstarts.wsat.simple.jaxws.RestaurantServiceATService.<init>(java.net.URL, javax.xml.namespace.QName, [Ljavax.xml.ws.WebServiceFeature;)"

### CODE REVIEW

**Comment by sgilda** [comment]
@ctomc : Do you know who should review this change?

@paulrobinson : You were the original owner of this one. Would you like to review it?

**Comment by paulrobinson** [comment]
This looks fine to me. I'm very rusty in this area now, but I don't see a reason to not add this additional constructor.

**Comment by sgilda** [comment]
@paulrobinson : Thanks for the response. I will wait for @ctomc to respond before I merge.

@h3nrique : Thanks for submitting the fix!

**Review by ctomc — APPROVED** [review]
This looks fine. 
But please do not merge it here yet, I will cherry-pick it as part of other changes to my development branch.

**Comment by sgilda** [comment]
@ctomc : Sure thing.

**Comment by h3nrique** [comment]
@sgilda  Thanks!

**Comment by ctomc** [comment]
cherry-picked this into my dev branch and pushed it to downstream repos.
closing this here.

**Pull request closed without merging**
