### PR TITLE
Initial appclient quickstart

### PR DESCRIPTION
**Pull request by wfink**

### CODE REVIEW

**Comment by sgilda** [comment]
@wfink : I reviewed this and it works great! I made a few minor edits to the README file and issued a pull back to you. 

I will try to find someone to do a code review.

Thanks for contributing this one!

**Comment by sgilda** [comment]
@wfink : I didn't mention. I could not test the 2 machine scenario. I assume you have tested that?

**Comment by wfink** [comment]
I'll never push something untested to the public repo ;)
But it might work only in my scenario

**Comment by sgilda** [comment]
@lightguard did a code review. He said it looks okay but he doesn't know anything about app client . He suggested I talk to Jason Greene.

**Comment by n1hility** [comment]
Looks good!

**Comment by sgilda** [comment]
Thanks @n1hility ! I will merge it!

**Comment by sgilda** [comment]
Merged!

**Pull request closed without merging**
