### PR TITLE
Fix JDF-484, JDF-485: Modify quickstart GAVs, JBoss BOM names for the reorg

### PR DESCRIPTION
**Pull request by sgilda**

### CODE REVIEW

**Comment by rafabene** [comment]
Except from a little detail it looks good now: 
- It should be '6.2.0-redhat-SNAPSHOT' instead of '6.2.0-redhat-1-SNAPSHOT' = remove '-1' on quickstarts versions

**Comment by sgilda** [comment]
Arghh! Should be good now. :-)

**Comment by rafabene** [comment]
:) If it builds ok, it is ready to merge. I didn't find any considerations on these changes

**Comment by sgilda** [comment]
I'm not able to completely build this due to this site being down: http://repository.jboss.org/

It fails on the ejb-security-interceptor: 
[ERROR] Failed to execute goal on project jboss-as-ejb-security-interceptors: Could not resolve dependencies for project org.jboss.quickstarts.eap:jboss-as-ejb-security-interceptors:jar:6.2.0-redhat-SNAPSHOT: Failed to collect dependencies for [org.jboss.as:jboss-as-security:jar:7.2.0.Final (compile), javax.enterprise:cdi-api:jar:1.0-SP4 (compile), org.jboss.spec.javax.annotation:jboss-annotations-api_1.1_spec:jar:1.0.1.Final (compile), org.jboss.spec.javax.servlet:jboss-servlet-api_3.0_spec:jar:1.0.2.Final (compile), org.jboss.spec.javax.ejb:jboss-ejb-api_3.1_spec:jar:1.0.2.Final (compile), org.jboss.ejb3:jboss-ejb3-ext-api:jar:2.0.0 (compile), org.jboss:jboss-ejb-client:jar:1.0.16.Final (compile), org.jboss.xnio:xnio-api:jar:3.0.7.GA (runtime), org.jboss.xnio:xnio-nio:jar:3.0.7.GA (runtime), org.jboss.marshalling:jboss-marshalling-river:jar:1.3.16.GA (runtime), org.jboss.spec.javax.transaction:jboss-transaction-api_1.1_spec:jar:1.0.1.Final (runtime)]: Failed to read artifact descriptor for org.jboss:staxmapper:jar:1.1.0.Final: Could not transfer artifact org.jboss:staxmapper:pom:1.1.0.Final from/to jboss-public-repository-group (http://repository.jboss.org/nexus/content/groups/public/): Connection to http://repository.jboss.org refused: Connection timed out -> [Help 1]
[ERROR]

**Comment by sgilda** [comment]
Nexus was back up and I was able to build successfully this morning. I will merge the changes.

**Pull request merged**
