### PR TITLE
Issue #165, add/fix license headers

### PR DESCRIPTION
**Pull request by pmuir**

### CODE REVIEW

**Comment by sgilda** [comment]
Pete, I tried building and deploying all of the quickstarts. They all worked except for the tasks-jsf. When I deploy, it throws a SAXParseException. I briefly looked through the XML files and didn't see anything strange. I'll continue to look.

19:11:08,798 ERROR [org.jboss.msc.service.fail](MSC service thread 1-4) MSC00001: Failed to start service jboss.deployment.unit."jboss-as-tasks-jsf.war".PARSE: org.jboss.msc.service.StartException in service jboss.deployment.unit."jboss-as-tasks-jsf.war".PARSE: JBAS018733: Failed to process phase PARSE of deployment "jboss-as-tasks-jsf.war"
    at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:120) [jboss-as-server-7.1.2.Final-SNAPSHOT.jar:7.1.2.Final-SNAPSHOT]
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) [rt.jar:1.6.0_25]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) [rt.jar:1.6.0_25]
    at java.lang.Thread.run(Thread.java:662) [rt.jar:1.6.0_25]
Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: SAXException parsing vfs:/content/jboss-as-tasks-jsf.war/WEB-INF/beans.xml
    at org.jboss.as.weld.deployment.BeansXmlParser.parse(BeansXmlParser.java:100)
    at org.jboss.as.weld.deployment.processors.BeansXmlProcessor.parseBeansXml(BeansXmlProcessor.java:133)
    at org.jboss.as.weld.deployment.processors.BeansXmlProcessor.deploy(BeansXmlProcessor.java:97)
    at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:114) [jboss-as-server-7.1.2.Final-SNAPSHOT.jar:7.1.2.Final-SNAPSHOT]
    ... 5 more
Caused by: org.xml.sax.SAXParseException: Premature end of file.
    at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:196)
    at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:175)
    at org.apache.xerces.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:394)
    at org.apache.xerces.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:322)
    at org.apache.xerces.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:281)
    at org.apache.xerces.impl.XMLScanner.reportFatalError(XMLScanner.java:1459)
    at org.apache.xerces.impl.XMLDocumentScannerImpl$PrologDispatcher.dispatch(XMLDocumentScannerImpl.java:903)
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:324)
    at org.apache.xerces.parsers.XML11Configuration.parse(XML11Configuration.java:845)
    at org.apache.xerces.parsers.XML11Configuration.parse(XML11Configuration.java:768)
    at org.apache.xerces.parsers.XMLParser.parse(XMLParser.java:108)
    at org.apache.xerces.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1196)
    at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:555)
    at org.apache.xerces.jaxp.SAXParserImpl.parse(SAXParserImpl.java:289)
    at org.jboss.as.weld.deployment.BeansXmlParser.parse(BeansXmlParser.java:94)
    ... 8 more

**Comment by sgilda** [comment]
I went through the XML files in tasks-jsf again and didn't see anything strange.

**Comment by sgilda** [comment]
As a sanity check, I tested the current jbossas/quickstart/tasks-jsf and it builds and deploys fine. So the problem is limited to your branch. 
I'll try to look at it again later tonight or tomorrow.

**Comment by pmuir** [comment]
Fixed and Merged

**Pull request closed without merging**
