### PR TITLE
Change <version.compiler.plugin>2.3.1 to 3.1

### PR DESCRIPTION
**Pull request by OndraZizka**
Tested (built with tests)

### CODE REVIEW

**Comment by sgilda** [comment]
@OndraZizka : Again, this pull has file changes for picketlink quickstarts that have been removed. Can you make sure you started with the latest code base?

**Comment by sgilda** [comment]
Closing this pull. It's replaced by https://github.com/jboss-jdf/jboss-as-quickstart/pull/594.

**Comment by OndraZizka** [comment]
No idea how the picketlink quickstarts changes got in, I had max. 2 days old git data... Never mind.

**Comment by sgilda** [comment]
@OndraZizka : I had a bunch of other QS Tools fixes, so I just incorporate these changes into my pull. I hope it works for you now. Did you try it?

**Pull request closed without merging**
