### PR TITLE
Modify README file internal links to use generated anchors. 

### PR DESCRIPTION
**Pull request by sgilda**
Remove hard-coded anchors. Fixed obsolete links and other markdown rendering problems.

### CODE REVIEW

**Comment by sgilda** [comment]
Also contains a fix for the Ruby script that generates anchors.

**Comment by sgilda** [comment]
Wait a bit to review. I ran link-checker and found some outdated links that redirect to new URL. I want to fix them too..

**Comment by rafabene** [comment]
Ok. Btw I checked the Ruby script and the regex expression seems fine!

**Comment by sgilda** [comment]
Merged.

**Pull request closed without merging**
