### PR TITLE
DO NOT MERGE - JBEAP-4786: Update tasks-rs quickstart to eliminate RESTEASY002142

### PR DESCRIPTION
**Pull request by sgilda**
DO NOT MERGE!!

### CODE REVIEW

**Comment by sgilda** [comment]
Waiting for input from @mmusgrov or @mjurc to resolve one remaining issue.

**Comment by mmusgrov** [comment]
I had to search for the "remaining issue" becaue the title of this PR contains a typo: JBEAP-4796 -> JBEAP-4786. The changes to the quickstart look good, once again thank you @sgilda

**Comment by sgilda** [comment]
@mmusgrov : Sorry about the typo. It must have happened when I changed it to WIP.
Unfortunately, this pull request does not address all of the issues. It fixes the curl GET command, but accessing it using a browser still shows the warning. See my comment here: https://issues.jboss.org/browse/JBEAP-4786?focusedCommentId=13252417&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13252417

**Comment by sgilda** [comment]
@mmusgrov : We are set. @mjurc discovered the remaining issue is caused by this server bug: https://issues.jboss.org/browse/JBEAP-3459

**Comment by mmusgrov** [comment]
Nice, well spotted @mjurc

On Wed, Jun 15, 2016 at 12:39 PM, sgilda notifications@github.com wrote:

> @mmusgrov https://github.com/mmusgrov : We are set. @mjurc
> https://github.com/mjurc discovered the remaining issue is caused by
> this server bug: https://issues.jboss.org/browse/JBEAP-3459
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/jboss-developer/jboss-eap-quickstarts/pull/1906#issuecomment-226162657,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAeHtEKVtN1jnVZ6T6JV_v0X1AGifKWQks5qL-RngaJpZM4I1khD
> .

## 

Michael Musgrove
Transactions Team
e: mmusgrov@redhat.com
t: +44 191 243 0870

Registered in England and Wales under Company Registration No. 03798903
Directors: Michael Cunningham (US), Paul Hickey (Ireland), Matt Parson
(US), Charles Peters (US)

Michael Cunningham (US), Charles Peters (US), Matt Parson (US), Michael
O'Neill(Ireland)

**Pull request merged**
