### PR TITLE
Spring and IBM MQ Integration

### PR DESCRIPTION
**Pull request by doug-grove**
Sending and receiving JMS messages in Spring from IBM MQ.

### CODE REVIEW

**Comment by sgilda** [comment]
Hi Doug,

I am not able to find the branch from which this pull was issued.  I see the following branches in your jboss-as-quickstart repository:

doug-grove/7.1.1.Final  
doug-grove/7.1.2.M1  
doug-grove/deltaspike  
doug-grove/master

The pull appears to be issued from doug/grove/3e5b567.

Should I be using your master branch?

**Comment by doug-grove** [comment]
I gather....  This is my first experience with git, so it should be on
master.

**Comment by sgilda** [comment]
Hi Doug,

I checked out your master branch but I don't see the jboss-as-spring-websphere-mq directory. It's odd, because I do see it in your repository, however it has an "ignores" in the commit comment section. I'm not sure what is going on here. 

If you are new to git, I will send you an email to try to help with this. 

Also, one more comment: Can you remove the "jboss-as-" prefix from the directory names. It would be better to name it "spring-websphere-mq".

Thanks,
Sande

**Comment by sgilda** [comment]
Closing this pull because I believe this pull was replaced by https://github.com/jboss-jdf/jboss-as-quickstart/pull/356.

**Pull request closed without merging**
