### PR TITLE
do not bundle junit.jar to ear

### PR DESCRIPTION
**Pull request by rhusar**

### CODE REVIEW

**Comment by sgilda** [comment]
@rhusar : Was this fix applied to the archetypes? Does it need to be?

**Comment by rhusar** [comment]
Do you mean /template? That one is fine -- doesnt have test scope deps.

**Comment by sgilda** [comment]
Merged.

**Comment by pmuir** [comment]
@sgilda yes, we need to push this change to the archetype as well.

**Comment by rhusar** [comment]
@pmuir Which project is that? https://github.com/jboss-jdf/jboss-as-archetype I didnt notice any test deps here, but I looked very roughly.

**Comment by pmuir** [comment]
@rhusar - this POM https://github.com/jboss-jdf/jboss-as-archetype/blob/master/jboss-javaee6-webapp-ear-archetype/src/main/resources/archetype-resources/__rootArtifactId__-ejb/pom.xml

**Comment by rhusar** [comment]
@pmuir @sgilda Got it. Let me submit a PR there too.

**Comment by rhusar** [comment]
https://github.com/jboss-jdf/jboss-as-archetype/pull/6

**Comment by sgilda** [comment]
@pmuir: doesn't it  impact 2 pom files:
- jboss-javaee6-webapp-ear-archetype/src/main/resources/archetype-resources/**rootArtifactId**-ejb/pom.xml
- jboss-javaee6-webapp-ear-blank-archetype/src/main/resources/archetype-resources/**rootArtifactId**-ejb/pom.xml

I issued a pull for the fixes, but it doesn't look right to me: https://github.com/jbossas/archetypes/pull/27

**Comment by pmuir** [comment]
@sgilda we generate -blank from the other one. We only regen it at release time normally.

**Comment by sgilda** [comment]
Ah. Good to know. Thanks @pmuir :-)

**Pull request closed without merging**
