### PR TITLE
Update for persistence xml correction

### PR DESCRIPTION
**Pull request by tomjenkinson**

### CODE REVIEW

**Comment by pmuir** [comment]
Lol, I just fixed that locally as well :-D

**Comment by sgilda** [comment]
That did it. Merged and closed.

**Comment by pmuir** [comment]
Yeah, except we're now back out of alignment :-( I'll push the alignment fix in a bit.

**Comment by sgilda** [comment]
Sorry about that. What do you mean by "out of alignment"?

**Comment by pmuir** [comment]
Datasource name doesn't follow conventions

**Pull request merged**
