### PR TITLE
Bz1013502 7.0.x develop aug5

### PR DESCRIPTION
**Pull request by rsearls**

### CODE REVIEW

**Comment by rafabene** [comment]
Something went wrong at the commit after the merge because it includes files ended with ~HEAD and ~upstream_6.4.x

**Comment by sgilda** [comment]
@rsearls : Did you rebase to 6.4.x instead of 7.0.x-develop? Also, can you squash the commits?

**Comment by rsearls** [comment]
To get remotes/upstream/7.0.x-develop into my fork of https://github.com/jboss-developer/jboss-eap-quickstarts I performed the following.
  git fetch upstream
  git checkout -b 7.0.x-develop upstream/7.0.x-develop
  git push -u origin 7.0.x-develop

Then I made a local branch to work in.
  git checkout -b bz1013502-7.0.x-develop-aug5 7.0.x-develop
  I integrated the changes. 
  commited the changed
  pushed the branch  (bz1013502-7.0.x-develop-aug5)

Why are there multiple commits in this branch?  I would not expect that.

**Comment by rsearls** [comment]
I've re-cloned my fork (https://github.com/rsearls/jboss-eap-quickstarts.git)
and set upstream (https://github.com/jboss-developer/jboss-eap-quickstarts).  Performed fetch --all
and the ~HEAD and ~upstream_6.4.x files come with this basic setup.  I don't know how to clean
this up.

**Comment by sgilda** [comment]
I don't either. I'm not clear why you needed to push 7.0.x-develop to your origin. Not necessary, but it doesn't hurt anything.

I think this "may be" wrong:

```
      git checkout -b bz1013502-7.0.x-develop-aug5 7.0.x-develop
```

I would do:

```
        git checkout -b bz1013502-7.0.x-develop-aug5 7.0.x-develop upstream/7.0.x-develop
```

I'm not clear what you did here either:
            "I integrated the changes. "

You may have to start over. This is what I would do:

$ git fetch upstream
$ git checkout -b Bz1013502-xxx upstream master

(update the files, add them, commit)

$ git push origin HEAD

Then issue the pull.

**Comment by sgilda** [comment]
I looked at your branch: https://github.com/rsearls/jboss-eap-quickstarts/commits/bz1013502-7.0.x-develop

The 3rd commit does not look right in that branch:

```
 https://github.com/rsearls/jboss-eap-quickstarts/commit/850b4bc1017c35a80aa515d55d14f61ddd314c04
```

**Comment by rsearls** [comment]
I'm closing this request. I've submitted https://github.com/jboss-developer/jboss-eap-quickstarts/pull/1470 in its place.

**Comment by rsearls** [comment]
----- Original Message -----

> From: "sgilda" notifications@github.com
> To: "jboss-developer/jboss-eap-quickstarts" jboss-eap-quickstarts@noreply.github.com
> Cc: "rsearls" rsearls@redhat.com
> Sent: Thursday, August 6, 2015 4:56:31 PM
> Subject: Re: [jboss-eap-quickstarts] Bz1013502 7.0.x develop aug5 (#1462)
> 
> I don't either. I'm not clear why you needed to push 7.0.x-develop to your
> origin. Not necessary, but it doesn't hurt anything.
> 
> I think this "may be" wrong:
> 
> ```
>       git checkout -b bz1013502-7.0.x-develop-aug5 7.0.x-develop
> ```
> 
> I would do:
> 
> ```
>         git checkout -b bz1013502-7.0.x-develop-aug5 7.0.x-develop
>         upstream/7.0.x-develop
> ```
> 
> I'm not clear what you did here either:
>             "I integrated the changes. "
> 
> You may have to start over. This is what I would do:
> 
> $ git fetch upstream
> $ git checkout -b Bz1013502-xxx upstream master

There is no upstream master.  There are only branch names.
I forked the (upstream) repo before there was a 7.0.x-develop branch,
so all of my rebaseing of 7.0.x-develop to 6.4.x-develop never worked. 
I finally figured out I had to put the 7.0.x-develop branch in my origin
and work from that.

**Comment by sgilda** [comment]
@rsearls : You are right. 7.0.x-develop is the upstream master. 

Try: 
$ git remote -v

Your upstream should look like this:

upstream    git@github.com:jboss-developer/jboss-eap-quickstarts.git (fetch)
upstream    git@github.com:jboss-developer/jboss-eap-quickstarts.git (push)

If it points to the old repo, try:
 $ git remote set-url upstream git@github.com:jboss-developer/jboss-eap-quickstarts.git 

Ping me today and I'll try to help you figure this out.

**Comment by rsearls** [comment]
Yes, when I  git remote -v I get
origin  https://github.com/rsearls/jboss-eap-quickstarts.git (fetch)
origin  https://github.com/rsearls/jboss-eap-quickstarts.git (push)
upstream    https://github.com/jboss-developer/jboss-eap-quickstarts (fetch)
upstream    https://github.com/jboss-developer/jboss-eap-quickstarts (push)

I originally forked 
    g branch -a  https://github.com/jboss-developer/jboss-eap-quickstarts before branch 
    remotes/upstream/7.0.x-develop was created so this is the branch list I initially had
  remotes/origin/6.2.x
  remotes/origin/6.3.x
  remotes/origin/6.4.x
  remotes/origin/kitchensink-angularjs
  remotes/origin/wildfly
  remotes/upstream/6.2.x
  remotes/upstream/6.3.x
  remotes/upstream/6.4.x
  remotes/upstream/kitchensink-angularjs
  remotes/upstream/wildfly

Please note that there is no  remotes/upstream/HEAD hence no master branch.

I placed my inital code in   remotes/origin/6.4.x-develop   which caused this to be created
on initial push back to origin
  remotes/origin/7.0.x-develop
  remotes/origin/HEAD -> origin/6.4.x-develop

Months later I did a  g fetch --all and branch remotes/upstream/7.0.x-develop showed up.

I have never been able to create a branch of upstream/7.0.x-develop (e.g.
g checkout -b bz1013502-7.0.x-develop upstream/7.0.x-develop  and push it to my repo (origin).
Any push attempts to send it back to upstream/7.0.x-develop and I don't have permission to
do that.

And attempting to rebase my origin/HEAD -> origin/6.4.x-develop to upstream/7.0.x-develop
and work from that never worked for me either.

After much googling I found I could make a copy of upstream/7.0.x-develop and push it to my origin/7.0.x-develop and work from that.

But in the end please do not use origin/bz1013502-7.0.x-develop-aug5.  I don't seem to be able
to fix the issues with this branch.  Please now ref origin/bz1013502-7.0.x-develop-AUG-6

**Comment by sgilda** [comment]
Your new pull looks fine, so we can definitely kill this one!

**Pull request closed without merging**
