### PR TITLE
Remove dependency on specific version and set the local versions.

### PR DESCRIPTION
**Pull request by darranl**
After a recent update to the quickstarts in a recently cleaned repo I ended up with a dependency issue as a dependency from one quickstart to another was using a specific version and as I hadn't built that specific version it was not available to satisfy the dependency.

This pull request switches to the current version instead of a specific version.

### CODE REVIEW

**Comment by sgilda** [comment]
Hi Darran, I'm testing this against boss-as-7.1.1.Final and am seeing this error on deployment:

[ERROR] Failed to execute goal on project jboss-as-ejb-in-ear-web: Could not resolve dependencies for project org.jboss.as.quickstarts:jboss-as-ejb-in-ear-web:war:7.1.1-SNAPSHOT: Could not find artifact org.jboss.as.quickstarts:jboss-as-ejb-in-ear-ejb:jar:7.1.1-SNAPSHOT -> [Help 1]

**Comment by darranl** [comment]
Ok let me take another look

**Comment by sgilda** [comment]
I'm seeing the same error when I deploy against jboss-as-7.1.0.Final. 
I will delete my local repository and try again.

**Comment by sgilda** [comment]
Same result.

**Comment by pmuir** [comment]
I ran 

```
mvn clean package jboss-as:deploy -Dmaven.repo.local=/Users/pmuir/tmp/
```

and it all deployed fine to AS 7.1.1 and AS 7.0.0

Merged

**Pull request closed without merging**
