### PR TITLE
Tasks

### PR DESCRIPTION
**Pull request by pmuir**

### CODE REVIEW

**Comment by pmuir** [comment]
This replaces pull request 91.

**Comment by pmuir** [comment]
Sande please sanity check and merge.

**Comment by sgilda** [comment]
This pull contains helloworld-errai changes in addition to the new tasks quickstart. Is that intentional?

Also, do this replace pull 91(https://github.com/jbossas/quickstart/pull/91)?

**Comment by sgilda** [comment]
Comments for the tasks quickstart:
The title in the README should be tasks, not jboss-as-tasks. 
There should be a short description in the title. Maybe something like "tasks: Test Database Access using JPA 2.0"?
There is no Author credit.

Other than minor README changes, the tasks quickstart works fine.

**Comment by sgilda** [comment]
The helloworld-errai folder contains only a src directory. Nothing else. Is that correct?

**Comment by pmuir** [comment]
Fixed the readme, removed the errai directory.

**Comment by sgilda** [comment]
Looks good. Pushed and closed.

**Pull request merged**
