### PR TITLE
Build fix

### PR DESCRIPTION
**Pull request by pgier**
Minor fixes to root pom.

### CODE REVIEW

**Comment by sgilda** [comment]
Paul, good catch on the kitchensink-er. What is the issue with the h2-console? It worked for me, or at least I thought it did.
Pete, I can take care of this one if you want.

**Comment by pgier** [comment]
There isn't any pom file in the h2-console module, so building from the
root dir gave an error for me.

https://github.com/jbossas/quickstart/tree/master/h2-console

**Comment by pgier** [comment]
There isn't any pom file in the h2-console module, so building from the
root dir gave an error for me.

https://github.com/jbossas/quickstart/tree/master/h2-console

**Comment by sgilda** [comment]
I didn't try from the parent. Good catch. 
Is this ready to merge?

**Pull request merged**
