### PR TITLE
Trim dependency tree a bit

### PR DESCRIPTION
**Pull request by ctomc**
I will follow up with more PRs on this topic.

This trims dep tree quite a bit, as removes need for half of EAP & wildfly core to be present to build ejb-security-interceptor QS

### CODE REVIEW

**Comment by sgilda** [comment]
Hi @ctomc : 
I use this command to test the build of all of the quickstarts: 

```
 mvn clean install -Pdefault,!complex-dependencies
```

When I attempt to build the quickstarts using your branch, the bean-validation-custom-constraint quickstart fails with this error:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project jboss-bean-validation-custom-constraint: Compilation failure: Compilation failure:
[ERROR] /home/sgilda/GitRepos/jboss-eap-quickstarts/bean-validation-custom-constraint/src/main/java/org/jboss/as/quickstarts/bean_validation_custom_constraint/PersonAddress.java:[29,33] package org.hibernate.annotations does not exist
[ERROR] /home/sgilda/GitRepos/jboss-eap-quickstarts/bean-validation-custom-constraint/src/main/java/org/jboss/as/quickstarts/bean_validation_custom_constraint/PersonAddress.java:[30,33] package org.hibernate.annotations does not exist
[ERROR] /home/sgilda/GitRepos/jboss-eap-quickstarts/bean-validation-custom-constraint/src/main/java/org/jboss/as/quickstarts/bean_validation_custom_constraint/PersonAddress.java:[41,6] cannot find symbol
[ERROR] symbol:   class GenericGenerator
[ERROR] location: class org.jboss.as.quickstarts.bean_validation_custom_constraint.PersonAddress
[ERROR] /home/sgilda/GitRepos/jboss-eap-quickstarts/bean-validation-custom-constraint/src/main/java/org/jboss/as/quickstarts/bean_validation_custom_constraint/PersonAddress.java:[41,89] duplicate element '<any?>' in annotation @<any?>.
[ERROR] /home/sgilda/GitRepos/jboss-eap-quickstarts/bean-validation-custom-constraint/src/main/java/org/jboss/as/quickstarts/bean_validation_custom_constraint/PersonAddress.java:[41,108] duplicate element '<any?>' in annotation @<any?>.

**Comment by sgilda** [comment]
@ctomc : I'm not clear why you removed the hibernate-core dependency from the bean-validation-custom-contraint quickstart. It needs it for the Hibernate annotations. When I add it back in, the quickstarts build fine.

**Comment by sgilda** [comment]
I talked to @ehsavoie and he said this works for him. I was using Maven 3.2.5 and he was using Maven 3.3.9. I upgraded to 3.3.9, but still get the same errors.

Next, I tried importing the bean-validation-custom-constraint into JBDS, which includes Maven 3.3.9. It gets these 4 import errors which are all related to org.hibernate.annotations not being resolved
- GenericGenerator cannot be resolved to a type PersonAddress.java  /jboss-bean-validation-custom-constraint/src/main/java/org/jboss/as/quickstarts/bean_validation_custom_constraint   line 41 Java Problem
- Parameter cannot be resolved to a type    PersonAddress.java  /jboss-bean-validation-custom-constraint/src/main/java/org/jboss/as/quickstarts/bean_validation_custom_constraint   line 41 Java Problem
- The import org.hibernate.annotations cannot be resolved   PersonAddress.java  /jboss-bean-validation-custom-constraint/src/main/java/org/jboss/as/quickstarts/bean_validation_custom_constraint   line 29 Java Problem
- The import org.hibernate.annotations cannot be resolved   PersonAddress.java  /jboss-bean-validation-custom-constraint/src/main/java/org/jboss/as/quickstarts/bean_validation_custom_constraint   line 30 Java Problem

**Comment by sgilda** [comment]
I created a JIRA to track this issue: https://issues.jboss.org/browse/JBEAP-6352

**Comment by ctomc** [comment]
This was mistake on my side hibernate-core is fine, as QS is actually using hibernate-core annotations.
we shouldn't be doing that, at least not in validator PR.
it is fixed now.

**Pull request closed without merging**
