### PR TITLE
Kitchensink-ml quickstart

### PR DESCRIPTION
**Pull request by sgilda**
The kitchensink-ml quickstart needs to be reviewed by an SME before pushing to jbossas.
It is based on the kitchensink, but I've changed a few things:
1: Added multiple language support. It currently supports English and French. I need someone with i18n experience to check that this is implemented in the correct way and is using best practices.
2. Enhanced the error reporting. For example, if you enter a duplicate key, you get the specific localised error.
I want someone to verify that the error handling is being done properly and the correct technique is being used to notify the page.
NOTE: the kitchensink-ear-ml quickstart is NOT ready yet.

### CODE REVIEW

**Comment by pmuir** [comment]
I'm not sure who the SME is for this @ JBoss…

Maybe someone at Amentra?

**Comment by sgilda** [comment]
Maybe we should just toss this quickstart. It may not be useful.

**Comment by pmuir** [comment]
I think let's defer it for this round.

**Comment by sgilda** [comment]
Agreed. I closed the pull request.

**Pull request closed without merging**
