### PR TITLE
Wsat simple

### PR DESCRIPTION
**Pull request by npfr**
Here's another Web Service transaction quickstart, which you are welcome to have if you want it.

### CODE REVIEW

**Comment by pmuir** [comment]
Generally looks good, Sande should review and test too.

Only comment is that the formatting hasn't been updated from Arjuna standards I think. I realised we don't specify that, so I added it to the CONTRIBUTING.md guide :-)

**Comment by npfr** [comment]
@pmuir I actually applied the code formatting that I thought you required. I did this by importing the AS7 eclipse formatting profile into Intellij using a 3rd party plugin. I assume something has gone wrong in the process. 

What,in particular did you notice to be wrong with the style?

**Comment by pmuir** [comment]
2 space indent in java files, should be 3 space indent... I think there is an intellij formatter now too.

**Comment by npfr** [comment]
Thanks, I'll take a look. I was hoping it was the page-width that was too short; not so keen on the amount of wrapping that has been introduced. 

However, I'm a big fan of code style standardisation, so I'm not complaining ;-)

**Comment by npfr** [comment]
I've fixed the code style.

**Comment by npfr** [comment]
Added quickstart to /README.md

**Comment by npfr** [comment]
Squashed

**Comment by sgilda** [comment]
Waiting for Paul's review based on his comment in pull/38, "I'll also take a look at some of the other quickstarts as I'm sure they will have hit the same issue".

**Comment by npfr** [comment]
Added the expected output and improved the server startup instructions. @sgilda, can you re-review please?

**Comment by npfr** [comment]
@sgilda I've fixed the inconsistencies.

**Comment by sgilda** [comment]
Hi Paul, 
This is great! Thanks for being so patient with all my nitpicking.
Pete, do we need to be concerned about the different version numbers in he Maven POM files? For example, a different version for Arquillian artifiactId (jboss-as-arquillian- *)?

**Comment by pmuir** [comment]
Yes, those need to be aligned to the current versions in HEAD.

**Comment by npfr** [comment]
@sgilda I'm happy with your nitpicking. It means our XTS users now get better quickstarts. We wouldn't have got this level of reviewing had we of put them in our repository.

**Comment by npfr** [comment]
I think I have the version numbers aligned with HEAD.
I changed 'arquillian-junit-container' and 'arquillian-protocol-servlet'.

**Comment by npfr** [comment]
Squashed

**Comment by sgilda** [comment]
Hi Paul,
Sorry, but can you update the pom.xml version numbers for this one too? 
jboss-as-arquillian-\* artifactId patterns should be 7.1.0.CR1b
org.jboss.arquillian.\* ﻿groupIds pattern should be 1.0.0.CR7.
jboss-as-maven-plugin artifactId should be 7.1.0.CR1 
The version checklist can be found here: https://docs.jboss.org/author/display/AS71/Maven+POM+Versions+Checklist
Thanks, Sande

**Comment by sgilda** [comment]
I modified the POM and README files, then issued https://github.com/jbossas/quickstart/pull/83.
Once that one is verified and pushed, I think we can close this one.

**Comment by pmuir** [comment]
83 is merged, closing this one.

**Pull request closed without merging**
