### PR TITLE
added support for Openshift in helloworld-mdb

### PR DESCRIPTION
**Pull request by andytaylor**

### CODE REVIEW

**Comment by sgilda** [comment]
Hi Andy,
I thought I had followed the instructions. but maybe I missed something.
I created an OpenShift Express account, created a domain 'sgilda'. 
I installed the client tools and that seemed to be successful.

But, I am having a problem with the rhc-create-app step. This is the result:

OpenshiftApplications $ rhc-create-app -a helloworldmdb -t jbossas-7.1
RHLogin is required
Obtaining list of cartridges (please excuse the delay)...

Usage: /usr/bin/rhc-create-app
Create an OpenShift Express app.

  -a|--app   application     Application name  (alphanumeric - max 32 chars) (required)
  -t|--type  type            Type of app to create (raw-0.1, php-5.3, jbossas-7.0, jenkins-1.4, python-2.6, perl-5.10, ruby-1.8) (required)
  -l|--rhlogin  rhlogin      Red Hat login (RHN or OpenShift login with OpenShift Express access) (required)
  -p|--password  password    RHLogin password  (optional, will prompt)
  -r|--repo  path            Git Repo path (defaults to ./$app_name)
  -n|--nogit                 Only create remote space, don't pull it locally
  -d|--debug                 Print Debug info
  -h|--help                  Show Usage info
  --no-dns                   Skip DNS check. Must be used in combination with --nogit
  --config  path             Path of alternate config file
  --timeout #                Timeout, in seconds, for connection
  --enable-jenkins [name]    Indicates to create a Jenkins application (if not already available)
                             and embed the Jenkins client into this application.  The default 
                             name will be 'jenkins' if not specified. Note that --no-dns is ignored
                             for the creation of the Jenkins application.

Did I mess up something during the setup?

**Comment by andytaylor** [comment]
you will need to provide your own login details iike the README says '-l mylogin'. Also this won't work on openshift yet until it supports jboss 7.1.

**Comment by sgilda** [comment]
I saw that in the Openshift Express notes, and had tried, but it just hangs:
OpenshiftApplications $ rhc-create-app -a helloworldmdb -t jbossas-7.1 -l sgilda
Password: /usr/lib/ruby/gems/1.8/gems/rhc-0.86.7/lib/rhc-common.rb:283: warning: Insecure world writable dir /home/sgilda/tools/byteman-download-2.0.0/bin in PATH, mode 040777

I didn't see anything in the README about '-l mylogin'. Do you mean the quickstart README? Maybe I don't have the latest?

Are you saying this won't work anyway until JBoss 7.1 is supported on OpenShift? Should I wait to test it then?

**Comment by sgilda** [comment]
I see a lot of similar issues posted on various sites. Most suggest changing permissions like this: sudo chmod -R 755 /usr/local/. That didn't work for me. I'll keep looking.

It's definitely a Ruby configuration issue and not related to OpenShift or this quickstart.

**Comment by sgilda** [comment]
Got past the problem by deleting the Byteman directory. Now I see this:
RESULT:
Found valid credentials but you haven't requested access yet

Looking into this issue now.

**Comment by sgilda** [comment]
Figured it out.
Now I see the following, with is what you indicate I should see until jbossas-7.1 is supported: 
RESULT:
Invalid application type (-t|--type) specified: ''.  Valid application types are (raw-0.1, php-5.3, jbossas-7.0, jenkins-1.4, python-2.6, perl-5.10, ruby-1.8).

**Comment by sgilda** [comment]
Byteman is used by some of the other quickstarts. I was able to get around the problem by changing the permissions in that folder and its contents: chmod -R o-rwx byteman-download-2.0.0/
I will add this comment to the quickstarts that use Byteman.

**Comment by andytaylor** [comment]
-- Are you saying this won't work anyway until JBoss 7.1 is supported on OpenShift? Should I wait to test it then?

yes, thats correct. you can test it on the staging environment see https://engineering.redhat.com/trac/Libra/wiki/Staging_Environment but you would need to amend the standalone.xml config to add the messaging subsystem. This is what i did. btw I had to tweak a few things to get the staging env to work as the instructions are slightly out of date

**Comment by sgilda** [comment]
Great. That's good to know. I did create a JBoss 7.0 app just to make 
sure it worked. :-)

Is there an estimated date for 7.1 support on OpenShift?

**Comment by pmuir** [comment]
Andy, I rewrote the instructions to push source to openshift - https://github.com/pmuir/quickstart/tree/helloworld-mdb-openshift - and tested on openshift (AS 7.1 is now live). But I get errors. Could you check it out for me?

**Comment by andytaylor** [comment]
I'll do it first thing Pete, since we didnt actually have a complete 7.1 
profile in staging i had to make some assumptions about config so its 
probably just a configuration issue.

**Comment by andytaylor** [comment]
hmmm, it seems there is not a messaging subsystem configured in the AS 
7.1 openshift configuration, I assumed that since messaging was being 
used to show of the features of a full profile it would be configured by 
default, i guess not. Whats the best way to deal with this, add a 
standalone.xml config to the quickstart and change the readme to push 
this to the git repo? Also, if I create this what restrictions are there 
in openshift re threading, memory, disk space, can I use persistence for 
the journal etc etc?

Andy

**Comment by sgilda** [comment]
Is this quickstart and folder going to be renamed to helloworld-mdb-openshift?

**Comment by pmuir** [comment]
No. Why would it be?

**Comment by sgilda** [comment]
I was thrown by the helloworld-mdb-openshift. Then it's just the helloworld-mdb quickstart with additional instructions?

**Comment by pmuir** [comment]
yes.

**Comment by sgilda** [comment]
Are we waiting for a decision how best to configure a messaging subsystem for this quickstart OpenShift?

**Comment by pmuir** [comment]
Yes.

**Comment by pmuir** [comment]
Replaced by #236

**Pull request closed without merging**
