### PR TITLE
removed all version properties which are not used in root pom.xml

### PR DESCRIPTION
**Pull request by mareknovotny**

### CODE REVIEW

**Comment by sgilda** [comment]
@rafabene : Can you review this to make sure it will not break anything anywhere (quickstarts, QS tools, etc.)?

**Comment by sgilda** [comment]
@rafabene : Please let me know if this is okay to merge.

**Comment by rafabene** [comment]
It seems ok for me :) Sorry to take so long to answer

**Comment by sgilda** [comment]
Merged!

**Pull request closed without merging**
