### PR TITLE
Configure Undertow MIME-type mapping to be compatible with Spring MVC

### PR DESCRIPTION
**Pull request by trepel**
This configuration will become unnecessary when Undertow 1.3.0.CR3 or later will be used in EAP 7

### CODE REVIEW

**Comment by ctomc** [comment]
we already have CR3 in upstream WildFly, and will get into next EAP release, not sure if this patch is really needed for this few days....

**Comment by trepel** [comment]
To be honest, me neither. If the next EAP 7 version is about to be released in just few day, feel free to close this one without merging.

**Comment by sgilda** [comment]
@trepel , @ctomc : Does this pull fix an outstanding issue with this quickstart when deployed and run on JBoss EAP 7? If so, can you describe the issue?

**Comment by trepel** [comment]
@sgilda : not really, only one link (exporting vets to xml) is not working:
http://localhost:8080/jboss-spring-petclinic/vets.xml

Apart from this the example works OK, but this causes one functional test to fail, see
https://github.com/jboss-developer/jboss-eap-quickstarts/pull/1661#issuecomment-149446004

In my opinion we can wait few days for new EAP7 version. On the other hand I will remove it as soon as new EAP7 version is available, so there's no problem in merging this either.

**Comment by sgilda** [comment]
I built the current WildFly from source, and tested this pull against it. It ran successfully, but there's a warning at the end. 

```
Results :

Tests run: 32, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] <<< cobertura-maven-plugin:2.7:check (default) < [cobertura]test @ jboss-spring-petclinic <<<
[INFO] 
[INFO] --- cobertura-maven-plugin:2.7:check (default) @ jboss-spring-petclinic ---
[INFO] Cobertura 2.1.1 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
[INFO] Cobertura: Loaded information on 42 classes.

[INFO] All checks passed.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

....

[WARNING] The requested profile "arq-wildfly-remote" could not be activated because it does not exist.
```

I'm still not clear what you are saying here. Is this change permanently needed or are you saying it's needed temporarily?

**Comment by ctomc** [comment]
well, new EAP build was already published that uses newer undertow that doesn't need this workaround anymore.

**Comment by sgilda** [comment]
Then I propose we close this pull. Does that work for you? :-)

**Comment by sgilda** [comment]
Closing this based on @ctomc 's comment above.

**Pull request closed without merging**
