### PR TITLE
Forge from scratch

### PR DESCRIPTION
**Pull request by sgilda**
Modified the README to point out the generated application code.

### CODE REVIEW

**Comment by sgilda** [comment]
This is based on this pull: https://github.com/jbossas/quickstart/pull/53
When this is pushed, we can close that one also.

**Comment by pmuir** [comment]
Squashed and merged.

**Comment by lincolnthree** [comment]
Awesome! Thanks guys~!

**Comment by sgilda** [comment]
Lincoln, please let me know if you don't like the way I sectioned and 
reworded your readme. We just wanted to get it out there for people to 
use. :-)

**Comment by lincolnthree** [comment]
No, this looks great! Thanks!

**Comment by sgilda** [comment]
No problem. You did all the hard work. Thanks again for doing this one!

**Pull request closed without merging**
