### PR TITLE
Grails Kitchensink App added

### PR DESCRIPTION
**Pull request by TejasM**

### CODE REVIEW

**Comment by sgilda** [comment]
@TejasM : Is there a reason class files are checked into Git on this commit?

**Comment by sgilda** [comment]
This builds and runs great! However, the form has 3 input fields without labels, so it's not clear what you need to enter in the fields. I had to guess by clicking the button and getting errors. :-)

**Comment by sgilda** [comment]
Apparently the classes are not generated and are required. Just curious why they aren't in a JAR?

Also, just curious about the empty directories, for example: lib/, src/groovy/, src/java/

**Comment by TejasM** [comment]
@sgilda: Thx for the starting the review! I made the mistake of relying on the master gitignore that is why binary files  got added. I think I have fixed that up, but will check to make sure. I will go through the other mistakes and fix those soon as well.

**Comment by sgilda** [comment]
I think you may have lost the README changes with the commit. :-)

**Comment by TejasM** [comment]
Lucky I had them in my email, so I think I got most of the fixes in at this point. And for the empty src/java and src/groovy, I think they are add by the grails plugin for files that might not be part of the grails-app itself.

**Comment by sgilda** [comment]
OK. Sounds good. :-)

**Comment by sgilda** [comment]
@TejasM 
When you run the application, it displays "You have successfully deployed a basic Spring MVC web application".
Should it say "You have successfully deployed a Grails web application"?

**Comment by TejasM** [comment]
@sgilda: Yep that would indeed make sense :)

**Comment by sgilda** [comment]
Looks good!

@pmuir : Do you need to do a code review?

**Comment by pmuir** [comment]
@sgilda, this is one for @joshuaw to review.

**Comment by joshuawilson** [comment]
@sgilda @pmuir Sure I can review it.

**Comment by joshuawilson** [comment]
@TejasM The errors on the UI do not display cleanly.

If you leave everything blank and try to Register, the errors for Name and Email list the class.

**Comment by joshuawilson** [comment]
@TejasM The Phone Number field does not have validation on it when left blank.

The validation on what is typed works.

**Comment by joshuawilson** [comment]
@TejasM 

I found the following errors in the pom.xml in Eclipse with both JBDS and the Grails plugin installed.
It is worth noting that it works from the command line.

```
- Plugin execution not covered by lifecycle configuration: org.grails:grails-maven-plugin:2.2.3:config-directories (execution: default-config-directories, phase: generate-
 sources)
- Plugin execution not covered by lifecycle configuration: org.grails:grails-maven-plugin:2.2.3:maven-compile (execution: default-maven-compile, phase: compile)
- Plugin execution not covered by lifecycle configuration: org.grails:grails-maven-plugin:2.2.3:validate (execution: default-validate, phase: validate)
- Plugin execution not covered by lifecycle configuration: org.grails:grails-maven-plugin:2.2.3:init (execution: default-init, phase: initialize)
```

**Comment by joshuawilson** [comment]
@TejasM Most of the .groovy code is missing comments and licenses.

**Comment by sgilda** [comment]
Comment from @joshuawilson on IRC last evening:

```
    I just talked with Tejas and he will not be able to get Booking or Grails fixed before the re-org
```

**Comment by sgilda** [comment]
Closing for now. Will reopen after reorg.

**Pull request closed without merging**
