### PR TITLE
quickstart-43

### PR DESCRIPTION
**Pull request by pmuir**

### CODE REVIEW

**Comment by sgilda** [comment]
This looks much better to me!
Pete, how did you fix it?

**Comment by sgilda** [comment]
Pete, do you want me to push this to jbossas? You can verify my push here: https://github.com/sgilda/quickstart/tree/hibernate3-pmuir

**Comment by pmuir** [comment]
Blood, sweat and tears ;-). I just had to walk through all the conflicts and resolve them.

**Comment by pmuir** [comment]
Go ahead and push.

**Pull request merged**
