### PR TITLE
Bz1087471: Failed attempt to resolve No matching SeamConversationContext

### PR DESCRIPTION
**Pull request by sgilda**
Updated to wicket-cdi 6.14.0 and added seam-conversation-weld dependency to get rid of the warning message.

### CODE REVIEW

**Comment by sgilda** [comment]
This pull is ready for review.

**Comment by LightGuard** [comment]
Really? The Seam Conversation code hasn't been touched in nearly three years, it's not very good and could be done much better, especially in light of CDI 1.1. Are we sure we want this in one of our QuickStarts?

**Comment by sgilda** [comment]
@lightguard : I'm just trying to get rid of the warning messages. If you have a better solution, can you describe it?

**Comment by LightGuard** [comment]
Unfortunately I don't have a better one, unless the Wicket guys have CDI
1.1 integration.

On Mon, Apr 21, 2014 at 3:14 PM, sgilda notifications@github.com wrote:

> @lightguard https://github.com/lightguard : I'm just trying to get rid
> of the warning messages. If you have a better solution, can you describe it?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jboss-developer/jboss-eap-quickstarts/pull/937#issuecomment-40978016
> .

## 

Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by sgilda** [comment]
@lightguard: Are you okay with these changes then? Or should I ask @ozizka to rewrite the quickstart?

**Comment by LightGuard** [comment]
I'm not sure if it's the best, but if it's all we have, it's probably
better than nothing.

On Mon, Apr 21, 2014 at 3:46 PM, sgilda notifications@github.com wrote:

> @lightguard https://github.com/lightguard: Are you okay with these
> changes then? Or should I ask @ozizka https://github.com/ozizka to
> rewrite the quickstart?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jboss-developer/jboss-eap-quickstarts/pull/937#issuecomment-40980897
> .

## 

Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by sgilda** [comment]
@LightGuard : I think it's also better than it was before because it's updated to use the newer artifacts.  Should I merge?

**Comment by LightGuard** [comment]
Go ahead—

**Comment by mareknovotny** [comment]
hmm, we should not add such outdated technology/library as Seam 3 to our top set of QS which is the GUIDE for end users. This is a BAD example how to show a fix!

**Pull request merged**
