### PR TITLE
Updated the version of jboss-javaee-6.0 to 3.0.0.Final

### PR DESCRIPTION
**Pull request by fjuma**

### CODE REVIEW

**Comment by pmuir** [comment]
Looks good, Sande can you test and merge?

**Comment by sgilda** [comment]
Pete: Is there a better way to test than to build , deploy, and run each one individually?

**Comment by sgilda** [comment]
I tested a couple that had the change to jboss-javaee-6.0 to 3.0.0.Final and a couple of the jboss-jsf-api_2.1_spec changes and they work with no problem. Do I need to test all of them?

**Comment by pmuir** [comment]
The only way to test is to do a full build and deploy on all.

**Comment by pmuir** [comment]
Let me see if building from root will work.

**Comment by pmuir** [comment]
Merged

**Pull request closed without merging**
