### PR TITLE
First stab at porting kitchensink to use angularjs

### PR DESCRIPTION
**Pull request by pmuir**

### CODE REVIEW

**Comment by pmuir** [comment]
Please don't merge for now. I still need to rewrite the README, and need to get feedback on my JS!

**Comment by LightGuard** [comment]
I don't know much about angular as I haven't used it yet, but the JS code looks fine.

**Comment by pmuir** [comment]
Ok, I've made my fixes now, please do review!

**Comment by pmuir** [comment]
I've merged this.

**Pull request closed without merging**
