### PR TITLE
Declared the proxy server settings in Maven configuration file (settings.xml)

### PR DESCRIPTION
**Pull request by girirajsharma**
Declared the proxy server settings in Maven configuration file (settings.xml) to enable downloading of dependencies through Maven in case of proxy servers. 

Signed-off-by: girirajSharma giriraj.sharma27@gmail.com

### CODE REVIEW

**Comment by rafabene** [comment]
Except for the header formatting It looks good to merge. We can fix the header formatting ourselves.

**Comment by sgilda** [comment]
@girirajsharma : Thanks so much for submitting this one! For future contributions, you might want to read through the Quickstarts Contributing Guide located on this page: http://www.jboss.org/jdf/quickstarts/get-involved. The General Guidelines section tells you how to configure your IDE to use the JBoss  profiles.

I will reformat this one before merging. Thanks again.

**Comment by sgilda** [comment]
@girirajsharma : I just noticed there are tabs throughout this file now. In the future, please use 2 spaces in place of tabs. :-)

**Comment by girirajsharma** [comment]
@sgilda : I am extremely sorry for poor formatting of the committed file(settings.xml). After making changes,I formatted the file with default eclipse settings for formatting xml files rather than the one as required by JBOSS AS quickstarts format for xml files. I shall be committing files in prescribed file format in future. :) Thanks a lot for the guide.

**Comment by sgilda** [comment]
Fixed formatting issues and merged.

**Pull request closed without merging**
