### PR TITLE
Applied workaround for JBEAP-2187 in spring-petclinic

### PR DESCRIPTION
**Pull request by trepel**

### CODE REVIEW

**Comment by sgilda** [comment]
@trepel : It looks like a number of JSP source files have changed. I thought we were supposed to work 'out-of-the-box' with no source code changes. Is this a workaround due to a problem with the `petclinic` app or is it due to an issue in JBoss EAP 7?

**Comment by trepel** [comment]
Hi @sgilda , it's difficult to say, there is no comment in https://issues.jboss.org/browse/JBEAP-2187 which would explain why this is happening and I didn't find time to investigate it myself.
The fact is that those relative paths no longer work in EAP7 (at least for me), I think the only thing we can do is to workaround it.

**Comment by sgilda** [comment]
@trepel : We've had a pretty strict rule about not making code changes to the `spring-petclinic` quickstart. We need to find out why this is happening. If it's a bug in JBoss EAP, we should fix it. If the issue is truly with the Spring petclinic code, we need to report it or submit a fix back to the project. If is is their problem and we do need to make a change, we need to document what we changed and why we did it. 

I commented on the JIRA. Let's see what they have to say.

**Comment by sgilda** [comment]
@trepel : I am closing this pull because it looks like they plan to fix the issue.

**Pull request closed without merging**
