### PR TITLE
add example of TransactionAttributeType.REQUIRES_NEW

### PR DESCRIPTION
**Pull request by gkephorus**
An example to show how a method marked with TransactionAttributeType.REQUIRES_NEW does commit a record while the former transaction can still fail.
One can see this by running the application and adding a 'customer' whose name starts with a 'p'. This will result in a LogMessage-record in the database but not a customer-record neither will a JMS-message be delivered.

Signed-off-by: Gerke - Ephorus gerke.ephorus@gmail.com

### CODE REVIEW

**Comment by sgilda** [comment]
@gkephorus : Thanks for submitting an enhancement to this quickstart! Would you mind rebasing your code against the latest code base? There have been a lot of changes since you checked out your branch and I want to make sure it is based off the latest source. 

Here's some additional feedback in the mean time:
-  I'm not sure I like it failing with 'Customer Already Existed' when you add a name that starts with 'P'. Maybe you could have it fail if the name contains special characters. For example, if it doesn't contain only  'A-Z',  'a-z', or spacesand put out the error "Name may only contain valid letters (A-Z or a-z) or spaces"
- Also, you may want to modify the README.md file to talk about the new functionality, particularly in the section "Access the application". 

When you submit the above changes, I will schedule the code review.

Thanks again.

**Comment by gkephorus** [comment]
Thanks for your comments. I will try to 'rebase' which should be simple as the code in the cmt-module did not change. And I'll update the README.md.

Also a good idea to make the 'restriction' a bit more realistic. We do'nt want to discriminate customers just for having a name that starts with 'P' ;-).

I tried to build the cmt-module of HEAD but I'm having a hard time. It currently yields:

```
[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.jboss.quickstarts.eap:jboss-cmt:6.2.0-redhat-SNAPSHOT (/opt/development/gerke/src/foreign/jboss-eap-quickstarts/cmt/pom.xml) has 7 errors
[ERROR]     Non-resolvable import POM: Failure to find org.jboss.bom.eap:jboss-javaee-6.0-with-tools:pom:6.2.0-build-7 in http://maven.repository.redhat.com/earlyaccess/all/ was cached in the local repository, resolution will not be reattempted until the update interval of jboss-earlyaccess-repository has elapsed or updates are forced @ line 66, column 25 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for org.jboss.spec.javax.transaction:jboss-transaction-api_1.1_spec:jar is missing. @ line 78, column 21
[ERROR]     'dependencies.dependency.version' for org.jboss.spec.javax.faces:jboss-jsf-api_2.1_spec:jar is missing. @ line 84, column 21
[ERROR]     'dependencies.dependency.version' for org.hibernate.javax.persistence:hibernate-jpa-2.0-api:jar is missing. @ line 90, column 21
[ERROR]     'dependencies.dependency.version' for org.jboss.spec.javax.jms:jboss-jms-api_1.1_spec:jar is missing. @ line 96, column 21
[ERROR]     'dependencies.dependency.version' for org.jboss.spec.javax.ejb:jboss-ejb-api_3.1_spec:jar is missing. @ line 102, column 21
[ERROR]     'dependencies.dependency.version' for javax.inject:javax.inject:jar is missing. @ line 108, column 21
```

when I do 'mvn3 package'. That was to good thing about doing it against the 2.1.8-Final branch ;-), it worked.

What do I do wrong?

**Comment by sgilda** [comment]
The quickstarts currently under development in the master branch require artifacts in the JBoss developer Maven repository, which is located at http://jboss-developer.github.io/temp-maven-repo/. As a quickstart contributor working with the latest code base, you need to follow the instructions in the `CONTRIBUTING.md` file, particularly the instuctions `Configure Maven`: https://github.com/jboss-developer/jboss-eap-quickstarts/blob/master/CONTRIBUTING.md#configure-maven

I hope that helps. Please let me know if you have any other questions.

**Comment by gkephorus** [comment]
@sgilda: thanks for the pointer. I did read some Contributing but failed to pickup the 'contributor-' in 'contributor-settings.xml' ;-). Thanks.

I created a new PR. Should I close this one and go on in the other? If so: see you there ;-)

**Comment by sgilda** [comment]
Since you made the changes in a new branch, I will close this one. Normally, you can do a forced update in the original branch. If you need help with that, let me know. :-)

**Pull request closed without merging**
