### PR TITLE
Add properties removed in automated header commit. Convert special characters to unicode.

### PR DESCRIPTION
**Pull request by sgilda**

### CODE REVIEW

**Comment by LightGuard** [comment]
Looks fine, not sure why we're adding back in the English to the i18n files, but whatever.

**Comment by sgilda** [comment]
Not sure what you mean by "adding back" ???

**Comment by LightGuard** [comment]
I guess they weren't there in the first place, so why are they there now?
Not that it affects anything, just wondering.

On Fri, Mar 22, 2013 at 2:37 PM, sgilda notifications@github.com wrote:

> Not sure what you mean by "adding back" ???
> 
> On 03/22/2013 04:08 PM, Jason Porter wrote:
> 
> > Looks fine, not sure why we're adding back in the English to the i18n
> > files, but whatever.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/jboss-jdf/jboss-as-quickstart/pull/481#issuecomment-15318905
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jboss-jdf/jboss-as-quickstart/pull/481#issuecomment-15320265
> .

## 

Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by sgilda** [comment]
I don't see any new files. Can you give me a specific file name?

**Comment by LightGuard** [comment]
New comments. The messages in the translation files.

On Fri, Mar 22, 2013 at 2:43 PM, sgilda notifications@github.com wrote:

> I don't see any new files. Can you give me a specific file name?
> 
> On 03/22/2013 04:38 PM, Jason Porter wrote:
> 
> > I guess they weren't there in the first place, so why are they there now?
> > Not that it affects anything, just wondering.
> > 
> > On Fri, Mar 22, 2013 at 2:37 PM, sgilda notifications@github.com
> > wrote:
> > 
> > > Not sure what you mean by "adding back" ???
> > > 
> > > On 03/22/2013 04:08 PM, Jason Porter wrote:
> > > 
> > > > Looks fine, not sure why we're adding back in the English to the i18n
> > > > files, but whatever.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > 
> > https://github.com/jboss-jdf/jboss-as-quickstart/pull/481#issuecomment-15318905
> > 
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on
> > > GitHub<
> > > https://github.com/jboss-jdf/jboss-as-quickstart/pull/481#issuecomment-15320265
> > > 
> > > .
> > 
> > ## 
> > 
> > Jason Porter
> > http://en.gravatar.com/lightguardjp
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/jboss-jdf/jboss-as-quickstart/pull/481#issuecomment-15320342
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jboss-jdf/jboss-as-quickstart/pull/481#issuecomment-15320554
> .

## 

Jason Porter
http://en.gravatar.com/lightguardjp

**Pull request merged**
