### PR TITLE
JDF-410 - Move richfaces-validation to richfaces-quickstarts submodules

### PR DESCRIPTION
**Pull request by rafabene**

### CODE REVIEW

**Comment by sgilda** [comment]
Never mind. It works by naming the top level only. This looks good. Merging now.

**Comment by sgilda** [comment]
@rafabene : I decided to run 1 more test. 

When I do the root `mvn clean install '-Pdefault,!complex-dependencies' , the`helloworld-rf`and`kitchensink-rf` build, but the richfaces-validation quickstart does not.

Since there is no root pom in the richfaces repository, should we keep the richfaces-validation module, but qualify it with the directory name as we do with the other 2 richfaces quickstarts? For example: 

```
            <module>richfaces-quickstarts/richfaces-validation</module>
```

**Comment by rafabene** [comment]
Yes. We should. I miss that.

Thanks for the review. I'll update the PR.

**Comment by sgilda** [comment]
Merged.

**Comment by rafabene** [comment]
Merged

**Pull request closed without merging**
