### PR TITLE
JDF-168 Added Contributing Guide and Release Procedure

### PR DESCRIPTION
**Pull request by rafabene**

### CODE REVIEW

**Comment by pmuir** [comment]
I thought we were moving release process to a RELEASING.md (or similarly named) file?

**Comment by pmuir** [comment]
Otherwise great.

**Comment by sgilda** [comment]
@pmuir: He named it RELEASE_PROCEDURE.md. Do you prefer a different name?

**Comment by pmuir** [comment]
Doh, I'm blind. Looks good, let's merge it.

**Comment by sgilda** [comment]
Merged.

**Pull request closed without merging**
