### PR TITLE
Rs 33

### PR DESCRIPTION
**Pull request by LightGuard**
Here's the updated RS-33 with the change to /task. It incorporates everything from Mike's pull request.

### CODE REVIEW

**Comment by sgilda** [comment]
Did the rest URL change for this one?

$ curl -i -u "quickstartUser:quickstartPassword" -H "Content-Length: 0" -X POST http://localhost:8080/jboss-as-tasks-rs/task/task1
HTTP/1.1 404 Not Found
Server: Apache-Coyote/1.1
Content-Type: text/html;charset=utf-8
Content-Length: 1301
Date: Fri, 04 May 2012 00:10:16 GMT

<html><head><title>JBoss Web/7.0.14.Final - Error report</title><style></style> </head><body><h1>HTTP Status 404 - Could not find resource for relative : /task/task1 of full path: http://localhost:8080/jboss-as-tasks-rs/task/task1</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Could not find resource for relative : /task/task1 of full path: http://localhost:8080/jboss-as-tasks-rs/task/task1</u></p><p><b>description</b> <u>The requested resource (Could not find resource for relative : /task/task1 of full path: http://localhost:8080/jboss-as-tasks-rs/task/task1) is not available.</u></p><HR size="1" noshade="noshade"><h3>JBoss Web/7.0.14.Final</h3></body></html>

**Comment by sgilda** [comment]
It appears the URL changed from 'task/' to 'tasks/'? 

Is that correct? If so, the README needs to change all instances of "http://localhost:8080/jboss-as-tasks-rs/task/" to "http://localhost:8080/jboss-as-tasks-rs/tasks/".

**Comment by LightGuard** [comment]
Updated. Thanks. I didn't even think to look in the readme.

**Comment by pmuir** [comment]
Thanks Jason.

Sande, I'm now happy with the coe.

**Comment by sgilda** [comment]
Not sure what the 'coe' is, but I'm happy with this one too. :-)
Want me to push it?

**Comment by pmuir** [comment]
The coe is like the code, but without a d. It's how all the cool kids speak nowadays, I'll have you know :-)

**Comment by sgilda** [comment]
I'm soooooooo uncool. :-(

**Comment by sgilda** [comment]
Should I push this in? I'm happy with it.

**Comment by pmuir** [comment]
Go for it.

**Pull request merged**
